### ISSUE TITLE
Add TextColor parsing to the Gutter

### ISSUE THREAD

**Issue by gabizou** [DemonWav/MinecraftDevIntelliJ#10]
Just like event listeners and how IntelliJ ultimate will show off java.awt.Color instances in the gutter, and Icons, we should be able to parse over `PsiElement`s that contain references to some various color based classes from different platforms.

Perhaps optionally make it where they are explicit to only show the first color instance found in a line if there are multiple colors in play?

It'd be very similar to how the [`ListenerLineMarkerProvider`](https://github.com/DemonWav/MinecraftDevIntelliJ/blob/master/src/main/java/com/demonwav/mcdev/insight/ListenerLineMarkerProvider.java#L64-L77) is handled.

**Comment by DemonWav** [comment]
That would be a good option, though by default we should probably show up to 3 icons if there's 3 or more in a row. Seems to me that's about how Ultimate behaves.

**Comment by DemonWav** [comment]
IntelliJ already has a hard limit on how many gutter icons can show, so we don't need to worry about that.
