### ISSUE TITLE
Commit import from Fabric-example-mod

### ISSUE THREAD

**Issue by UltraBlackLinux** [DemonWav/MinecraftDevIntelliJ#1012]
## My suggestion
I'd like this plugin to allow for importing commits from the [fabric example mod](https://github.com/FabricMC/fabric-example-mod) into the current project.

## Why?
It would make porting mods to different minecraft versions so much easier, as you can just copy all the required commits instead of having to do it yourself, or fork the FEM and so not having this plugin's functionality.

**Comment by RedNesto** [comment]
That's a no for me, I don't see the point of having an option to clone the repo when it is already really easy to do so manually (or via IntelliJ UI.)

The wizard also includes many options that we wouldn't be able to offer when using FEM, add multi-platform setups to that. Good luck implementing it correctly.

**Comment by UltraBlackLinux** [comment]
> That's a no for me, I don't see the point of having an option to clone the repo when it is already really easy to do so manually (or via IntelliJ UI.)
> 
> The wizard also includes many options that we wouldn't be able to offer when using FEM, add multi-platform setups to that. Good luck implementing it correctly.

It's not about cloning the repo or forking it. I'd just like to import major commits like version changes from the FEM repo directly. I had to do this manually previously, and doing this 2 times is already painful enough - I had to do it 5 times.

**Comment by RedNesto** [comment]
Sounds out of the scope of the plugin then. We do not provide migration of any kind for buildscripts or anything else currently, and it seems like a lot of trouble.

**Comment by UltraBlackLinux** [comment]
> Sounds out of the scope of the plugin then. We do not provide migration of any kind for buildscripts or anything else currently, and it seems like a lot of trouble.

Isn't this plugin supposed to make mod creation easy?
Let me show you this - If you want to upgrade your fabric mod to 1.17 you have to do this:
- https://github.com/FabricMC/fabric-example-mod/commit/54035654b75dd756d98f89fde179cb49183a6d68#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7
- https://github.com/FabricMC/fabric-example-mod/compare/29c522536fc16233833221e22eed3f106c0726bc...1.17
- https://fabricmc.net/versions.html
- https://fabricmc.net/wiki/tutorial:migratemappings

This is so annoying. Considering that you also have to push it out to github, I really feel like this should be a part of this plugin.
As I said, I had to do this 5 times - It took me several hours just with new 1.17 problems, creating releases, and fixing some bugs related to upgrading

**Comment by RedNesto** [comment]
The plugin never made _updating_ easier.

While I agree that this would be useful, an update system would require a pretty large amount of work and maintenance, we'd have to do it right, and it might break with any tooling change (look at what MC 1.17 did with Java 16, and FG5.)

In your specific case "importing commits" is just asking for troubles. Applying patches will not work for anyone that touched their buildscript a fair bit.

I don't think it'll be done anytime soon, if ever if someone is interested in working on it in the first place, and just for Fabric. Let alone supporting the tooling of the different modding frameworks, and keeping up with any future changes that might happen.

**Comment by UltraBlackLinux** [comment]
I found a workaround: I just cloned the fabric example mod repo to get my patches from there
