### ISSUE TITLE
Execution failed for task ':processResources'

### ISSUE THREAD

**Issue by HoseonYim** [DemonWav/MinecraftDevIntelliJ#1020]
Hi I think I have a bug while building a plugin.
So I'm making this spigot plugin in minecraft version 1.17.1 and the Minecraft Development plugin is on the latest version.
Also I'm using IntelliJ 2021.1.3 and  JDK 16 which makes me use gradle 7 (which I think that makes the bug)

**When it builds it stops building with this message.**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Entry plugin.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0/dsl/org.gradle.api.file.CopySpec.html#org.gradle.api.file.CopySpec:duplicatesStrategy for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

**And in build.gradle code it has this code**
```
processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
    }
}
```

I was searching if there was a way to find out if I could fix this problem by myself and I found this Issue.
[Issue link](https://github.com/minecraft-dev/MinecraftDev/issues/973)
In this Issue it has a very similar error with me(maybe same) and you said you have fixed so I tried like for 3 times making a new project but it said the same every time.
So, that is why I'm asking if you could fix this bug.

**Comment by dacoev** [comment]
Also I'm using window 10

**Comment by RedNesto** [comment]
Indeed this is a duplicate of #973

I have fixed this in a PR that is not merged yet.

**Comment by HoseonYim** [comment]
could I know when this would be merged?

**Comment by RedNesto** [comment]
I have no idea.

**Comment by HoseonYim** [comment]
wish it would be merged in the next update :(
