### ISSUE TITLE
ForgeGradle version selection field

### ISSUE THREAD

**Issue by Will0376** [DemonWav/MinecraftDevIntelliJ#1024]
Hi. I really like this plugin and use it a lot.
I am using version 1.12.2, and noticed that recently FG4 has been used,
which does not work very well on this version (for example, resources that are not loaded in userdev)
Once templates are used - can add a separate ForgeGradle version selection field for 1.12?
I would add it myself, but alas, I don't know Kotlin...

And yet - what about the mixin checkbox for this version?

(Oh yes. I'm using google translate)

**Comment by RedNesto** [comment]
I'm not sure if we'll update the 1.12.2 template to use newer FG versions. And I doubt we'll add a FG version selector.
You can still [customize templates as you wish](https://www.jetbrains.com/help/idea/using-file-and-code-templates.html), and use [the FG3+ template](https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/resources/fileTemplates/j2ee/forge/Forge%20(1.13+)%20build.gradle.ft) as a base.

> And yet - what about the mixin checkbox for this version?

That's because Forge doesn't bundle Mixin in 1.12.2.

**Comment by Will0376** [comment]
> I'm not sure if we'll update the 1.12.2 template to use newer FG versions.

Well, actually, I wanted to roll back to a 'stable' FG2)

> You can still customize templates as you wish

How much I use IDEA - this is the first time I hear about this, thanks for the tip

> That's because Forge doesn't bundle Mixin in 1.12.2.

After compilation? there is a separate MixinBootstrap for this... If in Dev - it is added by several fields to the build.gradle template (almost the same as in 1.13+)

**Comment by RedNesto** [comment]
> Well, actually, I wanted to roll back to a 'stable' FG2)

Hum I should get more sleep.

FG4 worked fine for me last time I used it, you can use our current 1.12.2 templates as a base then. But it'd be better to get your issue fixed properly.

About the Mixins, I mean that Forge doesn't use it in 1.12.2, you are responsible for setting it up correctly by yourself.

**Comment by Will0376** [comment]
> FG4 worked fine for me last time I used it, you can use our current 1.12.2 templates as a base then. But it'd be better to get your issue fixed properly.

May I ask you to check the health of resources (textures, lang files)? Because when I create from a template(FG4), no resource is loaded, throwing a FileNotFoundException error

> About the Mixins, I mean that Forge doesn't use it in 1.12.2, you are responsible for setting it up correctly by yourself.

Okay, I get it.

> Hum I should get more sleep.

Life is hard for a programmer :)

**Comment by RedNesto** [comment]
I can't help you with that, you should ask in some discord server that does Forge 1.12.2 support.

**Comment by Will0376** [comment]
> I can't help you with that

I know how to fix this, but there are several steps, from the nasty 'idea.module.inheritOutputDirs = true' along with 'sourceSets {main {output.resourcesDir (output.classesDirs.getAsPath ())}}' 
where the last step would be manual adjustment of storage parameters for Gradle resources in the project.
When nothing had to be fixed in FG2 and worked initially
And basically he doesn't know how to fix it correctly, without using 'crutches'...

> Forge 1.12.2 support.

It will be difficult to do, because all discord servers that I know refer to old versions with inexplicable aggression for me...
Maybe Lexmanos bit them? :D

**Comment by Will0376** [comment]
So, I get it. using version 2847 we get FG2, which is what I need

**Comment by SizableShrimp** [comment]
FG3+ on forge 1.12.2 does have some issues, namely assets not loading. However it is easily fixed using a forked version of LegacyDev. for better support see Modded Minecraft discord server in #mod-dev
