### ISSUE TITLE
Cannot build fresh Paper 1.17.1 plugin

### ISSUE THREAD

**Issue by berwil-1** [DemonWav/MinecraftDevIntelliJ#1026]
IntelliJ IDEA 2021.1.3 (Community Edition)
Build #IC-211.7628.21, built on July 4, 2021
Runtime version: 11.0.11+9 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.10.49-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins: com.demonwav.minecraft-dev (2021.1-1.5.12-248)
Kotlin: 211-1.4.32-release-IJ7628.19
Current Desktop: XFCE
Target platform: Paper

From a fresh Paper project with JDK version 16.0.1 and Gradle 7.0 I get this error when building the project for the first time, it only seems to occur with Gradle and Paper, Maven Paper works and Gradle Spigot works.
```
Could not resolve io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by RedNesto** [comment]
In `build.gradle` bump the compatibility properties to Java 16:
```
sourceCompatibility = '16'
sourceCompatibility = '16'
```

And to anticipate another issue, replace the `processResources` block with the following:

```
processResources {
    def props = ['version': version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
```

And in the `plugin.yml` replace `version: @version@` with `version: ${version}`

These will be fixed with #994

**Comment by BadHunyun** [comment]
Where are your JDK16???(doge)

**Comment by RedNesto** [comment]
Fixed by the PR mentioned in my previous comment.
