### ISSUE TITLE
Support for official mappings on forge

### ISSUE THREAD

**Issue by Mysterious-Dev** [DemonWav/MinecraftDevIntelliJ#1032]
It's maybe a godd idea to add support for official mapping on the forge creation panel.
![image](https://user-images.githubusercontent.com/40738104/126903319-07873286-7c5b-4566-b20f-b67aeb0eecc4.png)

**Comment by Mysterious-Dev** [comment]
Maybe use a checkbox called "Use Official Mapping" and set this on the gradle template when the checkbox is checked. What do you think ?

**Comment by RedNesto** [comment]
That's what I am planning to do ^^

**Comment by Mysterious-Dev** [comment]
Awesome.  If you want, I can try to do this.

**Comment by RedNesto** [comment]
I think it'd be better to have another ComboBox instead, so we can support other mappings channels (like parchment.)

I'm currently updating the Forge templates so there might be conflicts with whatever you might change in the wizard step class.

**Comment by Mysterious-Dev** [comment]
Yes, it's a good idea.
