### ISSUE TITLE
Imports with 1.17(Official mapped) breaking when using "Minecraft Class" option.

### ISSUE THREAD

**Issue by PugzAreCute** [DemonWav/MinecraftDevIntelliJ#1063]
Creating a new "Minecraft Class" with option "Item"(Only tested with "Item" as of now) it imports `net.minecraft.item.Item` for Item.Properties. While in 1.17(Official mapped), it was changed to `net.minecraft.world.item.Item`

Target platform: Forge
OS: Linux(Debian 10)
IJ Version: `IntelliJ IDEA 2021.2 (Ultimate Edition)`
McDev version: `2021.2-1.5.12`

**Comment by RedNesto** [comment]
We'd have to expose SrgManager to the templates.

**Comment by PugzAreCute** [comment]
Probably, And I assume this will come out with #1032

**Comment by RedNesto** [comment]
Not necessarily, your issue is not about the wizard.

Also we need to be careful about what we expose to templates though, we'd rather not accidentally break templates with API changes.

**Comment by PugzAreCute** [comment]
Yeah, breaking templates is a bad thing

**Comment by Mysterious-Dev** [comment]
Can be close with this [commit](https://github.com/minecraft-dev/MinecraftDev/commit/62e1c65ef2c5bc4cf78f73522a715abcf26c1ff2)

**Comment by PugzAreCute** [comment]
Sure! Thanks for informing me!
