### ISSUE TITLE
Bothersome warning on newer versions.

### ISSUE THREAD

**Issue by Lemon-Lord** [DemonWav/MinecraftDevIntelliJ#1074]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version
2021.2-1.5.12
* IntelliJ version
Build #IC-212.4746.92, built on July 27, 2021
* Operating System (this has come up enough times to be worth noting)
Windows 10, standard installation.

**The bug:**

In modern versions of Minecraft, this warning is incorrect and makes it look like the file has an error and makes error-tapping large projects with entities slightly more trouble than it should be.
![image](https://user-images.githubusercontent.com/62090471/128600073-caa8672a-3c9a-48c6-a485-d0ac311a199d.png)
The warning could be left in and changed to accommodate for the newer format of `net.minecraft.entity.EntityType.IFactory` but this sounds like unnecessary effort so please just remove the warning as (opinion) I cannot see it being helpful even if it was working as intended. Should note this has been cropping up for a few versions now without being fixed so my apologies if this is a duplicate, with all the autogenerated issues I did not want to scroll back through all the entries to check. I did think it was fixed a few versions ago as it was not appearing but MinecraftDev might just have not been working at the time.

Thank you for your time.

**Comment by RedNesto** [comment]
This is already fixed in nightly builds by https://github.com/minecraft-dev/MinecraftDev/commit/92f39c1937f9ecef7cafafdb6d5dd404541601a0
