### ISSUE TITLE
There was an error attempting to retrieve versions error - Bukkit, Spigot and Paper

### ISSUE THREAD

**Issue by SteakFisher** [DemonWav/MinecraftDevIntelliJ#1156]
* Minecraft Development for IntelliJ plugin version 2021.2-1.5.13
* IntelliJ version Community 2021.2
* Operating System Windows
* (optional) Target platform - All forks of Bukkit

whenever launching a project using any fork of Bukkit I get the error "there was an error attempting to retrieve versions" 
![image](https://user-images.githubusercontent.com/88953813/129466341-df2f0f73-c1d6-42c2-a645-800bd227e689.png)

I've attempted using the nightly versions and older stable versions but it didn't work.

**Comment by RedNesto** [comment]
Hi, this error is usually caused by internet hiccups, or more rarely when our website AND GitHub is unreachable.

**Comment by SteakFisher** [comment]
> Hi, this error is usually caused by internet hiccups, or more rarely when our website AND GitHub is unreachable.

I'm not sure whthr that's the problem.. as I tried restarting my router several times, and my wifi speed is recorded as 100 mb up and 200 down with 4 ping, and Minecraft server's seem fine, is there anything else I can try perhaps? I also tried running the app as admin in case smth else was interfering with it.. but no it still didn't work, moreover the problem came out of the blue, I don't remember doing anythin, not even updating the plugin, so anything else I can try?

**Comment by RedNesto** [comment]
Do you see JSON text at https://minecraftdev.org/versions/spigot.json ?

If not then something prevents you from reaching the website, otherwise reproduce the issue and send the IDE logs, maybe there is more info there.

**Comment by SteakFisher** [comment]
> Do you see JSON text at https://minecraftdev.org/versions/spigot.json ?
> 
> If not then something prevents you from reaching the website, otherwise reproduce the issue and send the IDE logs, maybe there is more info there.

Oh ye I am NOT able to reach the link.. I've also been having trouble reaching bukkit forums, even tho spigot forums work perfectly well, could it be connected perhaps?, not to mention the fact that my mc launcher has also been havin severe problems as of late as in showing me the demo of the game for the 50th time even though my account is full access java.

**Comment by RedNesto** [comment]
I can't know if it's connected, but that's definitely the problem, even though there is a backup link at https://raw.githubusercontent.com/minecraft-dev/minecraftdev.org/master/versions/spigot.json used when the website can't be reached.

I would be surprised if you can access github.com but not raw.githubusercontent.com

**Comment by SteakFisher** [comment]
> I can't know if it's connected, but that's definitely the problem, even though there is a backup link at https://raw.githubusercontent.com/minecraft-dev/minecraftdev.org/master/versions/spigot.json used when the website can't be reached.
> 
> I would be surprised if you can access github.com but not raw.githubusercontent.com

so how do I change the link it attempts to access? also no I am able to access raw.githubusercontent.com, it just redirects me to github

**Comment by RedNesto** [comment]
> so how do I change the link it attempts to access?

You don't, the plugin tries it automatically, but if you can't reach the github link too then you're stuck unfortunately. You have to find why you can't access these pages.

I can still take a look at your IDE logs if you want to post them.

**Comment by SteakFisher** [comment]
> > so how do I change the link it attempts to access?
> 
> You don't, the plugin tries it automatically, but if you can't reach the github link too then you're stuck unfortunately. You have to find why you can't access these pages.
> 
> I can still take a look at your IDE logs if you want to post them.

Srry for the late reply, but after I got up tday MOST of the problems seemed to be fixed (like the mc and bukkit problems) but the 2 website links that u sent me still doesnt work, my IDE logs are at https://pastebin.ubuntu.com/p/szCfD3Mjq2/ srry for the trouble...

**Comment by RedNesto** [comment]
As long as it works in the IDE that's fine, I am still puzzled as to why you can't reach the links manually.

The logs do not contain any error related to the project creator, we might need to improve logging for that.

**Comment by SteakFisher** [comment]
> As long as it works in the IDE that's fine, I am still puzzled as to why you can't reach the links manually.
> 
> The logs do not contain any error related to the project creator, we might need to improve logging for that.

well.. if it means anything I do see this at 
![image](https://user-images.githubusercontent.com/88953813/129563704-d59636f0-2be7-4137-a007-c919c68541a7.png)
the link u sent.. but its the alternative link and you mentioned the plugin tries to approach it if the main doesnt work.. but I can manually reach the link..

**Comment by RedNesto** [comment]
Ah ok, this is what you should get on both links. At least one works for you.

I guess this issue can be closed then ?

**Comment by SteakFisher** [comment]
I wish so.. cuz I AM gettin that on 1 link, but the original problem of it being unable to retrieve mc versions still persists
![image](https://user-images.githubusercontent.com/88953813/129564805-b5ae158c-6098-4e0e-8dc1-485709196f0c.png)

**Comment by RedNesto** [comment]
Well that's weird. I can try to add more logging to the next version and hope that it will uncover the real cause.

**Comment by SteakFisher** [comment]
> Well that's weird. I can try to add more logging to the next version and hope that it will uncover the real cause.

Oh so I can't do anything to fix this? thats sad.. but fair ig, thx for ur patience, ig I could edit my previous plugins, thx a lot tho

**Comment by RedNesto** [comment]
> Oh so I can't do anything to fix this?

I can't do anything until I know why you can reach one link in your browser but the wizard can't.

**Comment by SteakFisher** [comment]
> > Oh so I can't do anything to fix this?
> 
> I can't do anything until I know why you can reach one link in your browser but the wizard can't.

I understand, thx tho, I'll wait it out, maybe once I get back after my vacation it may work there..

**Comment by satyamedh** [comment]
well 24 days later and I'm still having this issue, I can reach the raw githubusercontent link, but your minecraftdec site is refusing to connect

this issue should be re-opened

**Comment by codeaye** [comment]
Its the exact same issue for me! I dont know what is causing this.

**Comment by kroazi** [comment]
我也有这个问题，就导致我无法创建项目。qaq

**Comment by kroazi** [comment]
> 

so，这个问题咋解决啊XD
