### ISSUE TITLE
Velocity 3.0.0

### ISSUE THREAD

**Issue by Lorenzo0111** [DemonWav/MinecraftDevIntelliJ#1226]
Velocity 3.0.0 has been released from about 3 months, can you add support for it?

**Comment by RedNesto** [comment]
The templates are already done, it'll be available in the next release.

**Comment by Lorenzo0111** [comment]
ok

**Comment by RedNesto** [comment]
Velocity 3.0.0 and 4.0.0-SNAPSHOT are now available in the wizard.
