### ISSUE TITLE
Help Me to solve this plz There was an error while attempting to retrieve versions

### ISSUE THREAD

**Issue by idarkode** [DemonWav/MinecraftDevIntelliJ#1245]
https://github.com/minecraft-dev/MinecraftDev/blob/deee64b5af6fc5fa440b6198579b6961e649a7cd/src/main/kotlin/platform/bukkit/creator/BukkitProjectSettingsWizard.form#L89

**Comment by RedNesto** [comment]
We are already aware of this issue, nothing you can do, and not sure what we can do on our end to fix this for good.
