### ISSUE TITLE
Suggestions for build type

### ISSUE THREAD

**Issue by shmezi** [DemonWav/MinecraftDevIntelliJ#1479]
Hey, was wondering a few things.
1. Can you add gradle.kts as an option? It's better in my opinion and I end up manually changing it every time which is annoying. 
2. Can you add a default build type option so we don't mistake use the wrong one (gradle vs maven)
3. instead of group, artifact etc maybe just have the main class name ?

Thanks for all the development I use it on a daily basis.

**Comment by RedNesto** [comment]
Hi,

> Can you add gradle.kts as an option?

I plan to add it along with the Kotlin templates (probably after #1033 is merged)

> Can you add a default build type option so we don't mistake use the wrong one (gradle vs maven)

Do you mean a personal preference option ? That'd be nice.
I was thinking about implementing it this summer. This can be a good first PR for whoever is interested ;)

> instead of group, artifact etc maybe just have the main class name ?

No, we use these fields for some data required by the the build systems, in all cases we have to get those information and the current way is the most optimal I can see.

**Comment by shmezi** [comment]
I mean can't you just use the group from the MainClass thing and artifact is the main class?

me.alwxirving.plugin.Main
?
