### ISSUE TITLE
I don't understand how this happend

### ISSUE THREAD

**Issue by Rydjinn** [DemonWav/MinecraftDevIntelliJ#1491]
So I made a new modpack for myself and it crashes on startup. I don't know what's causing it but it's very annoying 

Here is  the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FTBUltimineASM (ftb-ultimine-1202.3.5.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  midnight (themidnight-0.3.5.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  Backpacked (backpacked-1.4.3-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.082210-core.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  BringMeTheRings plugin (BringMeTheRings-0.4.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  craftfallessentials (CraftfallEssentials-1.12.2-1.2.5.jar)
  ThaumicWandsCore (thaumicwands-1.2.6.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.4.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  AUCoreMod (actuallyunbreaking-1.12.2-0.3.0.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/4/21 8:27 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1142)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1142)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1499002816 bytes (1429 MB) / 2026897408 bytes (1933 MB) up to 14070841344 bytes (13419 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 155 mods loaded, 155 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                  | Source                                                | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| L     | minecraft                                    | 1.12.2                   | minecraft.jar                                         | None                                     |
	| L     | mcp                                          | 9.42                     | minecraft.jar                                         | None                                     |
	| L     | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge                                        | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                         | None                                     |
	| L     | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                         | None                                     |
	| L     | backpacked                                   | 1.4.2                    | backpacked-1.4.3-1.12.2.jar                           | None                                     |
	| L     | crafttweaker                                 | 4.1.20                   | CraftTweaker2-1.12-4.1.20.660.jar                     | None                                     |
	| L     | jei                                          | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| L     | abyssalcraft                                 | 1.10.4                   | AbyssalCraft-1.12.2-1.10.4.jar                        | None                                     |
	| L     | acintegration                                | 1.11.3                   | AbyssalCraft Integration-1.12.2-1.11.3.jar            | None                                     |
	| L     | actuallyunbreaking                           | 1.12.2-0.3.0             | actuallyunbreaking-1.12.2-0.3.0.jar                   | None                                     |
	| L     | forgeendertech                               | 1.12.2-4.5.5.0           | ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar          | None                                     |
	| L     | adlods                                       | 1.12.2-1.0.8.0           | AdLods-1.12.2-1.0.8.0-build.0504.jar                  | None                                     |
	| L     | aether_legacy                                | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                            | None                                     |
	| L     | codechickenlib                               | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | None                                     |
	| L     | ancientwarfare                               | 1.12.2-2.7.0.1038        | ancientwarfare-1.12.2-2.7.0.1038.jar                  | None                                     |
	| L     | ancientwarfareautomation                     | 1.12.2-2.7.0.1038        | ancientwarfare-1.12.2-2.7.0.1038.jar                  | None                                     |
	| L     | ancientwarfarenpc                            | 1.12.2-2.7.0.1038        | ancientwarfare-1.12.2-2.7.0.1038.jar                  | None                                     |
	| L     | ancientwarfarestructure                      | 1.12.2-2.7.0.1038        | ancientwarfare-1.12.2-2.7.0.1038.jar                  | None                                     |
	| L     | ancientwarfarevehicle                        | 1.12.2-2.7.0.1038        | ancientwarfare-1.12.2-2.7.0.1038.jar                  | None                                     |
	| L     | antiqueatlas                                 | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
	| L     | antiqueatlasoverlay                          | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
	| L     | placebo                                      | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                              | None                                     |
	| L     | apotheosis                                   | 1.12.4                   | Apotheosis-1.12.2-1.12.5.jar                          | None                                     |
	| L     | appleskin                                    | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                           | None                                     |
	| L     | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                                | None                                     |
	| L     | ebwizardry                                   | 4.3.4                    | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| L     | arcane_essentials                            | 1.0                      | Arcane Essentials-1.0.0-alpha-11.jar                  | None                                     |
	| L     | carrots                                      | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                       | None                                     |
	| L     | armorunder                                   | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                         | None                                     |
	| L     | aroma1997core                                | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                      | None                                     |
	| L     | aroma1997sdimension                          | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar       | None                                     |
	| L     | grimoireofgaia                               | 1.7.2                    | GrimoireOfGaia3-1.12.2-1.7.2.jar                      | None                                     |
	| L     | patchouli                                    | 1.0-23.6                 | Patchouli-1.0-23.6.jar                                | None                                     |
	| L     | potioncore                                   | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                         | None                                     |
	| L     | astralsorcery                                | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                      | None                                     |
	| L     | zettaimagic                                  | 1.4.2                    | ZettaiMagic+1.4.2.jar                                 | None                                     |
	| L     | arte_magicum                                 | 1.3.0                    | ArteMagicum-1.3.0.jar                                 | None                                     |
	| L     | artifacts                                    | 1.12.2-1.2.3             | Artifacts-1.12.2-1.2.3.jar                            | None                                     |
	| L     | quark                                        | r1.6-179                 | Quark-r1.6-179.jar                                    | None                                     |
	| L     | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                                 | None                                     |
	| L     | speedsterheroes                              | 1.12.2-2.2.1             | SpeedsterHeroes-1.12.2-2.2.1.jar                      | None                                     |
	| L     | lucraftcore                                  | 1.12.2-2.4.16            | LucraftCore-1.12.2-2.4.16.jar                         | None                                     |
	| L     | heroesexpansion                              | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar                      | None                                     |
	| L     | star-tech                                    | 1.1.1                    | star-tech-1.1.1.jar                                   | None                                     |
	| L     | avengerstech                                 | 4.3                      | AvengersTech 4.3.jar                                  | None                                     |
	| L     | betterbuilderswands                          | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar       | None                                     |
	| L     | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                          | None                                     |
	| L     | bettermineshafts                             | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar                | None                                     |
	| L     | bibliocraft                                  | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                     | None                                     |
	| L     | biomesoplenty                                | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar         | None                                     |
	| L     | cyclicmagic                                  | 1.20.11                  | Cyclic-1.12.2-1.20.11.jar                             | None                                     |
	| L     | runesofwizardry                              | 1.12.2-0.9.3             | Runes-of-Wizardry-1.12.2-0.9.3.jar                    | None                                     |
	| L     | guideapi                                     | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                           | None                                     |
	| L     | bloodmagic                                   | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                       | None                                     |
	| L     | bookshelf                                    | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                          | None                                     |
	| L     | bountifulbaubles                             | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar                    | None                                     |
	| L     | bmtr                                         | 0.4                      | BringMeTheRings-0.4.jar                               | None                                     |
	| L     | carryon                                      | 1.12.3                   | carryon-1.12.2-1.12.4.16.jar                          | None                                     |
	| L     | champions                                    | 1.12.2-1.0.11.10         | champions-1.12.2-1.0.11.10.jar                        | None                                     |
	| L     | ctm                                          | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| L     | chisel                                       | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                          | None                                     |
	| L     | clumps                                       | 3.1.2                    | Clumps-3.1.2.jar                                      | None                                     |
	| L     | toughasnails                                 | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar           | None                                     |
	| L     | comforts                                     | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                           | None                                     |
	| L     | controlling                                  | 3.0.10                   | Controlling-3.0.10.jar                                | None                                     |
	| L     | corpse                                       | 1.12.2-1.0.8             | corpse-1.12.2-1.0.8.jar                               | None                                     |
	| L     | cosmeticarmorreworked                        | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                  | None                                     |
	| L     | ftblib                                       | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                    | None                                     |
	| L     | ftbutilities                                 | 5.4.1.131                | FTBUtilities-5.4.1.131.jar                            | None                                     |
	| L     | craftfallessentials                          | 1.2.5                    | CraftfallEssentials-1.12.2-1.2.5.jar                  | None                                     |
	| L     | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.20.660.jar                     | None                                     |
	| L     | crafttweakerjei                              | 2.0.3                    | CraftTweaker2-1.12-4.1.20.660.jar                     | None                                     |
	| L     | thaumcraft                                   | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                      | None                                     |
	| L     | crimsonrevelations                           | 0.8                      | crimsonrevelations-0.8.jar                            | None                                     |
	| L     | crimsonwarfare                               | 1.5                      | crimsonwarfare-1.5.jar                                | None                                     |
	| L     | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar                       | None                                     |
	| L     | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar                   | None                                     |
	| L     | disenchanter                                 | 1.7                      | disenchanter-[1.12]1.7.jar                            | None                                     |
	| L     | dungeonsmod                                  | @VERSION@                | DungeonsMod-1.12.2-1.0.8.jar                          | None                                     |
	| L     | elevatorid                                   | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                         | None                                     |
	| L     | eplus                                        | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                     | None                                     |
	| L     | enchdesc                                     | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar             | None                                     |
	| L     | janine                                       | 1.0.0                    | Entities and Titans.jar                               | None                                     |
	| L     | golems                                       | 7.1.9                    | ExtraGolems-1.12-7.1.9.jar                            | None                                     |
	| L     | extra_spells                                 | 1.2.0                    | ExtraSpells-1.12.2-1.2.0.jar                          | None                                     |
	| L     | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                                 | None                                     |
	| L     | mod_lavacow                                  | 1.3.0                    | Fish's Undead Rising-1.3.0.jar                        | None                                     |
	| L     | forbidden_arcanus                            | 1.12.2-1.1.4             | forbidden_arcanus-1.12.2-1.1.4.jar                    | None                                     |
	| L     | ftbultimine                                  | 1202.3.5                 | ftb-ultimine-1202.3.5.jar                             | None                                     |
	| L     | cfm                                          | 6.3.1                    | furniture-6.3.1-1.12.2.jar                            | None                                     |
	| L     | craftablewizardry                            | 2.0                      | GIsCraftableWizardryItems-2.0.jar                     | None                                     |
	| L     | gottschcore                                  | 1.14.0                   | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar        | None                                     |
	| L     | grapplemod                                   | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                           | None                                     |
	| L     | llibrary                                     | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                            | None                                     |
	| L     | herobrinemod                                 | 0.6.0                    | herobrinemod-0.6.2.jar                                | None                                     |
	| L     | iceandfire                                   | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                           | None                                     |
	| L     | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                            | None                                     |
	| L     | infinity                                     | 1.12                     | infinity-1.12.jar                                     | None                                     |
	| L     | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | None                                     |
	| L     | ironchest                                    | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
	| L     | journeymap                                   | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| L     | jeid                                         | 1.0.3-55                 | JustEnoughIDs-1.0.3-55.jar                            | None                                     |
	| L     | jeresources                                  | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	| L     | lordcraft                                    | 1.0.0                    | Lord Craft 2.10.3.jar                                 | None                                     |
	| L     | lostmagic                                    | 1.0                      | lostmagic-1.0.2.jar                                   | None                                     |
	| L     | lycanitesmobs                                | 2.0.7.2 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.7.2.jar                      | None                                     |
	| L     | mahoutsukai                                  | 1.12.2-v1.19.49          | mahoutsukai-1.12.2-v1.19.49.jar                       | None                                     |
	| L     | mca                                          | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                        | None                                     |
	| L     | mobdismemberment                             | 7.0.0                    | MobDismemberment-1.12.2-7.0.0.jar                     | None                                     |
	| L     | mobends                                      | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar                | None                                     |
	| L     | morph                                        | 7.2.0                    | Morph-1.12.2-7.2.1.jar                                | None                                     |
	| L     | mousetweaks                                  | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	| L     | mowziesmobs                                  | 1.5.8                    | mowziesmobs-1.5.8.jar                                 | None                                     |
	| L     | mutantbeasts                                 | 1.12.2-1.0.2             | MutantBeasts-1.12.2-1.0.2.jar                         | None                                     |
	| L     | naturescompass                               | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                       | None                                     |
	| L     | neat                                         | 1.4-17                   | Neat 1.4-17.jar                                       | None                                     |
	| L     | overpoweredarmorbar                          | @VERSION@                | overloadedarmorbar-1.0.4g.jar                         | None                                     |
	| L     | thaumicwands                                 | 1.2.6                    | thaumicwands-1.2.6.jar                                | None                                     |
	| L     | polymancy                                    | 1.0.1                    | polymancy-1.0.1.jar                                   | None                                     |
	| L     | potionfingers                                | r1.0-8                   | PotionFingers-r1.0-8.jar                              | None                                     |
	| L     | progressivebosses                            | 1.5.4                    | ProgressiveBosses-1.5.4-mc1.12.x.jar                  | None                                     |
	| L     | reccomplex                                   | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                          | None                                     |
	| L     | xreliquary                                   | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                        | None                                     |
	| L     | additionalstructures                         | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar      | None                                     |
	| L     | roguelike                                    | 2.4.0                    | RoguelikeDungeonsFnarEdition-1.12.2-2.4.0.jar         | None                                     |
	| L     | ruins                                        | 17.2                     | Ruins-1.12.2.jar                                      | None                                     |
	| L     | runesofwizardry_classics                     | 1.12.2-0.5.8             | RunesofWizardry-Classics-1.12.2-0.5.8.jar             | None                                     |
	| L     | silentlib                                    | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                       | None                                     |
	| L     | scalinghealth                                | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                   | None                                     |
	| L     | somanyenchantments                           | 0.5.2                    | SoManyEnchantments-0.5.2.jar                          | None                                     |
	| L     | spartanweaponry                              | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	| L     | spartanfire                                  | 0.08                     | spartanfire-0.08.jar                                  | None                                     |
	| L     | stg                                          | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                  | None                                     |
	| L     | twilightforest                               | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar         | None                                     |
	| L     | tfspellpack                                  | 1.1.0                    | TFSpellPack-1.1.0-MC1.12.2.jar                        | None                                     |
	| L     | thaumicaugmentation                          | 1.12.2-2.1.4             | ThaumicAugmentation-1.12.2-2.1.4.jar                  | None                                     |
	| L     | tcinventoryscan                              | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar            | None                                     |
	| L     | thaumictinkerer                              | 1.12.2-5.0-620a0c5       | thaumictinkerer-1.12.2-5.0-620a0c5.jar                | None                                     |
	| L     | beneath                                      | 1.7.1                    | The Beneath-1.12.2-1.7.1.jar                          | None                                     |
	| L     | toughnessbar                                 | @VERSION@                | toughnessbar-2.4.jar                                  | None                                     |
	| L     | treasure2                                    | 1.16.1                   | Treasure2-mc1.12.2-f14.23.5.2854-v1.16.1.jar          | None                                     |
	| L     | treasure2_wizardry_lp                        | 1.0.0                    | Treasure2WizardryLP-mc1.12.2-f14.23.5.2854-v1.0.0.jar | None                                     |
	| L     | xat                                          | 0.30                     | Trinkets and Baubles-0.30.1.jar                       | None                                     |
	| L     | waystones                                    | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                            | None                                     |
	| L     | witherskelefix                               | 2.6.3                    | WitherSkeletonTweaks-1.12.2-2.6.3.jar                 | None                                     |
	| L     | wizardrygolems                               | 1.2.0                    | WizardryGolems-1.1.0.jar                              | None                                     |
	| L     | zettaigrimoires                              | 1.4.9                    | ZettaiGrimoires+1.4.9.jar                             | None                                     |
	| L     | ancientspellcraft                            | 1.12.2-1.2.0             | AncientSpellcraft-1.12.2-1.2.0.jar                    | None                                     |
	| L     | craftstudioapi                               | 1.0.0                    | CraftStudio-1.0.1.95-mc1.12-alpha.jar                 | None                                     |
	| L     | cyclopstek                                   | 1.0.34                   | cyclopstek-1.0.34.jar                                 | None                                     |
	| L     | phosphor-lighting                            | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar           | None                                     |
	| L     | thebetweenlands                              | 3.7.3                    | TheBetweenlands-3.7.3-universal.jar                   | None                                     |
	| L     | midnight                                     | 0.3.5                    | themidnight-0.3.5.jar                                 | None                                     |

	Loaded coremods (and transformers): 
FTBUltimineASM (ftb-ultimine-1202.3.5.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
Backpacked (backpacked-1.4.3-1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
  
ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  shadows.ApotheosisTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.082210-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
BringMeTheRings plugin (BringMeTheRings-0.4.jar)
  zabi.minecraft.bmtr.core.BaublesTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
craftfallessentials (CraftfallEssentials-1.12.2-1.2.5.jar)
  com.hydrosimp.craftfallessentials.core.CEClassTransformer
ThaumicWandsCore (thaumicwands-1.2.6.jar)
  de.zpenguin.thaumicwands.asm.WandTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.4.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
AUCoreMod (actuallyunbreaking-1.12.2-0.3.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GT 710/PCIe/SSE2'
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by RedNesto** [comment]
Hi, this is not the place to ask for help with mods. There's probably a couple of places where you can get help with forge 1.12.2.

**Comment by Rydjinn** [comment]
Then where do I go?

**Comment by RedNesto** [comment]
I don't know, you are on your own when using old versions.
