### ISSUE TITLE
Add Event Factory Generation

### ISSUE THREAD

**Issue by gabizou** [DemonWav/MinecraftDevIntelliJ#15]
Sponge provides a nice event generation utility that consumes event interfaces and produces a static factory generating the necessary methods to create those events. It would be a long term goal to possibly have some sort of event class generation through the modules.

For Bukkit based platforms, the event generation would be as simple as providing the class name, the fields desired, etc.

**Comment by DemonWav** [comment]
This is complete for all platforms sans Sponge. I will open a separate issue for the more complex event factory generation required for Sponge.
