### ISSUE TITLE
Add spigot-api dependency when creating a Paper based plugin for MC 1.17+

### ISSUE THREAD

**Issue by Kamilkime** [DemonWav/MinecraftDevIntelliJ#1589]
When creating a new Paper project for MC 1.17 or 1.17.1 (so versions using the new Paper artifact maven groups) - no bukkit or spigot API is actually added to a project, I guess it always was a transitive dependency but now isn't (?). For older MC versions - adding just paper-api works fine.

So I'd like to suggest adding also a spigot-api dependency when creating a new Paper project.

**Comment by RedNesto** [comment]
I don't see any mention of bukkit or spigot-api in https://papermc.io/using-the-api
Are you sure these artifacts are needed for a paper plugin ?

**Comment by Kamilkime** [comment]
For me, when I make a plugin for MC 1.17 or 1.17.1 - the main class throws errors, IJ cannot find e.g. the JavaPlugin class import. If I use the old artifacts for MC 1.16.5 and lower - it's all ok, the org.bukkit classes are found.

**Comment by Kamilkime** [comment]
After clearing Gradle and Maven caches from the io.papermc folders - seems like Gradle isn't even downloading the artifact correctly, but the old (pre 1.17) artifacts re-download correctly

**Comment by RedNesto** [comment]
Ah yes somehow the project creator doesn't set the java version to 16. You have to modify your build.gradle manually.

**Comment by Kamilkime** [comment]
Yup, now that I've changed it - it downloads correctly. So it would probably be best to set `targetJavaVersion` to 16 when using the newer Paper builds
