### ISSUE TITLE
IntelliJ IDEA Community Edition 2021.3 (Build: 213.3714.440) not supported?

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#1598]
Please include the following information in all bug reports:

* 2021.2-1.5.12
* IntelliJ IDEA Community Edition 2021.3 (Build: 213.3714.440)
* Windows 10

https://prnt.sc/1uab1x8

Does the project still not have support for 2021.3? I know it's still in beta in version 2021.3, but do you have a deadline to add?

**Comment by RedNesto** [comment]
The 2021.3 branch is already available and is working fine (been using it since the EAP release). What's left is configuring the CI server to publish it AFAIK, and I have no idea when that'll be done.

**Comment by ghost** [comment]
I got it, thanks.
