### ISSUE TITLE
Invalid ID for plugin

### ISSUE THREAD

**Issue by gjorgdy** [DemonWav/MinecraftDevIntelliJ#1644]
When trying to compile a Velocity plugin I receive the following:
Invalid ID for plugin eu.hexasis.helixchat.HelixChat. IDs must start alphabetically, have alphanumeric characters, and can contain dashes or underscores.

**Comment by RedNesto** [comment]
Change the `@Plugin` id to `helixchat` in your main class.

The project creator does not prevent usage of invalid values yet.
