### ISSUE TITLE
Error while retrieving version while trying to make spigot 1.17.1 plugin

### ISSUE THREAD

**Issue by ihsan6133** [DemonWav/MinecraftDevIntelliJ#1656]
I tried to make a plugin for my spigot 1.17.1 server. I have Intellij IDEA 2021.2.3 (Community edition) Please fix, I want to make a plugin

**Comment by GreenArrowlol** [comment]
I too am unable to make a plugin due to my IDEA showing *error while retreving version*

**Comment by ihsan6133** [comment]
got any idea anyone?

**Comment by Glender2** [comment]
So how was this problem solved?

**Comment by GreenArrowlol** [comment]
still get the issue
