### ISSUE TITLE
Paper Icon - 1.17

### ISSUE THREAD

**Issue by BlockyTheDev** [DemonWav/MinecraftDevIntelliJ#1712]
* 2021.2-1.5.15
* 2021.2.3
* Windows 10
* Paper

When I'm using "Paper" for 1.17.1 development I'm seeing the Bukkit-Icon instead of the PaperMC-Icon, I think it's because in 1.17 the package was changed to ``io.papermc.paper:paper-api`` ... (See picture)
![image](https://user-images.githubusercontent.com/86119630/142249722-465d087b-ec26-4c15-90d2-c8a1d6aabcb1.png)

**Comment by HyperSkys** [comment]
This isn't very important but I do not see the image on my IDE, maybe try updating the plugin or updating IntellIJ

**Comment by BlockyTheDev** [comment]
> This isn't very important but I do not see the image on my IDE, maybe try updating the plugin or updating IntellIJ

Intellij and the plugin ist on the newest version. The only thing (I think to do) is to change/add the new package path to paper. https://github.com/minecraft-dev/MinecraftDev/blob/deee64b5af6fc5fa440b6198579b6961e649a7cd/src/main/kotlin/platform/bukkit/PaperModuleType.kt

How you say it's not very important to do it fast.

**Comment by Mysterious-Dev** [comment]
Seem fixed in last version
![image](https://user-images.githubusercontent.com/40738104/171417028-a05999af-2c4b-4806-9d2f-30647fd8e814.png)

**Comment by BlockyTheDev** [comment]
I haven't seen because in the last month I only worked on 1.16.5 projects, but it looks like it was fixed in this commit last year https://github.com/minecraft-dev/MinecraftDev/commit/5f80ca22d415ac80ab0856467db8c9322a7bc3cc
