### ISSUE TITLE
Access widener functionality marks transitive modifiers as errors

### ISSUE THREAD

**Issue by Juuxel** [DemonWav/MinecraftDevIntelliJ#1780]
- MCDev version: 2021.2-1.5.17
- IDEA 2021.2.2 Ultimate
- OS: Windows 10
- Target platform: Fabric since it's about AWs

Transitive access modifiers (like `transitive-accessible`) from the v2 AW format are marked as format errors. Example from Fabric Data Generation API's access widener:

![](https://user-images.githubusercontent.com/6596629/146552860-483168c8-c142-4b50-8d43-489641d65247.png)

**Comment by RedNesto** [comment]
AW v2 are not supported yet

**Comment by Juuxel** [comment]
Alright. I think the only change from v1 are these `transitive-` modifiers so it shouldn't be too hard to support in the future :smile:

**Comment by RedNesto** [comment]
Fixed in 8b4958a2016048fa05ef72beb0c76502532108e4
