### ISSUE TITLE
Incorrect import for Forge Template on 1.17+

### ISSUE THREAD

**Issue by Mysterious-Dev** [DemonWav/MinecraftDevIntelliJ#1783]
All of informations is in title

**Comment by DenWav** [comment]
Which import? What is incorrect?

**Comment by RealYusufIsmail** [comment]
Yeah I saw this too. It's a bug. It gives you imports that are used in 1.16 and since a-lot of classes have changed in 1.17 the import are wrong

**Comment by Mysterious-Dev** [comment]
Yeah. Maybe add a multiple versions template support.

**Comment by RedNesto** [comment]
There already is a different template for 1.17 https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/resources/fileTemplates/j2ee/forge/Forge%20(1.17+)%20Main%20Class.java.ft

I might have misread the mdk diff , and I test those changes so it's surprising I did not notice.

**Comment by RealYusufIsmail** [comment]
> There already is a different template for 1.17 https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/resources/fileTemplates/j2ee/forge/Forge (1.17+) Main Class.java.ft
> 
> I might have misread the mdk diff , and I test those changes so it's surprising I did not notice.
<img width="1236" alt="Screenshot 2021-12-27 at 13 49 40" src="https://user-images.githubusercontent.com/67903886/147477868-5aba6431-580e-4431-ab22-1de06dd9bae5.png">

**Comment by RedNesto** [comment]
I'm finally back home and did some quick tests.
Using MCDev `2021.3-1.5.18-307`, the generated projects for both Forge `1.17.1-37.1.1` and `1.18.1-39.0.9` compile correctly (with `gradlew build`).

You gotta provide more information about this issue.

**Comment by Mysterious-Dev** [comment]
It's the object class template (like Block, Item, Enchantment and Packet)
