### ISSUE TITLE
Error while attempting to retrieve versions.(Spigot Plugin)

### ISSUE THREAD

**Issue by Glender2** [DemonWav/MinecraftDevIntelliJ#1784]
MD: v2020.3-1.5.3
IJ: v2020.3.2 Community
Date: 2021/12/26
OS: Windows
Type: Spigot Plugin.
Issue: When create a new project in Spigot plugin, I can not choose the minecraft versions.
There was an error while attempting to retrieve versions.

**Comment by ValentinLiu15** [comment]
This problem still exists!

**Comment by EpicNose** [comment]
This problem still exists!

**Comment by GregTaoo** [comment]
i met this problem just now
