### ISSUE TITLE
Support Architectury API

### ISSUE THREAD

**Issue by KP2048** [DemonWav/MinecraftDevIntelliJ#1793]
Architectury API makes it possible to have both forge and fabric projects share common code and any forge/fabric specific things go in their respective sub projects

https://github.com/architectury/architectury-templates

**Comment by zml2008** [comment]
What support would you like to see from MinecraftDev? Doesn't architectury have their own IntelliJ plugin already?

**Comment by zml2008** [comment]
(also duplicate of #823)

**Comment by KP2048** [comment]
I kind wanted a project template but ok
Their plug-in just makes it so their @ExpectPlatform annotation can generate implementation classes.

**Comment by Earthcomputer** [comment]
It was closed because it was a duplicate, not because it was rejected.

**Comment by KP2048** [comment]
ok
