### ISSUE TITLE
Implement KSpigot

### ISSUE THREAD

**Issue by DasShorty** [DemonWav/MinecraftDevIntelliJ#1794]
Can you add KSpigot from BLUE it is a very helpful api in the plugin develop

[Github Resource](https://github.com/jakobkmar/kspigot)

**Comment by Earthcomputer** [comment]
Just add it to the pom / build.gradle yourself

**Comment by jakobkmar** [comment]
I wouldn't add anything related to that library, I have moved to Fabric / Quilt and this project does not receive enough love from me anymore for this kind of stuff.
