### ISSUE TITLE
Add mixin helper support for MixinExtras

### ISSUE THREAD

**Issue by shaksternano** [DemonWav/MinecraftDevIntelliJ#1795]
Would it be possible to add stuff like mixin target autocomplete and the go to target button for MixinExtras?
https://github.com/LlamaLad7/MixinExtras

**Comment by Earthcomputer** [comment]
I have discussed this with LlamaLad on discord, and for now I think this might be best as a separate plugin on top of mcdev which uses mcdev's mixin API, which should allow for this quite easily. MixinExtras is still quite new but if it gets popular then we may decide (with permission) to merge that separate plugin into mcdev.

**Comment by Earthcomputer** [comment]
#1882 will partly address this by trying to detect whether an annotation is a mixin injector, which will facilitate completion and navigation for injectors that don't have proper support. However there will be no unresolved errors, as we can't be sure that a custom injector doesn't have custom resolution logic. To get full support for MixinExtras, Annotation handlers need to be written for these annotations as described above.

**Comment by faluhub** [comment]
Hi, seeing as this is an issue from 2022 I don't think there'll be much activity. But I'll just ask anyway.
Is it possible to implement this? I think MixinExtras has gotten to a point where it is worth it to implement.
Stuff like `WrapOperation` and `WrapWithCondition` shouldn't be too hard to implement, as they're very similar to `Redirect` calls.
If this already exists I hope someone can send it.
Please take it into consideration. Thanks :)

**Comment by Earthcomputer** [comment]
This has been implemented for a while now
