### ISSUE TITLE
Plugin is incompatible with IntelliJ Ultimate Edition

### ISSUE THREAD

**Issue by ZephireNZ** [DemonWav/MinecraftDevIntelliJ#18]
I have the latest version of IntelliJ IDEA Ultimate edition of IntelliJ (basically just lots of fancy 1st-party plugins), yet I can't install the plugin.

I'm unable to find it in the repositories, and when I compile and try to load the built zip it says it's "incompatibly with this installation.

Looking at the repo page, it seems that this is because my build number is #143.2370 whereas the supported builds are #145.x

**Comment by gabizou** [comment]
IT does require IntelliJ 2016 at the least. It sounds like you're running IntelliJ 15 still.

**Comment by ZephireNZ** [comment]
OK I see that's what is at fault now... But it's odd that IntelliJ is telling me I'm completely up to date when I'm really not o.O
