### ISSUE TITLE
IDE Error if @Inject method cancels but is not cancellable

### ISSUE THREAD

**Issue by fin444** [DemonWav/MinecraftDevIntelliJ#1801]
When mixing into a method using `@Inject`, programmers have the ability to prematurely cancel it using `CallbackInfoReturnable#setReturnValue` and `CallbackInfo#cancel`. However, if the annotation does not have a `cancellable = true` property, then doing so will create a runtime exception.

This suggestion is to add an IDE error when an `@Inject` method contains one of these cancellations, but does not have `cancellable = true`. This will make it quicker and easier for mixin developers to catch these issues.

**Comment by RedNesto** [comment]
This is actually a bug. `CallbackInfoReturnable` was no longer recognised after the inspection refactoring.
