### ISSUE TITLE
Minecraft Version Selector Error

### ISSUE THREAD

**Issue by Lazycork** [DemonWav/MinecraftDevIntelliJ#1811]
I am unable to select Minecraft versions. Some error is coming

**Comment by Mysterious-Dev** [comment]
Can you give more details?

**Comment by Lazycork** [comment]
[](url
![Screenshot (4)](https://user-images.githubusercontent.com/87581390/154858818-4e485b51-e0e1-4c96-9875-483c163cd87f.png)
)

**Comment by Lazycork** [comment]
[](url
![Screenshot (3)](https://user-images.githubusercontent.com/87581390/154858842-8c309c54-da16-4c7b-beee-f206670d1cce.png)
)

**Comment by iInvisibilities** [comment]
You should be using internet to be able to do that. i think that this plugin uses internet to get the mc servers? it happened to me & fixed by enabling internet lmfao

**Comment by Mysterious-Dev** [comment]
Yes. If internet is disable, the plugin cannot get versions ^^. This issue can be close.
