### ISSUE TITLE
@At("NEW") target parsing is incorrect

### ISSUE THREAD

**Issue by js6pak** [DemonWav/MinecraftDevIntelliJ#1818]
* Minecraft Development for IntelliJ plugin version: 1.5.18
* IntelliJ version: 2021.3.2
* Target platform, if relevant: Mixin

To target a constructor like this
![image](https://user-images.githubusercontent.com/35262707/158629508-c668bf98-af40-4def-82b2-9480e8da3bc4.png)
[Mixin format](https://jenkins.liteloader.com/job/Mixin/javadoc/org/spongepowered/asm/mixin/injection/points/BeforeNew.html) requires you to use `([Lnet/minecraft/client/model/Vertex;IIII)Lnet/minecraft/client/model/Quad;` as the target, yet mcdev fails to parse that and instead recommends `Lnet/minecraft/client/model/Quad;<init>([Lnet/minecraft/client/model/Vertex;IIII)V` (which fails)

This is probably a regression introduced by #1525

**Comment by TechPizzaDev** [comment]
Just stumbled upon this bug (on nightly plugin version `2023.1-1.6.4-386`). 
Using the expected Mixin format for `NEW` in either `At.target` or `At.args="class=..."` is not recognized.

**Comment by RedNesto** [comment]
I have attempted a fix in the next nightly build but I'm not sure if this is completely correct.
Please let me know if this fixes your use cases or if it breaks other stuff.

**Comment by TechPizzaDev** [comment]
`At.target` now works as expected. 
`At.args="class=..."` seems to still be broken as before, but judging by fba57df81658e5afcf439108c4ae75d6ba4d527f, that commit didn't seem to have code to handle `At.args="class=..."` so no surprise in it being unchanged.

**Comment by RedNesto** [comment]
The class arg is already handled by the plugin, but I noticed it didn't match the class name properly (https://github.com/minecraft-dev/MinecraftDev/commit/fba57df81658e5afcf439108c4ae75d6ba4d527f#diff-1d5bd2909dc857dcf3081316e1f524ce3ebb63b7451a2c262be57c8efcd57552R67). After changing that it was fine in my simple test case.

I'll look into it later.
