### ISSUE TITLE
Bug: Unable to handle dollar signs in mixin class names within <modname>.mixins.json

### ISSUE THREAD

**Issue by Jack-Papel** [DemonWav/MinecraftDevIntelliJ#1821]
### The Problem:
When the name of a mixin class has a dollar sign in it, it is displayed as nonexistent in modname.mixins.json, even though mixin has no trouble processing it.

### System specifications:
Minecraft Development for Intellij 2021.2-1.5.18
Intellij IDEA 2021.2.1 (Community Edition)
Windows 10 Home 21H1 19043.1586

### Additional Information:
This issue has also been noted by my co-developers, who use Arch Linux.
For [the project in question](https://github.com/devs-immortal/Paradise-Lost), I am developing with / the issue is likely related to Mixin and Fabric.

The following image is a screenshot of the name of [the class in question](https://github.com/devs-immortal/Paradise-Lost/blob/b1.7/src/main/java/net/id/aether/mixin/entity/SlimeEntity%24RandomLookGoalMixin.java): 
![image](https://user-images.githubusercontent.com/64770632/160218581-5d6e4975-2a28-4c25-ab53-da438ff311ed.png)

The following image is a screenshot of [the_aether.mixins.json](https://github.com/devs-immortal/Paradise-Lost/blob/b1.7/src/main/resources/the_aether.mixins.json):
![image](https://user-images.githubusercontent.com/64770632/160218321-055a8822-3370-4c8a-8810-3ca9b83eb45d.png)

The following image is the message displayed when hovering over the string in the_aether.mixins.json:
![image](https://user-images.githubusercontent.com/64770632/160218852-0df94907-bec2-44b7-ae5a-ab5a4d18dc62.png)

The class is in the correct directory, so it's likely just a parsing issue.

**Comment by RedNesto** [comment]
Fixed in 19ffce4a2f8a0caddfab0460f8955027b4f3f2d2
