### ISSUE TITLE
You can't open a project with the new EAP Intelij.

### ISSUE THREAD

**Issue by Godwhitelight** [DemonWav/MinecraftDevIntelliJ#1822]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version: 2022.1-1.5
* IntelliJ version: EAP 2022.1 BETA
* Operating System (this has come up enough times to be worth noting): Win11

I can't see the Minecraft category on Create Project 
![image](https://user-images.githubusercontent.com/73111474/160616726-71e89506-181c-41e2-b06a-b1bfbe935dfb.png)

**Comment by Earthcomputer** [comment]
https://github.com/minecraft-dev/MinecraftDev/commit/ba390c9e08b897f143e2f769aeb41334323cfe54

**Comment by L1oN1337** [comment]
Issue seems to be a problem again/still.
I'm on plugin version 2022.1-1.5.18, Intellij version 2022.1 and Win11

**Comment by Earthcomputer** [comment]
You need to update to mcdev nightly

**Comment by L1oN1337** [comment]
Thanks mate ^^
