### ISSUE TITLE
IntelliJ EAP (and normal ultimate) does not show any possibility to create a Minecraft Based project

### ISSUE THREAD

**Issue by CarinaSchoppe** [DemonWav/MinecraftDevIntelliJ#1823]
IntelliJ EAP (and normal ultimate) does not show any possibility to create a Minecraft Based project

**Comment by CarinaSchoppe** [comment]
Also the createEvent tab in "generate" is not visible or even existing

**Comment by Earthcomputer** [comment]
Duplicate of #1822
