### ISSUE TITLE
Not see New Minecraft class in fabric 

### ISSUE THREAD

**Issue by CodeCraftPlugin** [DemonWav/MinecraftDevIntelliJ#1828]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* 2022.1-1.5.19
* 2022.1
* Windows 11(os build = 22000.613)
* Fabric
  * E.g., Bukkit, Forge, Mixin, etc
please look at the image for detailed information
this is no button for instant creation of Minecraft class in fabric if you guys have removed please bring it back and if it is a bug please fix it
or if there is a problem at my end try to help me on how to fix it 
![image](https://user-images.githubusercontent.com/86466022/166152599-fdffe468-a162-444f-9327-d8f465f184bb.png)

**Comment by Mysterious-Dev** [comment]
Confirmed. This bug affect all the fabric projects in 2022.1 & 2021.2.
