### ISSUE TITLE
Cannot choose version options for Fabric

### ISSUE THREAD

**Issue by ebay-kid** [DemonWav/MinecraftDevIntelliJ#1829]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version - 2022.1-1.5.19
* IntelliJ version - 2022.1
* Operating System (this has come up enough times to be worth noting) - Windows 10 Home 21H2
* (optional) Target platform, if relevant - Fabric
  * E.g., Bukkit, Forge, Mixin, etc

Always include a stack trace if there is one. Otherwise, the more information you can provide in terms of how to reproduce the problem, the more likely it'll be fixed. If there is something specific about your project, a link to the GitHub project can be very helpful.

I am trying to create a new Fabric project, however, upon trying to choose the MC version, Yarn version, Loader version, Loom version, or Fabric API version, there are no options in the dropdown. Below are two screenshots showing the issue. However, the Environment and License dropdowns work properly. However, I tested this on a different project type (Paper), and the version dropdown (the only dropdown there) works as expected.

Fabric (broken):
![image](https://user-images.githubusercontent.com/72238524/166170519-822b1f4c-ea2d-487f-8af1-5e65e935e92c.png)
![image](https://user-images.githubusercontent.com/72238524/166170528-bee564f1-a6d4-4fc7-b38c-f51788525e91.png)

Environment (fine):
![image](https://user-images.githubusercontent.com/72238524/166170603-4348988f-2b09-45d1-9027-22cd2464ff2c.png)

Paper (fine):
![image](https://user-images.githubusercontent.com/72238524/166170651-e042ab9e-8d6d-4997-85e6-aee363ff12eb.png)

**Comment by Lemmmy** [comment]
I ran into this bug a few days ago too, but it seems to work now. Perhaps the versions are fetched from an API and it was temporarily down?

**Comment by chriss59** [comment]
I have the same problem today with the plugin.
- IntelliJ version - 2022.1.1
- Minecraft Development for IntelliJ plugin version - 2022.1-1.5.19

**Comment by jurekth** [comment]
I also have the same problem today as chriss59 with the same IntelliJ and plugin version.

**Comment by RattMeister** [comment]
This issue is still occurring on multiple systems.

**Comment by Earthcomputer** [comment]
@modmuss50 can you confirm if this is due to the Fabric web API?

**Comment by BurnutsGaming** [comment]
It even affects Architectury.
https://github.com/minecraft-dev/MinecraftDev/issues/1834

**Comment by K4l3th** [comment]
I just searched through the code to find the API's responsible.
Sorry if this is complete nonsense (I am fairly new to  this) but to me it seems like the API for the "Fabric API Version" does not respond.
https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/kotlin/platform/fabric/creator/FabricProjectSettingsWizard.kt#L284-L299

DataProvider:
https://github.com/ExtraCrafTX/TemplateMakerFabric/blob/master/src/main/java/com/extracraftx/minecraft/templatemakerfabric/data/DataProvider.java#L118-L133

I tried every other API and got a response except for Fabric API Version (https://addons-ecs.forgesvc.net/api/v2/addon/306612/files)

**Comment by modmuss50** [comment]
> @modmuss50 can you confirm if this is due to the Fabric web API?

This is not an issue with anything on Fabric's end. You guys are using an internal curseforge API that was shutdown.

**Comment by Mysterious-Dev** [comment]
It's maybe the moment to use own class and not a librairy for this

**Comment by triphora** [comment]
For Fabric API, the Modrinth API can be used: [documentation](https://docs.modrinth.com/api-spec/#operation/getProjectVersions) and [example](https://api.modrinth.com/v2/project/fabric-api/version?game_versions=[%221.18.2%22]).
For Architectury API, the [Architectury Maven](https://maven.architectury.dev/dev/architectury/architectury/) can be used alongside this [architectury.json](https://gist.github.com/shedaniel/4a37f350a6e49545347cb798dbfa72b3/) file.

**Comment by Earthcomputer** [comment]
Oh, good to know there's a way to do it with the modrinth API now, it's always good to have a supported API :+1:

**Comment by CommandCracker8** [comment]
How can I fix this / still use the plugin?

**Comment by brandonplank** [comment]
As of right now, you don't, Or you can implement those API's yourself.

**Comment by SzczurekYT** [comment]
Also facing this issue.
