### ISSUE TITLE
Support for Minecraft Paper 1.18.2

### ISSUE THREAD

**Issue by Leguan16** [DemonWav/MinecraftDevIntelliJ#1832]
I noticed that there is no drop down option for minecraft 1.18.2 if you want to create a new paper plugin. 

I tried to fix it by myself but i could not find the location where the versions are defined.

**Comment by RedNesto** [comment]
Paper 1.18.2 is now available in the project creator.

**Comment by Leguan16** [comment]
Nice thanks!
