### ISSUE TITLE
Add support for jareds multiloader template

### ISSUE THREAD

**Issue by Minecraftschurli** [DemonWav/MinecraftDevIntelliJ#1833]
I love this plugin, but I recently started working in multiloader projects and discovered that the plugin does not support creating such projects. It works on existing multiloader projects but one can't create them with it.

**Comment by DenWav** [comment]
No, we used to support multiple loader projects and specifically removed it as the project templates were too getting too complicated to maintain. In general anything outside of a standard project is out of scope.
