### ISSUE TITLE
There is no version options in Architectury Mods

### ISSUE THREAD

**Issue by BurnutsGaming** [DemonWav/MinecraftDevIntelliJ#1834]
## About

When I tried to create a Architectury Mod in IntelliJ IDEA, There are no versions displaying even after restart preventing me from continuing to create the project.

## Info

**Minecraft Development for IntelliJ plugin version: 2021.3-1.5.19**

**IntelliJ version: 2021.3.3 (IC-213.7172.25)**

**Operating System: Windows 10 (19044.1706)**

**Target platform: Architectury**

## Screenshots

![Screenshot 2022-05-17 101725](https://user-images.githubusercontent.com/50048533/168714890-71e3a48b-5e05-4f7c-ad55-6d4c83208198.png)

![Screenshot 2022-05-17 102211](https://user-images.githubusercontent.com/50048533/168715385-091059e6-8eea-467f-b4af-48f5eba9b502.png)

**Comment by Charismara** [comment]
I got the same problem :(

**Comment by chmodsayshello** [comment]
I also have this problem, but with fabric mods, anyways I can confirm that it also applies to Architectury

**Comment by orange2222222222** [comment]
me too :

**Comment by Jab125** [comment]
have the same problem, can also confirm this issue doesn't affect forge

**Comment by googleooer** [comment]
any updates on this? it makes the plugin unusable

**Comment by DaemonUmbra** [comment]
Wait until #1838 is merged, then try the subsequent nightly
