### ISSUE TITLE
Add support for a single author to be listed in the plugin.yml

### ISSUE THREAD

**Issue by ShreyasAyyengar** [DemonWav/MinecraftDevIntelliJ#1835]
This is a very simple QOL feature that I would definitely find useful, usually as I am the only one writing my plugins. 

When creating a new project, and filling out the plugin.yml contents (eg. Main Class, Name, Dependencies) there is also a textbox for authors: 

If I wanted to put my name: `Shreyas Ayyengar`, the IntelliJ plugin would not let me proceed, stating that in order to list more than one author a comma (,) should split the names.  This means that those who want to list their name (with a space) as the only author, would not be able to do so.

Quite simple ¯\_(ツ)_/¯

**Comment by syorito-hatsuki** [comment]
![image](https://user-images.githubusercontent.com/33298273/178137171-656ce35b-4a3f-46fb-a01e-eb1893e17fde.png)
Yep. Same trouble up to year

**Comment by ShreyasAyyengar** [comment]
Any potential implementations? A short-term solution was provided in #1868 but was closed.
