### ISSUE TITLE
Version Selector

### ISSUE THREAD

**Issue by CorruptionHades** [DemonWav/MinecraftDevIntelliJ#1837]
Hello!
Im using your plugin in Intlij and i want to make a mod, but when i want to create it, the versions dont show up
Kind regards,
CorruptionHades
![Welcome to IntelliJ IDEA 23 05 2022 17_43_14](https://user-images.githubusercontent.com/96599430/169857276-1604f258-8894-4d6e-821f-c50c87cbfe7c.png)

**Comment by Earthcomputer** [comment]
Duplicate of #1829
