### ISSUE TITLE
Fabric Project initialization is missing all versions

### ISSUE THREAD

**Issue by LizAinslie** [DemonWav/MinecraftDevIntelliJ#1840]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Dev version: 2021.3-1.5.19
* IntelliJ version: 2021.3.3 IU-213.7172.25
* OS: Windows (Where I took the screenshot) or Linux.
* (optional) Target platform, if relevant
  * E.g., Bukkit, Forge, Mixin, etc

There is no stack trace, have an image:
![](https://i-work-at-the.cocaine.institute/Lizzy628ecea4bOgctLUBotRs.png)

**Comment by ox-ox-ox** [comment]
This is fixed in the latest nightly version.

**Comment by LizAinslie** [comment]
When can I expect a stable release?

**Comment by LizAinslie** [comment]
I would not consider this closed. I'd appreciate an estimate of when I can expect a stable (non nightly) release as I cannot use nightly builds for work. Thanks.
