### ISSUE TITLE
Can't choose any fabric version

### ISSUE THREAD

**Issue by znel2002** [DemonWav/MinecraftDevIntelliJ#1841]
![Bild_2022-05-29_220957599](https://user-images.githubusercontent.com/99537307/170889537-cccb19b6-3d5f-45b5-8680-17461a302147.png)
Hey,
i have a problem with this plugin. I can't select any version for fabric. (screenshot) Every other works fine
Thanks for your help. Just ping me
Java : 18
IntelliJ: 2022.1.1
No error code or smth. like that

**Comment by RedNesto** [comment]
This is already fixed in the nightly channel.

**Comment by znel2002** [comment]
Sry for not knowing. 
What or who is the nighlty channel?

**Comment by RedNesto** [comment]
The nightly channel is where you can find the very latest version of the plugin, with changes that are not yet released in a stable version.

If you want to switch to the nightly channel follow the instructions in `Setting up nightly builds` https://mcdev.io/install/

**Comment by znel2002** [comment]
Thx dude.
You are such a nice guy ♥
