### ISSUE TITLE
1.19 Support for Forge

### ISSUE THREAD

**Issue by MrScautHD** [DemonWav/MinecraftDevIntelliJ#1851]
1.19 Support for Forge

**Comment by Mysterious-Dev** [comment]
What do you think is not supported?

**Comment by MrScautHD** [comment]
> What do you think is not supported?

i tried it and i get errors, so yes it is not supported

**Comment by RedNesto** [comment]
The forge 1.19 templates are not updated yet because I am waiting for https://github.com/MinecraftForge/MinecraftForge/pull/8675 to be merged before updating these templates accordingly.

**Comment by Mysterious-Dev** [comment]
It's merged

**Comment by MrScautHD** [comment]
when does it release?
