### ISSUE TITLE
Minecraft Vresion,Yarn Version,Loader Version,Loom Version are empty.

### ISSUE THREAD

**Issue by littleFlyBoy** [DemonWav/MinecraftDevIntelliJ#1863]
![image](https://user-images.githubusercontent.com/76845387/175811480-f1d93b43-7556-47a1-a1aa-333ca96741f1.png)
fabric construction

**Comment by Mysterious-Dev** [comment]
It's fixed in the last version of plugin. Please update

**Comment by littleFlyBoy** [comment]
Ok, thank you it works.
