### ISSUE TITLE
Bring back multi selection of modloaders in New Project

### ISSUE THREAD

**Issue by DelofJ** [DemonWav/MinecraftDevIntelliJ#1864]
In the 1.5.19 version of the plugin, the ability to select to develop a mod with multiple modloader was removed
Before, you could select to make this mod working with Forge and Fabric at the same time for example
But with the version 1.5.19 and 1.5.20 of the plugin, you can select to work only with on modloader at a time
Why this was done ? It was great to make a mod compatible with multiple mod loaders in the same project
![before](https://user-images.githubusercontent.com/50058956/176321048-42c7bca2-ebbe-411b-81db-2e737a793d76.png)
![after](https://user-images.githubusercontent.com/50058956/176321056-83a08b45-d866-4ef8-a2fa-32ceebc0f486.png)

**Comment by Earthcomputer** [comment]
It was done because it was a maintenance burden to maintain. You can still make a mod compatible with Forge and Fabric, just not with a template like this anymore. Mcdev can still handle multi-platform projects, only the creators have been affected.
