### ISSUE TITLE
Spigot LivingEntity#setInvisible

### ISSUE THREAD

**Issue by JPKairos** [DemonWav/MinecraftDevIntelliJ#1866]
I'm using your Plugin Minecraft Development for IntelliJ. I recently tried to code some Spigot plugin. while using the ArmorStand#[setInvisible](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/LivingEntity.html#setInvisible(boolean)) method, the IDE told me, that it "Cannot resolve method 'setInvisible' in 'ArmorStand'", while it exists in the API https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/LivingEntity.html#setInvisible(boolean) .

**Comment by JPKairos** [comment]
Okay, found the error: in your plugin the method is called setVisible while in the API it is called setInvisible.

**Comment by JPKairos** [comment]
similar problem with pigs. But here it's neither visibility nor invisibility.
You should really have a look on those invisibility thing

**Comment by Earthcomputer** [comment]
Minecraft Dev has nothing to do with this issue. You probably attached the wrong library or something.
