### ISSUE TITLE
Support for mixin extras

### ISSUE THREAD

**Issue by MattiDragon** [DemonWav/MinecraftDevIntelliJ#1881]
[Mixin Extras](https://github.com/LlamaLad7/MixinExtras) is a mixin addon that adds a bunch of new injectors. It's really handy, but it's a shame that mcdev doesn't support it as writing mixins is painful without the autocompletions.

I'd like to see at least basic mixin support for verifying `method`, `at` and `slice`, preferably also custom checks for it's more advanced features.

**Comment by Earthcomputer** [comment]
Duplicate of #1795
