### ISSUE TITLE
Make "Translation key not included in default localization file." inspection toggleable.

### ISSUE THREAD

**Issue by Cypher121** [DemonWav/MinecraftDevIntelliJ#1885]
There does not appear to be a way to disable this inspection.

I have my processResources task set up to flatten keys (`{"namespace": {"key": "value"} }`) for lang files, which predictably breaks the inspection. I marked my files as JSON5 in IJ, but I'd like to be able to turn that inspection off to begin with, as it doesn't apply to my dev environment.

**Comment by l-Luna** [comment]
+1 - Lib39 provides a similar feature now, and the plugin paints the whole file yellow 
It also has false positives (on everything) when editing the file (and it's temporarily invalid), and should probbaly only apply to non-default files to begin with.

**Comment by ILikeFood971** [comment]
If you use yamlang for language files it also (understandably) has issues. I'd be great with just being able to turn off the inspection.

https://github.com/Fallen-Breath/yamlang

**Comment by Earthcomputer** [comment]
All inspections are toggleable. This one is called "missing translations" in the "Minecraft" category.
