### ISSUE TITLE
[FG2.3] No Mapping Data Available

### ISSUE THREAD

**Issue by ByThePowerOfScience** [DemonWav/MinecraftDevIntelliJ#1887]
* Minecraft Development for IntelliJ plugin version: 2021.2-1.5.20
* IntelliJ version: 2021.2.4 (Ultimate Edition)
* Operating System: OSX Monterey 12.5.1
* Target platform: Forge 1.12.2 with ForgeGradle 2.3-SNAPSHOT

Look, look, I know this is related to an older version, but please bear with me.

I'm maintaining a few older projects, and code analysis is broken due to the following error in the logs:
> 2022-08-21 15:13:18,418 [1555417]  ERROR - n.impl.GeneralHighlightingPass - Exception 'org.jetbrains.concurrency.MessageError: No mapping data available at /[PROJECT]/build/createMcpToSrg/output.tsrg' was reported 40 times

The reason for this is because I'm forced to use ForgeGradle 2.3-SNAPSHOT due to several compatibility errors in the newer versions, and 2.3 stores the SRG mapping file in a different file location.  This causes code analysis to be broken globally, even in files that don't use remapped functions.

This should in theory be a really simple fix by just adding an option to configure the SRG mapping path, so I'm going to submit a PR for it as soon as I can figure out where it's handled, but I wanted to file the issue here first.

**Comment by mightydanp** [comment]
I am also having the same problem

**Comment by mightydanp** [comment]
![image](https://user-images.githubusercontent.com/4637469/187051507-67dc828f-d613-4cc9-b68c-4ec3bea5d127.png)

**Comment by DenWav** [comment]
Does it fix itself after refreshing Gradle?

**Comment by mightydanp** [comment]
That was one of the sugesstions that i tried

**Comment by Bread-NiceCat** [comment]
I am also having the same issue，I can only get AW entry but AT says `no mapping found`
