### ISSUE TITLE
Spigot, bukkit and paper do not have the option of version 1.15.2 or above

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#1889]
Minecraft Development for IntelliJ plugin version:2022.2-1.5.20-336
IntelliJ version:2022.2
Operating System:Windows 10 pro 21H2
Spigot, bukkit and paper do not have the option of version 1.15.2 or above
![image](https://user-images.githubusercontent.com/70805743/187681359-1b86bd77-7cb1-4af9-a5b9-163e33dcc5ae.png)
![image](https://user-images.githubusercontent.com/70805743/187681416-f034dd11-6d5a-4836-8268-66172a8e7289.png)
![image](https://user-images.githubusercontent.com/70805743/187681455-3613ef04-e9a7-4b59-a7db-6a59f68d29f7.png)

**Comment by ghost** [comment]
Many times after reshipment again, the problem has been solved

**Comment by Stausssi** [comment]
What do you mean with reshipment? I have the same issue and can't get it to work on both stable and nightly builds of this plugin.

I'm currently running 2022.2-1.5.20-339 on IntelliJ 2022.2.2 on Windows 11 pro 22H2

**Comment by Stausssi** [comment]
I fixed it by creating a temporary project in version 1.15.2 and then editing the `pom.xml` file with the following changes:

```xml
<dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
</dependencies>
```

After that, I ran Maven and it downloaded the latest jar. Now I can create a spigot (and paper) plugin in 1.19.2.
