### ISSUE TITLE
Please update Architectury API

### ISSUE THREAD

**Issue by Vyacguru** [DemonWav/MinecraftDevIntelliJ#1892]
Information:

* Minecraft Development for IntelliJ plugin version
= 2022.2-1.5.20
* IntelliJ version
= 2022.2.1
* Operating System
= Windows 10 21H2
* Target platform
= Architectury API 1.19.2

Issue:

Minecraft 1.19.1-2 requires Architectury API versions Forge 6.2.33 and Fabric 6.2.43. But MinecraftDev does not have these versions. Accordingly, it is impossible to launch the project

**Comment by DaemonUmbra** [comment]
~~Not Us: Architectury's Official json is missing the mentioned versions~~
To Do: Arch team recommends using Modrinth as a version directory instead
