### ISSUE TITLE
Plugin doesn't recognize valid NBT file

### ISSUE THREAD

**Issue by izofar** [DemonWav/MinecraftDevIntelliJ#1894]
Reproduce: Open [inside_cage_broken.nbt](https://github.com/izofar/takes-a-pillage/blob/04eec5277b0bbcfd086723ba7c2f908774a9b89b/src/main/resources/data/takesapillage/structures/bastille/corner/inside_cage_broken.nbt) with Minecraft Development plugin version `2021.3-1.5.20-348` on Intellij IDEA version `2021.3.3`. 

Notice that keys are not colored as usual. 

Make an edit and try to save. Get error: "*Error Saving NBT File*: This file is not recognized as a NBTT file. This might be caused by wrong file type associations". 

I've confirmed that `Named Binary Tag` maps to `*.nbt` and `NBT Text Representation` maps to `*.nbtt` in `Editor > File Types`. 

I was able to open it with [Minecraft NBT Support v1.5.2](https://github.com/tth05/minecraft-nbt-intellij-plugin), though I prefer being able to do find-and-replace

**Comment by DenWav** [comment]
Not sure exactly what the issue is, I thought it was because the text file was too big but I'm getting the same issue increasing the max file size.

I think I can fix this, just not sure yet.

**Comment by DenWav** [comment]
I believe abf32c6ee060522323f0427c8ddb24e739d2402a fixes the issue you are having. If you could switch to the nightly channel and give it a try and let me know how it works for you that'd be great.

One change I made is saving/writing the file no longer happens automatically, it can only be triggered by clicking the "Save" button or using the `Save All` action (Ctrl-S / Cmd-S).

**Comment by izofar** [comment]
This seemed to fix it. Thank you
