### ISSUE TITLE
Arch Loom mixin issues

### ISSUE THREAD

**Issue by rlnt** [DemonWav/MinecraftDevIntelliJ#1895]
* Minecraft Development version: 2022.2-1.5.20
* IntelliJ version: 2022.2 Build 222.3345.118
* Operating System: Windows 11 Pro
* Target platform: Arch Loom 0.12-SNAPSHOT + Mixin 0.8.5

When using Arch Loom in a Forge setup (it's a Forge port of Fabric Loom), the mixin integration of the plugin does not work correctly. 

When mixin a class and injecting into a method, the method datatypes autocomplete just fine. Things that don't work are the parameter autocompletion for the target method, the mixin class does not have a quick fix for adding it to the mixin configuration and the mixin configuration has no validation so when adding an invalid mixin class name, it doesn't show an error.

The icons on the left side work fine as well and also navigate you to the right target, just the auto-completion and quick fixes seem to be broken.

Here is a preview of how it looks in Arch Loom compared to Fabric Loom or Forge Gradle.
![unknown](https://user-images.githubusercontent.com/16513358/191321434-4b5a5ca2-8507-4a34-815b-c70f077f901a.png)

**Comment by embeddedt** [comment]
I have the same issue. Is there anything that can be done to help debug/fix this?
