### ISSUE TITLE
Support for Gradle kts

### ISSUE THREAD

**Issue by raphael950** [DemonWav/MinecraftDevIntelliJ#1898]
Hello, I saw that we can create plugins using Gradle and Maven, could you also add support for Grdle kts pls?

**Comment by AlmanaX-21** [comment]
Are there plans on working towards this?

**Comment by OakLoaf** [comment]
Yeahh I'd also like gradle kts support

**Comment by GhostGonz21st** [comment]
woul like this as well. It would make things alot faster than starting from scratch.

**Comment by Tennessene** [comment]
I agree with this too, but this is a duplicate of #687
