### ISSUE TITLE
Installation error - Needs Update

### ISSUE THREAD

**Issue by Apthos** [DemonWav/MinecraftDevIntelliJ#19]
Could you please update it to be compatible with newer versions... plz.

**Comment by DemonWav** [comment]
Can you be more specific? It should work with any 2016.1.* version.

**Comment by kashike** [comment]
With newer versions of... what?

**Comment by Apthos** [comment]
http://prntscr.com/biijle

**Comment by DemonWav** [comment]
What version of IntelliJ do you have? Again, it only works for 2016.1 and up.

**Comment by Apthos** [comment]
pretty sure, I'm on the latest version : http://prntscr.com/biikye

**Comment by DemonWav** [comment]
No, you're on version 15.0.6. 2016.1 is the next major release after 15.
