### ISSUE TITLE
NPE: cannot be cast to non-null type `PsiAnnotation`

### ISSUE THREAD

**Issue by rlnt** [DemonWav/MinecraftDevIntelliJ#1901]
Versions:
- Plugin: 2022.2-1.5.21
- IntelliJ: 2022.2.2 222.4167.29
- Java: Zulu 17.0.3
- OS: Windows 11 Pro 21H2 22000.832
- Target Platform: Forge

Relevant code and logs:
- [code file that triggers the error](https://pastebin.com/T3h00Qah)
- [first stack](https://pastebin.com/fhPtiCvz)
- [second stack](https://pastebin.com/D78Rw1Dg)

**Comment by DenWav** [comment]
Fixed in eaa8c26d70c26c7aac850866b0ce97c3f7557710.
