### ISSUE TITLE
Plugin 'com.demonwav.minecraft-dev' failed to initialize and will be disabled. Help please!

### ISSUE THREAD

**Issue by SpaceNiklas** [DemonWav/MinecraftDevIntelliJ#1906]
just wanted to ask why i'm getting this error: https://pastebin.com/vp16EWTp (im on a apple silicon (m2) mac using macos ventura and have zulu jkd 18 and 8 installed)

**Comment by DaemonUmbra** [comment]
Known conflict with MineAcademy Development due to the author copying code and not relocating or renaming one or more classes.
It's why #1907 is happening.
