### ISSUE TITLE
uh its not working i might be dumb as fuck

### ISSUE THREAD

**Issue by AquaNot** [DemonWav/MinecraftDevIntelliJ#1914]
### Minecraft Development for IntelliJ plugin version

2022.1-1.5.21-358

### IntelliJ version

2022.3

### Operating System

Windows 10

### Target platform

Minecraft Forge, Fabric

**Comment by Earthcomputer** [comment]
What is not working? What do you mean by "not working"?

**Comment by AquaNot** [comment]
> What is not working? What do you mean by "not working"?

ok earth computer the pluGin is not working i will send a picture
![image](https://user-images.githubusercontent.com/82337681/209399057-0676ad6d-9b63-46b6-a888-cc9a655ea782.png)
![image](https://user-images.githubusercontent.com/82337681/209399061-f650db96-2b59-49ad-9b99-79b4363f66df.png)
ye das fucked up OR im so dumb
![image](https://user-images.githubusercontent.com/82337681/209399088-99793ec0-5758-4e93-a857-2caae0a8a350.png)

**Comment by Earthcomputer** [comment]
Ah you're the guy from discord. Yeah, see our comments there.
