### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by cootshk** [DemonWav/MinecraftDevIntelliJ#1915]
### Minecraft Development for IntelliJ plugin version

2022.3-1.5.21

### Description of the feature request

add support for compiling for 1.19.3

**Comment by Mysterious-Dev** [comment]
It's done for nightly builds.

**Comment by cootshk** [comment]
I mean spigot/paper/bukkit

**Comment by Mysterious-Dev** [comment]
1.19.3 is available for spigot and paper with https://github.com/minecraft-dev/mcdev.io/commit/9ec0f0ae287528c582926772d02fc198a6c1fc64. BTW, I'm not a plugin developer, so I don't know what could have changed. If you can give us more feedback on what's wrong, that would be great ^^.
