### ISSUE TITLE
Automatically add shadow plugin when making a Gradle plugin

### ISSUE THREAD

**Issue by CerialPvP** [DemonWav/MinecraftDevIntelliJ#1922]
### Minecraft Development for IntelliJ plugin version

2022.1-1.5.21

### Description of the feature request

Whenever you make a Bukkit, Spigot or Paper plugin, add the shadow plugin automatically to the `build.gradle` file. This would be your `plugins` section in the `build.gradle` with the shadow plugin:
```gradle
plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'java'
}
```

The shadow plugin then allows users to make the plugin into a singular jar with all dependencies by doing `.\gradlew.bat shadowJar` (or `gradlew shadowJar` on Linux systems).

**Comment by RedNesto** [comment]
I don't see why we'd need to add the shadow plugin in the default templates when it is useless as-is. The default jar should already contain the plugin's compiled classes and that's all that's needed in the default "scenario" the templates are made for.

**Comment by Mysterious-Dev** [comment]
In my opinion, it would be better to wait until the end of the project wizard rewrite before talking about it, or even implementing it.

**Comment by DenWav** [comment]
I think at some point the templates did include it, but it doesn't seem like the template's place to configure that for you.

The plugin is intended to make it quick and easy to get started, it's not intended to configure everything for you.
