### ISSUE TITLE
Add support 223.*

### ISSUE THREAD

**Issue by deestt** [DemonWav/MinecraftDevIntelliJ#1931]
### Minecraft Development for IntelliJ plugin version

2022.3-1.5.21

### IntelliJ version

223.*

### Operating System

Windows

**Comment by Mysterious-Dev** [comment]
https://github.com/minecraft-dev/MinecraftDev/commit/a0e4482c23bb9be3b963d5cdf3b8a4acf38e5ef5

**Comment by deestt** [comment]
thanks
