### ISSUE TITLE
i cant see minecraft versions

### ISSUE THREAD

**Issue by bckd00r** [DemonWav/MinecraftDevIntelliJ#1938]
### Minecraft Development for IntelliJ plugin version

2022.3-1.5.22

### IntelliJ version

2022.3.1

### Operating System

windows 10 pro

### Target platform

Paper

### Description of the bug

When I want to create a project in bukkit, spigot, paper or even all of them, I can't choose which minecraft version I should create, the error tells me "There was an error while attempting to retrieve version."

![image](https://user-images.githubusercontent.com/48347237/218197265-ebb4e72a-4e48-4a9b-bd15-8c5b83da2a26.png)

![image](https://user-images.githubusercontent.com/48347237/218197280-6624bc30-d288-4cf0-8627-104667c892d5.png)

**Comment by themg95** [comment]
I had the same issue, check if the paper API is blocked on your network and if it is, you can use a VPN to bypass it.
