### ISSUE TITLE
No genIntellijRuns when using maven

### ISSUE THREAD

**Issue by WaromiV** [DemonWav/MinecraftDevIntelliJ#1943]
### Minecraft Development for IntelliJ plugin version

1.5.20

### IntelliJ version

2022.2.1

### Operating System

macos

### Target platform

Spigot

### Description of the bug

<img width="449" alt="image" src="https://user-images.githubusercontent.com/59875489/221344760-10f3da42-0c7e-42cf-8280-50e0c7735160.png">
i want to be able to debug my code

**Comment by Earthcomputer** [comment]
genIntellijRuns is a ForgeGradle task, not for Spigot.
