### ISSUE TITLE
The code cannot be run

### ISSUE THREAD

**Issue by xooygf** [DemonWav/MinecraftDevIntelliJ#1951]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

IU-223.8617.56

### Operating System

Windows 10

### Target platform

Spigot

### Additional description

The code cannot be run, and the .jar file cannot be generated

**Comment by itinstructor** [comment]
Same. After the last IDE and Plugin update, Maven is not configured, the project is not runnable.

**Comment by 1mvghost** [comment]
Same, I need to copy run configuration from my project made with older version of this plugin.

**Comment by 1mvghost** [comment]
Same, I need to copy run configuration from my projects made with older version of this plugin.

**Comment by RedNesto** [comment]
Fixed in the next nightly

**Comment by itinstructor** [comment]
Yes, thank you! Maven is back!!!!
