### ISSUE TITLE
Mcdev doesn't support split environment source sets on fabric

### ISSUE THREAD

**Issue by MattiDragon** [DemonWav/MinecraftDevIntelliJ#1953]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1-368

### IntelliJ version

2022.3.2 (Community Edition)

### Operating System

Windows 11 Home

### Target platform

Fabric

### Description of the bug

Mcdev breaks in a lot of places when split client and common source sets are used. For example it fails to find entrypoints located in the client source set when the fabric.mod.json is in the common one. There might also be other issues

**Comment by caoimhebyrne** [comment]
This can be seen with the [example mod from the fabric mod generator](https://fabricmc.net/develop/template/), when "Split client and common sources" is enabled.

**Comment by MattiDragon** [comment]
This seems to have stopped working. I'm using mcdev 2023.2-1.6.9-410 on intellij 2023.2.1 (also broken on 2023.2) and fabric loom 1.3.9 (latest as of writing). Could have been the loom 1.3 update breaking something or something else, but the fix no longer seems to work.

**Comment by RedNesto** [comment]
The template mod with split sourcesets works fine for me using 2023.2-1.6.10 on 2023.2.1. Using loom 1.3-SNAPSHOT, freshly created.

**Comment by MattiDragon** [comment]
Hmm. Why didn't my setup work? I made a project with the setup wizard, and enabled split sources by adding the line to the build.gradle.

**Comment by RedNesto** [comment]
Can't tell without seeing the whole project. But the wizard doesn't generate a project layout compatible with the split source sets option so only modifying the build.gradle file won't work.

Use fabric's mod template generator instead.

**Comment by MattiDragon** [comment]
What I did was I tweaked the buildscript, set up the client source set and moved the client code there. Besides mcdev it's working just fine

**Comment by MattiDragon** [comment]
Here's a slightly fixed version of a project generated with mcdev. I've enabled split sources, created a client mixins file and fixed the broken entrypoint classes. [Example.zip](https://github.com/minecraft-dev/MinecraftDev/files/13196215/Example.zip)

This is how the fabric.mod.json looks like:
![image](https://github.com/minecraft-dev/MinecraftDev/assets/61198884/d1632bc0-65eb-425f-9df2-2f747ea04941)
The icon is actually missing, but the entrypoint and mixins file do exist

**Comment by MattiDragon** [comment]
Have you tried to reproduce this with the project above?

**Comment by JPeroutek** [comment]
I am encountering this issue.  
Intellij IDEA 2023.3.6 (Community Edition), latest 
Plugin version 2023.3-1.8.1
