### ISSUE TITLE
Remove validation on group ID

### ISSUE THREAD

**Issue by jimraynor2470** [DemonWav/MinecraftDevIntelliJ#1956]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### Description of the feature request

In `creator/buildsystem/BuildSystemPropertiesStep.kt`, there is `nonExampleValidation` which prevents creating a project with `org.example` as group ID. Sometimes, I just want to create a throwaway project to test something quickly, but I have to keep changing group ID since it is not allowed. Is there a reason behind this? Can it be removed or perhaps have it as a suggestion rather than a hard error preventing creating a project?

**Comment by Earthcomputer** [comment]
I wanted to prevent people from leaving it as the default. It remembers what you last set it to, so it shouldn't be a huge problem to create throwaway projects quickly once you've set it once.
