### ISSUE TITLE
Add paper plugins with paper-plugin.yml file

### ISSUE THREAD

**Issue by SageSphinx63920** [DemonWav/MinecraftDevIntelliJ#1958]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.1-369

### Description of the feature request

Paper added their new plugins and the plugin doesn't support the  new yaml file yet. No autocomplete and not even the creation of the file itself when choosing paper plugin. https://docs.papermc.io/paper/dev/getting-started/paper-plugins

**Comment by RedNesto** [comment]
Implemented in 78680be6a02fe3d7a54a32e62b14dfe7be95e84e

**Comment by SageSphinx63920** [comment]
https://github.com/minecraft-dev/MinecraftDev/commit/78680be6a02fe3d7a54a32e62b14dfe7be95e84e#commitcomment-107182114
