### ISSUE TITLE
JDK not selecting

### ISSUE THREAD

**Issue by GreenedDev** [DemonWav/MinecraftDevIntelliJ#1959]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

IC-223.8617.56

### Operating System

Windows 10

### Target platform

Waterfall

### Additional description

JDK is not selecting when i click on it's folder and click OK

**Comment by natanfoleto** [comment]
I have the same problem

**Comment by IuCC123** [comment]
Same here

**Comment by Earthcomputer** [comment]
Can one of you take a screenshot of what it looks like?

**Comment by IuCC123** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/80768059/224154821-6abe5989-a69d-4274-b6e5-66e1696ea0fc.png">
Whenever I click a JDK it just resets to this

**Comment by Earthcomputer** [comment]
What JDKs do you have installed on your system?

**Comment by GreenedDev** [comment]
![image](https://user-images.githubusercontent.com/108997309/224297211-9fa9f421-7ff8-45d0-99a2-27298152782c.png)

**Comment by GreenedDev** [comment]
still cant create project. anyone here?

**Comment by killua-glich** [comment]
same problem
