### ISSUE TITLE
Why Project

### ISSUE THREAD

**Issue by RudolfRaspe** [DemonWav/MinecraftDevIntelliJ#1960]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

IU-223.8617.56

### Operating System

Windows 11

### Target platform

Spigot, Paper, Sponge, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

Previously, the project wizard for creating plugins for Minecraft I had a new one, and now everything is on one page, help
![image](https://user-images.githubusercontent.com/90341601/223561138-4549ef8a-767a-4ee2-8fb2-00548e8a9d79.png)

**Comment by Earthcomputer** [comment]
Yes, the project wizard was redesigned, this is intended.
