### ISSUE TITLE
[Fabric] Entrypoint-Configuration missing after new UI-Update

### ISSUE THREAD

**Issue by LunaticWasTaken** [DemonWav/MinecraftDevIntelliJ#1961]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1-369

### Description of the feature request

Before the new UI-Update, we had the Option to remove/add entrypoints, change their names, etc.

Now after the Update, we can only change between "Client", "Server" and "Both", but in some cases Entrypoints are not needed for a mod, as stuff is handled internally via mixin-only.

Please bring this Option back, or at least add a "None" Option to the new "Entrypoints" Submenu.

**Comment by Earthcomputer** [comment]
Being able to disable entrypoints was an oversight when I removed this option

**Comment by LunaticWasTaken** [comment]
So does it get added back in the next update or does it remain gone?
