### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#1967]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

Build #IC-223.8836.41, built on March 10, 2023

### Operating System

Windows 11

### Target platform

Spigot

### Description of the bug

Massive memory leaks with plugin when copying/removing chunks of code
https://youtu.be/Pe3vGSk4BXM

**Comment by Earthcomputer** [comment]
That's the `Material` class in Bukkit, nothing to do with mcdev.
