### ISSUE TITLE
settings to allways add custom repositories

### ISSUE THREAD

**Issue by filtastisch** [DemonWav/MinecraftDevIntelliJ#1969]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### Description of the feature request

Just an option maybe somewhere in the settings or in the optional settings where i can configure my own repository. A setting where you can add repos by default would be ideal.

And thanks for the great plugin <3

**Comment by filtastisch** [comment]
btw, i just updated the plugin and saw, that the version doesnt match the release xd

![grafik](https://user-images.githubusercontent.com/55882591/224608080-80834f6f-9685-4d4f-a991-0c479e34d28b.png)

**Comment by RedNesto** [comment]
You can add your repository to the build file template in the settings `File | Settings | Editor | File and Code Templates` under the Other tab

**Comment by filtastisch** [comment]
ohhhh thank you
