### ISSUE TITLE
Old project wizard

### ISSUE THREAD

**Issue by yavda1** [DemonWav/MinecraftDevIntelliJ#1971]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1 

### IntelliJ version

IC-223.8836.41

### Operating System

Mac OS X

### Target platform

Spigot

### Additional description

Hi

 I'm trying to get back into plugin development but when I install the plugin im getting this outdated wizard. The normal one that I used to get with all the options is not showing up and I'm getting something else. I've tried clearing my cache and reinstalling the plugin but nothing works. 

<img width="798" alt="Screen Shot 2023-03-13 at 6 07 55 PM" src="https://user-images.githubusercontent.com/94653933/224866130-ec4a1e62-6f8e-47f1-8c85-b9c5923f29ab.png">

What menu is showing up for me

**Comment by RedNesto** [comment]
This is the new project wizard released in 1.6.

If you are missing features that you think should exist in the newer versions you can open an issue to ask for it.
