### ISSUE TITLE
MAVEN no build confi

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [DemonWav/MinecraftDevIntelliJ#1973]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

IC-223.8836.41

### Operating System

Windows 11

### Target platform

Spigot

### Additional description

I've always used maven and was able to press run and a jar was issued to me... meanwhile, since the new update, no configuration has been stored in maven, which means you can't press the run button. it works with gradle but I want it to work again on maven

**Comment by 1mvghost** [comment]
Same here, hope it gets fixed

**Comment by RedNesto** [comment]
Fixed in the next nightly
