### ISSUE TITLE
Maven build configuration is not being created

### ISSUE THREAD

**Issue by 1mvghost** [DemonWav/MinecraftDevIntelliJ#1975]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1-369

### IntelliJ version

IC-223.8836.35

### Operating System

Windows 11 64-bit

### Target platform

Bukkit, Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, Mixins, BungeeCord, Waterfall

### Description of the bug

After updating the IDE and the plugin, the project Maven build configuration isn't being created.

When creating the project using Gradle, the build configuration is made.

**Comment by ThatGuyCalledJesse** [comment]
I also have this issue using Maven, gradle works

**Comment by ThatGuyCalledJesse** [comment]
I am still having this issue

**Comment by Earthcomputer** [comment]
that's because the release with the fix isn't out yet.

**Comment by ThatGuyCalledJesse** [comment]
Ah ok, thank you for responding so fast!
