### ISSUE TITLE
Support files with `.png.mcmeta` as JSON

### ISSUE THREAD

**Issue by Mysterious-Dev** [DemonWav/MinecraftDevIntelliJ#1977]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.2

### Description of the feature request

With the PR that add JSON schema (SchemaStore) for this extension, that would be great if the plugin support files with `.png.mcmeta` extension as JSON (to allow IDEA to detect which schema can be applied) ^^.

https://github.com/SchemaStore/schemastore/pull/2833

**Comment by Earthcomputer** [comment]
I'm pretty sure intellij is supposed to do this already, given your schema checks for the path `**/assets/*/textures/**/*.png.mcmeta`

**Comment by Mysterious-Dev** [comment]
Not really, it's like pack.mcmeta

https://github.com/minecraft-dev/MinecraftDev/blob/c9139e6a56d8e423957c79a6c0558eda10be5529/src/main/kotlin/platform/forge/ForgeModule.kt#L60

**Comment by Mysterious-Dev** [comment]
I see IntelliJ let add fileType in plugin.xml but my tests were not very conclusive :/.

https://plugins.jetbrains.com/docs/intellij/registering-file-type.html#registration

https://plugins.jetbrains.com/docs/intellij/language-and-filetype.html?from=jetbrains.org#run-the-project
