### ISSUE TITLE
Project Wizard Outdated

### ISSUE THREAD

**Issue by Jaoow** [DemonWav/MinecraftDevIntelliJ#1978]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.2

### IntelliJ version

IU-231.8109.144

### Operating System

Windows

### Target platform

Spigot

### Additional description

My Project Wizard does not seem to be up-to-date

**Comment by Jaoow** [comment]
![image](https://user-images.githubusercontent.com/57773902/227652944-e6c0f98c-41c4-410d-a0a0-185b65a764b9.png)

**Comment by Earthcomputer** [comment]
Hello, can you please be more specific, what exactly is not up-to-date?

**Comment by Mysterious-Dev** [comment]
Maybe plugin version ?

**Comment by KleverSE** [comment]
I have this exact same issue

**Comment by anonymous123-code** [comment]
Maybe duplicate of #1971 ?
