### ISSUE TITLE
broken mod create ui.

### ISSUE THREAD

**Issue by Corbonat** [DemonWav/MinecraftDevIntelliJ#1979]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.2

### IntelliJ version

IC-223.8836.41

### Operating System

Windows 10

### Target platform

Fabric

### Additional description

![Screenshot_36](https://user-images.githubusercontent.com/119676769/227707122-e5cb83b2-1f96-4dd5-8cdb-389f88aa80ca.png)
ui look like parody. I can't create new mod without empty project from github, because when i try to create new mod, there is always some problems with gradle. It happend when i reinstalled my windows.

**Comment by Earthcomputer** [comment]
This is an issue with Gradle/Loom and not mcdev.

**Comment by Corbonat** [comment]
Gradle changed mcdev ui?

**Comment by Earthcomputer** [comment]
The UI isn't broken. You never specified what was broken about the UI.
