### ISSUE TITLE
Cant select Version?

### ISSUE THREAD

**Issue by zivthefire** [DemonWav/MinecraftDevIntelliJ#1981]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.2

### IntelliJ version

IC-222.3739.54

### Operating System

Windows 10

### Target platform

Spigot

### Additional description

fsr i have a old menu without a version option there is not much to say

**Comment by RedNesto** [comment]
The "old menu" is likely the new wizard UI rewritten to follow Jetbrains' new UI.

The versions not loading might be an issue on your end preventing you from downloading the versions list.
