### ISSUE TITLE
I need to create a forge of 1.8.9

### ISSUE THREAD

**Issue by RedCarl** [DemonWav/MinecraftDevIntelliJ#1982]
### Minecraft Development for IntelliJ plugin version

3.3

### Description of the feature request

I need to create a forge of 1.8.9

**Comment by Mysterious-Dev** [comment]
The warning message was not big enough in my opinion :/.

**Comment by RedCarl** [comment]
what?

**Comment by RedCarl** [comment]
I can only see versions minimum 1.16.5 available for selection

**Comment by RedCarl** [comment]
I need to develop a mod for 1.8.9

**Comment by RedCarl** [comment]
Ok, sorry, I just saw that warning. My English is not good, I can't understand that sentence at a glance, sorry
