### ISSUE TITLE
CREATE button doesn't working

### ISSUE THREAD

**Issue by ChemFlix** [DemonWav/MinecraftDevIntelliJ#1983]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.2

### IntelliJ version

IC-223.8836.41

### Operating System

Windows 11

### Target platform

Paper

### Additional description

When I click on CREATE it doesn't create a new project. Instead the input box of 'Name:' is selected.
![Welcome to IntelliJ IDEA 27 03 2023 17_51_37](https://user-images.githubusercontent.com/114338506/227995200-34b647e1-b726-45a3-9661-efad5321dff2.png)

**Comment by SinonCute** [comment]
same

**Comment by Thepigcat76** [comment]
I have the same issue as well

**Comment by IuCC123** [comment]
I found a temporarily fix, you just click create and edit the JDK in the options of the project

**Comment by Rajala1404** [comment]
same
