### ISSUE TITLE
Cannot create new fabric mod

### ISSUE THREAD

**Issue by GetNameSniped** [DemonWav/MinecraftDevIntelliJ#1986]
### Minecraft Development for IntelliJ plugin version

2021.1 - 1.5.19

### IntelliJ version

2021.1.1

### Operating System

Windows 10

### Target platform

Fabric

### Description of the bug

Whenever i attempt to create a new fabric mod, no dropdowns work, except for the, environment dropdown and the license dropdown.
This means i cannot select the minecraft version, the yarn version, the loader version, the loom version, or the fabric api version.
I have tried reinstalling intellij, reinstalling the plugin, etc. etc.
Nothing works.

**Comment by RedNesto** [comment]
The fabric creator works fine on my end. It might be an issue on your network, like a firewall blocking connections to the various services the versions are pulled from.

AFAIK the creator accesses `https://api.modrinth.com/v2/project/P7dR8mSH/version` and `https://meta.fabricmc.net/v2/versions`
