### ISSUE TITLE
Fabric mod project generation generates wrongly with errors

### ISSUE THREAD

**Issue by levyishai** [DemonWav/MinecraftDevIntelliJ#1989]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

2023.1

### Operating System

Windows 10

### Target platform

Fabric

### Description of the bug

When I generate a new fabric mod project (1.19.4), it generates the two main classes without the package declaration.
Also, a couple of errors show up while generating the project: 
Failed to setup Minecraft, java.nio.file.NoSuchFileException: C:\Users\yishi\.gradle\caches\fabric-loom\1.19.4\minecraft-client.jar
Cannot invoke "String.lastIndexOf(int)" because "deobfuscatedName" is null

The same thing seems to occur when using 1.19.3

**Comment by thesnipe12** [comment]
Why did you close this?
