### ISSUE TITLE
Project Wizard Looks Odd

### ISSUE THREAD

**Issue by devAshton** [DemonWav/MinecraftDevIntelliJ#1990]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.3

### IntelliJ version

2022.3.3

### Operating System

Windows 11

### Target platform

Spigot, Paper, Minecraft Forge

### Additional description

The project creation looks very outdated and not like any other of the tutorials i'm currently watching.
![idea64_ODNswjMDat](https://user-images.githubusercontent.com/77751671/229380658-8caf8c59-e033-4790-a811-6da7440bf76e.png)

**Comment by RedNesto** [comment]
Duplicate of #1971
