### ISSUE TITLE
I cant create a new project. It just doesnt work without error message or something like that... Nothing

### ISSUE THREAD

**Issue by AC1prmry** [DemonWav/MinecraftDevIntelliJ#1994]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.3

### IntelliJ version

IC-223.8836.41

### Operating System

Windows 10

### Target platform

Minecraft Forge

### Additional description

the title says everything. Can someone pls help me?

**Comment by nomirva** [comment]
I'm facing the same problem, I have arch linux

**Comment by Polda18** [comment]
Just today, Windows 11 64bit (build 25330.1000, 22H2).

**Comment by tianxiansheng2003** [comment]
me to

**Comment by Vulpino** [comment]
Same here Win 11 22621.1631, 22H2

**Comment by JaaiDead** [comment]
same Here Windows 10 . Intelij 2023.1

**Comment by JaaiDead** [comment]
even for fabric its does not work with the new ui
