### ISSUE TITLE
Incompatible Build

### ISSUE THREAD

**Issue by n-tdi** [DemonWav/MinecraftDevIntelliJ#1995]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.1

### IntelliJ version

2023.1

### Operating System

Windows

### Target platform

Bukkit, Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, Mixins, BungeeCord, Waterfall

### Description of the bug

Incompatibe builds for the plugin on InteliJ ultimate. Here's the plugin error:

`Incompatible: requires IDE build .223* or earlier`

**Comment by RedNesto** [comment]
[The plugin does have a 2023.1 version](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/stable/312720). You likely encountered an Intellij issue. Reinstalling the plugin should do it.
