### ISSUE TITLE
Gateway plugin

### ISSUE THREAD

**Issue by lambdagg** [DemonWav/MinecraftDevIntelliJ#1997]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### Description of the feature request

Hello,
I've been using MinecraftDev for a while now but now that I've switched to JetBrains' Remote Development tools, I realize that this plugin must be installed separately in each project if I want it to work on all of them.
A solution would be to have a Client plugin that checks for the Host plugin and installs it if not found, but I don't think this is the best idea.
As for now, I'm using the one-by-one solution but it would be nice to have a Gateway plugin.

**Comment by lambdagg** [comment]
update: instead of using the Gateway application, I'm now using IntelliJ IDEA with the plugin installed to connect to the remote development environment.

**Comment by lambdagg** [comment]
update: this doesn't work

**Comment by RedNesto** [comment]
This is by design https://www.jetbrains.com/help/idea/faq-about-remote-development.html#plugins

I don't see anything we'd need to do, this is the same for other plugins.
