### ISSUE TITLE
Package line is not added in new fabric projects

### ISSUE THREAD

**Issue by uku3lig** [DemonWav/MinecraftDevIntelliJ#1998]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

2023.1

### Operating System

Linux

### Target platform

Fabric

### Description of the bug

When creating a new project, java files for entrypoint such as `ModName.java` and `ModNameClient.java` are generated without the package line (eg. `package net.uku3lig.modname;`) before the class definition.
![image](https://user-images.githubusercontent.com/61147779/230690994-0f2557f1-1e88-4bbe-95fe-fefe5937e931.png)

**Comment by baka4n** [comment]
I have also encountered this situation, and now I can only manually set it up. The problem is not significant, but it is not very convenient
