### ISSUE TITLE
Can no longer use breakpoints in Mixins

### ISSUE THREAD

**Issue by Insane96** [DemonWav/MinecraftDevIntelliJ#1999]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3-377

### IntelliJ version

#IC-231.8109.175

### Operating System

Windows 11

### Target platform

Minecraft Forge, Mixins

### Description of the bug

Since I've updated to IntelliJ 2023.1 (and subsequently the plugin), adding breakpoints into mixins no longer works.

I have this simple mixin:
```java
@Mixin(ArrowInfiniteEnchantment.class)
public abstract class ArrowInfiniteEnchantmentMixin {
	@Inject(at = @At("RETURN"), method = "getMinCost", cancellable = true)
	private void onGetMinCost(int lvl, CallbackInfoReturnable<Integer> cir) {
		cir.setReturnValue(lvl * 12);
	}

	@Inject(at = @At("RETURN"), method = "getMaxCost", cancellable = true)
	private void onGetMaxCost(int lvl, CallbackInfoReturnable<Integer> cir) {
		cir.setReturnValue(65);
	}
}
```

But when I try to set the breakpoint to `cir.setReturnValue(lvl * 12);` I get
![image](https://user-images.githubusercontent.com/7185104/231128912-1f51d759-c5b1-437c-b84b-b07acc14fee7.png)

The error doesn't pop out if the breakpoint is set when debugging is stopped, but it still doesn't work

**Comment by RedNesto** [comment]
This works fine on my end, same IDEA and plugin version.

Have you tried a gradle clean build ? Or invalidating caches after the IDE update ?
