### ISSUE TITLE
Make Spigot version 1.10 selectable  in the minecraft version dropdown

### ISSUE THREAD

**Issue by MiniDigger** [DemonWav/MinecraftDevIntelliJ#20]

**Comment by sgdc3** [comment]
And 1.10.2 ;)

**Comment by MiniDigger** [comment]
idk how your system works but the easiest way to think of to always have the latest version would be grabbing it from here: https://hub.spigotmc.org/versions/

**Comment by DemonWav** [comment]
That's where BuildToolsGUI gets the latest versions from, but I'm personally not a fan of having to hit a pseduo-API just for project creation. MC version bumps happen infrequently enough I feel that hard-coding the values is the best option, I just need to be more on the ball when it comes to getting an update out for it.

**Comment by MiniDigger** [comment]
thats why you have us to remind you ^^

**Comment by DemonWav** [comment]
Fixed in a9dda5b3 :)
