### ISSUE TITLE
No Gui(No Spigot in gui)

### ISSUE THREAD

**Issue by SuchterKingg** [DemonWav/MinecraftDevIntelliJ#2000]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

IC-231.8109.175

### Operating System

Windows

### Target platform

Spigot

### Additional description

I installed the newest version of intellij and The dev kit. but the Gui dont looks like normal and there is no option to choose spigot

**Comment by Leguan16** [comment]
you need to check if you have Platform Type (Plugin), Platform (Bukkit) and Bukkit Platform (Spigot) selected.
But please consider using Paper over Spigot. 
![image](https://user-images.githubusercontent.com/59799222/234017941-113ca223-014f-4786-aab2-cc74a1973eb2.png)
