### ISSUE TITLE
Can't create a project

### ISSUE THREAD

**Issue by Rame839** [DemonWav/MinecraftDevIntelliJ#2002]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.3

### IntelliJ version

IU-223.8836.41

### Operating System

Windows 11

### Target platform

Spigot

### Additional description

Hi,
When im going to create a new project and click on create button, that doesn't work and "tag" me the pluginname field

**Comment by kainlighty** [comment]
At the most inopportune moment...

**Comment by fstrx** [comment]
Im having the same issue with Fabric with Mixins

**Comment by Rame839** [comment]
> Im having the same issue with Fabric with Mixins

do you have resolved?

**Comment by ColonelGerdauf** [comment]
I will say that the current build makes it completely impossible to create any Minecraft project, regardless of settings used.
