### ISSUE TITLE
nimmt denn Projekt Namen nicht an 

### ISSUE THREAD

**Issue by Battosaixx** [DemonWav/MinecraftDevIntelliJ#2012]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

IU-231.8109.175

### Operating System

Windows

### Target platform

Spigot

### Additional description

nimmt denn Projekt Namen nicht an

**Comment by itsTyrion** [comment]
- English would probably be better (deepl translator is usually good/Deepl Translator ist normalerweise gut)
- Can you elaborate on that/Kannst du das genauer erklären?
- Why Spigot not Paper/Warum spigot nicht Paper
