### ISSUE TITLE
Add Quilt Mod Support

### ISSUE THREAD

**Issue by MarcPG1905** [DemonWav/MinecraftDevIntelliJ#2014]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.3

### IntelliJ version

IC-222.4459.24

### Operating System

Windows 11

### Target platform

Fabric

### Additional description

Please add an option to make a Quilt mod, because I think it will be the newest loader that will maybe even overtake Fabric and Forge

**Comment by Earthcomputer** [comment]
You were told in the form not to use it to request new platforms.

**Comment by sylv256** [comment]
(duplicate of #1827)
