### ISSUE TITLE
Gradle project not loading properly

### ISSUE THREAD

**Issue by Javatrix** [DemonWav/MinecraftDevIntelliJ#2015]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

2022.3.3

### Operating System

Windows 10

### Description of the bug

When creating new fabric mod project, gradle stops loading after a while leaving corrupted classes like the attached one, without package line and methods. Console says: Cannot use connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.3.3-bin.zip' as it has been stopped.
Also, it does not create mod.mixins.json file
![Screenshot 2023-04-22 104720](https://user-images.githubusercontent.com/108270039/233773774-4c4bf07e-5cde-467d-a1ac-9dd3e94d7f8e.png)
![Screenshot 2023-04-22 104730](https://user-images.githubusercontent.com/108270039/233773776-788dde99-a73e-4e46-ac64-b36602ee7ec8.png)

**Comment by Mysterious-Dev** [comment]
Can you try to update mcdev to nightly builds and try again ?

**Comment by Javatrix** [comment]
Where can I find the builds you talk about? And how do I install them in intellij?

**Comment by Leguan16** [comment]
This: https://ci.denwav.dev/buildConfiguration/MinecraftDev_Build/8739?buildTab=artifacts (latest build as of  23 April 2023)
And this: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by Mysterious-Dev** [comment]
Nop Go to File > Settings > Languages & Framework > Minecraft Development, click on the button "Change plugin update channel and change from Stable to Nightly (and click on the button "Check for updates now" ^^.

**Comment by Leguan16** [comment]
is my way wrong?

**Comment by Mysterious-Dev** [comment]
No, but it's easier to do it the way described above ^^

**Comment by Leguan16** [comment]
eh 🤷🏻‍♂️ works both. I didnt knew it before either. Just wanted to demonstrate that its possible to achieve everything with eyes.

**Comment by Javatrix** [comment]
Kinda did work, but I created new test project, and i got this error message. What is this gradleIdentityPath and how do i set it?
![wasd](https://user-images.githubusercontent.com/108270039/233975216-dffd0262-d908-4b72-83e7-3067cae4d83f.png)

**Comment by Javatrix912** [comment]
btwit at least created the project properly, so I guess the issue is fixed now.

**Comment by Javatrix** [comment]
No, it still doesnt work. It worked only once, but now every new project is corrupted the same way except this time it adds mixins,json file. Packages and implementations are still not there.

**Comment by Leguan16** [comment]
tried updating your intellij?

**Comment by Javatrix** [comment]
not yet, the download says 2 hours left xDDDDDD

**Comment by Javatrix** [comment]
Nope, updating didn't work :(
Only clue I have is the error message that i attached earlier.

**Comment by Leguan16** [comment]
tried unlinking and linking it again? (in the gradle tool window)

**Comment by Javatrix** [comment]
Didn't work. :\

**Comment by Leguan16** [comment]
well sorry buddy. This seems like a IntelliJ issue since it has been reported on their Issue tracker. But they don't give much information on how to fix it. 
https://youtrack.jetbrains.com/issue/IDEA-314641

**Comment by Javatrix** [comment]
Well, thank you all for the support though. I will just have to manually add the missing filed and fix the corrupted ones :/
Bye👋

**Comment by Leguan16** [comment]
do you use the gradle wrapper or do you have gradle installed and configured in intelliJ?

**Comment by Javatrix** [comment]
i have it installed in intellij, i have not used gradle before starting to mod mc, IDE just auto-downloaded it.

**Comment by Javatrix** [comment]
New update came out, problem fixed! Thanks, dev!

**Comment by Leguan16** [comment]
Looks like this was an IntelliJ issue after all:
![image](https://github.com/minecraft-dev/MinecraftDev/assets/59799222/c8e00138-475b-4fc5-af78-12872cfc4736)
https://youtrack.jetbrains.com/issue/IDEA-317045/Resync-Gradle-projects-throws-Missing-gradleIdentityPath
