### ISSUE TITLE
Minecraft plugin cannot read JDK files

### ISSUE THREAD

**Issue by CatPixelNetWork** [DemonWav/MinecraftDevIntelliJ#2017]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.3

### IntelliJ version

IC-231.8770.65

### Operating System

Windows

### Target platform

Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

In the latest version, the plugin cannot read my JDK file, and manual import is also invalid. After restarting IDEA, selecting JDK in the plugin will directly disappear, but IDEA software can read my JDK file

**Comment by Ex0nl** [comment]
Bro got the same problem idk why it aint working
