### ISSUE TITLE
Mixin breakpoints don't work when IDEA Android plugin is enabled

### ISSUE THREAD

**Issue by makamys** [DemonWav/MinecraftDevIntelliJ#2019]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

2023.1.1 (#IC-231.8770.65)

### Operating System

Windows 10

### Target platform

Mixins

### Description of the bug

When IDEA's Android plugin is enabled, (**which comes bundled with IDEA and is enabled by default,**) breakpoints in mixins don't get hit. This is likely to be the underlying cause of https://github.com/minecraft-dev/MinecraftDev/issues/1999. Once the plugin is disabled, breakpoints work.

This is a regression. I have tested the following versions with the Android plugin enabled, placing a breakpoint in [fabric-example-mod's example mixin](https://github.com/FabricMC/fabric-example-mod/blob/38f93b4e0744a819272bf7077bfeed76cb3e7d14/src/main/java/net/fabricmc/example/mixin/ExampleMixin.java#L14):

| IDEA version | Minecraft Dev version | Result |
| --- | --- | --- |
| 2021.1.3 (#IC-211.7628.21) | 2021.1-1.5.19 | ✅ Breakpoint gets hit |
| 2022.3.2 (#IC-223.8617.56) | 2022.3-1.6.4 | ❌ Breakpoint is ignored |
| 2023.1.1 (#IC-231.8770.65) | 2023.1-1.6.4 | ❌ Breakpoint is ignored |

### Code analysis

It seems the Android plugin's `PositionManager` is taking priority over the Mixin plugin's when the `locationsOfLine` call is dispatched from `LineBreakpoint#createRequestForPreparedClass`. `MixinPositionManager#locationsOfLine` thus never gets called.

(The first element of `myPositionManagers` shown in this screenshot is `AndroidPositionManager`, the second is `MixinPositionManager`.)
![](https://user-images.githubusercontent.com/13667520/235353527-6ba35e7d-626f-4355-aaab-dd2ad5c644e6.png)

**Comment by RedNesto** [comment]
Thanks for the analysis 👍 
I think I got a fix, it'll be available in the next nigthly build.

**Comment by makamys** [comment]
Seems to be working fine now.
![](https://user-images.githubusercontent.com/13667520/236203177-cb3bc1d5-352b-4d31-aa0f-9f750d3fead3.png)
