### ISSUE TITLE
Detect identical method name in double inheritance

### ISSUE THREAD

**Issue by USS-Shenzhou** [DemonWav/MinecraftDevIntelliJ#2022]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### Description of the feature request

By identical method name in double inheritance, I mean the situation that a mod's class extends a vanilla MC class while implementing a new interface, like this:

![image](https://user-images.githubusercontent.com/57312492/235433204-add716a2-7cdf-49ef-a176-298b9d375fc5.png)

During mod-build reobfuscation, `YourClass#foo` will be renamed to `YourClass#<VanillaClass' foo's obfuscation name>`, but the calling `yourClass.foo()` won't get changed, which will cause a error like `Caused by: java.lang.AbstractMethodError: Receiver class YourClass does not define or inherit an implementation of the resolved method 'foo()' of interface IYourInterface.`

This identical-name-in-double-inheritance is hard to be found out when you are in a developing enviroment if you don't know the vanilla father class has a method with the same name - until the game crashes in a production enviroment. So a detcet-and-alert should be very helpful.

**Comment by Earthcomputer** [comment]
This honestly looks like a bug with the build tool you are using.

**Comment by USS-Shenzhou** [comment]
> This honestly looks like a bug with the build tool you are using.

I'm using just normal Forge toolchain, and (I think) it's difficult for reobfuscation tools to clearly and correctly find out which exact method is referenced, or wanted, and should be reobfuscated. Giving an alert to modders seems much better.

**Comment by Earthcomputer** [comment]
The way the reobfuscation tool *should* be doing this is by adding a bridge method so both methods are implemented.

**Comment by USS-Shenzhou** [comment]
Sounds reasonable but still a little odd. I'll take that for now. Thank you for your reply.
