### ISSUE TITLE
release version 17 not supported on compileJava Task

### ISSUE THREAD

**Issue by dayo05** [DemonWav/MinecraftDevIntelliJ#2023]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

2023.1 Community 231.8109.175

### Operating System

Mac OS 13.3.1 (22E261)

### Target platform

Fabric, Mixins

### Description of the bug

I have a project which uses Kotlin/Java both and when I try to execute that, it shows `Cause: error: release version 17 not supported` compile error. 
When I change project Java version to 11 and set `targetJavaVersion` to 11, force-set runClient task to use Java 17 then it works well.

### My Kotlin configuration method:
1. Create project by plugin and wait for full-initialize
2. Configure kotlin with intellij feature(ctrl + alt + shift + K) with latest version of Kotlin
3. Change the Kotlin language implementation to [kotlin-language-fabric](https://github.com/FabricMC/fabric-language-kotlin) mod

**Comment by dayo05** [comment]
When I try to use minecraft related class in the Java class then It shows error:
```
  bad class file: /Users/dayo/IdeaProjects/mctest/.gradle/loom-cache/minecraftMaven/net/minecraft/minecraft-merged-project-root/1.18.2-net.fabricmc.yarn.1_18_2.1.18.2+build.4-v2/minecraft-merged-project-root-1.18.2-net.fabricmc.yarn.1_18_2.1.18.2+build.4-v2.jar(/net/minecraft/network/packet/c2s/play/PlayerInteractEntityC2SPacket.class)
    class file has wrong version 61.0, should be 55.0
```

**Comment by dayo05** [comment]
This has caused by the invalid `jvmToolchain` call on gradle file; extra study will need for that maybe

**Comment by RedNesto** [comment]
Sounds like your Gradle process isn't running on JDK 17. Make sure your project SDK and Gradle JDK are set to a Java 17 distribution.

**Comment by dayo05** [comment]
> Sounds like your Gradle process isn't running on JDK 17. Make sure your project SDK and Gradle JDK are set to a Java 17 distribution.

No. If that case, it throws NotSupportedError.
