### ISSUE TITLE
Idea hangs adding new entry in localization file.

### ISSUE THREAD

**Issue by blackd** [DemonWav/MinecraftDevIntelliJ#2030]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

Build #IU-231.8770.65

### Operating System

Gentoo Linux

### Target platform

Minecraft Forge, Fabric

## While adding new entry in localization file idea hangs and it's JVM process keeps all cores at 100%.

Thread Dump form the time of the hang: [idea-hang-thread-dump.txt](https://github.com/minecraft-dev/MinecraftDev/files/11422956/idea-hang-thread-dump.txt)

### Steps to reproduce:

1. Checkout and import `https://github.com/blackd/Inventory-Profiles/` at tag `idea-hang-problem`. **The project requires Linux** 
2. Wait for gradle project to be imported and indexes to be created/downloaded.
3. Open `platforms/fabric-1.19.4/src/shared/resources/assets/inventoryprofilesnext/lang/en_us.json`
4. Try to add `"": ""` after the `{` if nothing happens move the cursor between the second `""`

### Expected behaviour:

Allow editing of the opened file.

### Actual behaviour:

The whole IDE hangs. Most if the times event the mouse cursor disappears. 
Only way to recover is to send SIG_KILL, any other signal gets ignored.

**Comment by RedNesto** [comment]
I basically reverted the bad commit and added a guard instead to avoid the error I tried to fix in the first place.

The next nightly build should be released in about 6 hours.
