### ISSUE TITLE
Soft lock when handling translation lines

### ISSUE THREAD

**Issue by MehVahdJukaar** [DemonWav/MinecraftDevIntelliJ#2031]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

2023.1

### Operating System

Windows

### Target platform

Architectury

### Description of the bug

When viewing or editing translation lines the IDE completely freezes, taking up huge amount of memory and becomes unresponsive. Only solution is to force close it from the task manager

**Comment by RedNesto** [comment]
This has been fixed in the nightly build https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/nightly/329994
