### ISSUE TITLE
HaruClient

### ISSUE THREAD

**Issue by angelofwar1** [DemonWav/MinecraftDevIntelliJ#2038]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

IC-231.8770.65

### Operating System

Windows

### Target platform

Minecraft Forge

### Additional description

Prueba de launcher de proyecto minecraft

**Comment by RedNesto** [comment]
Sorry but I'm not sure what you want, and this is probably not the place to ask for it.
