### ISSUE TITLE
The window to choose the version of plugin i want to dev doesn't display and i get the basic menu of intellij with some new option 

### ISSUE THREAD

**Issue by Guillaume-Wlt** [DemonWav/MinecraftDevIntelliJ#2040]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.4

### IntelliJ version

IC-231.9011.34

### Operating System

Windows

### Target platform

Architectury

### Additional description

all in title, first time i use this plugin, i juste discover it and i wanted to try it.
PS : i'm french so my english might be not good.. sorry ^^

**Comment by Earthcomputer** [comment]
Please can you send a screenshot to show what you mean?

**Comment by Guillaume-Wlt** [comment]
i'm sorry icouldn't find the conv after sending the first message, here is the screenshot.
![image](https://github.com/minecraft-dev/MinecraftDev/assets/47671834/d581b11e-89ee-4171-89a1-ecc6ff15d3fe)

it's when i click on new project and minecraft i don't the selection like this  :
![image](https://github.com/minecraft-dev/MinecraftDev/assets/47671834/cd8fd8ad-c0cb-4df9-8468-4efa6abf98f1)

**Comment by Guillaume-Wlt** [comment]
bump
