### ISSUE TITLE
dönner mod

### ISSUE THREAD

**Issue by retropatpc23** [DemonWav/MinecraftDevIntelliJ#2045]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IC-231.9011.34

### Operating System

Windows

### Target platform

Minecraft Forge

### Additional description

in this mod you can eat dönner

**Comment by LunaticWasTaken** [comment]
I don't even know what to say lol

**Comment by RedNesto** [comment]
This issue tracker is not a place for mods/plugins requests.
