### ISSUE TITLE
Sources not being generated correctly

### ISSUE THREAD

**Issue by Tinglyyy** [DemonWav/MinecraftDevIntelliJ#2046]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

17.0.6+ 10-b829.9 amd64

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

Gradle stops generating the Java files at some point, causing the Client (run Client option) to exit with an error before before being able to start. The same bug has already been posted here (https://github.com/minecraft-dev/MinecraftDev/issues/2015) but the solutions don't work for me.
The fabric.mod.json tells "Cannot resolve entry point 'de.unverwunderbar.test.Test'".
This happens every time I create a new Fabric project using the MinecraftDev Plugin.

**Comment by RedNesto** [comment]
See #2054
