### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by Atten007** [DemonWav/MinecraftDevIntelliJ#2048]
### Minecraft Development for IntelliJ plugin version

1.6.5

### Description of the feature request

Hello!

Minecraft 1.20 has been released on 5'o clock PM today and unfortunately, it's not currently available in the Minecraft dev plugin, so I wanted to ask you: Can you add this Minecraft version to your plugin? That may be nice :)

1.20 is currently available for Fabric, Spigot, CraftBukkit and Vanilla.

**Comment by Mysterious-Dev** [comment]
Spigot & BungeeCord is added by minecraft-dev/mcdev.io#50

**Comment by Atten007** [comment]
Ok, can Forge and Fabric please also be added? This may be nice, thanks! 😍

**Comment by Mysterious-Dev** [comment]
Forge is already added.

**Comment by RedNesto** [comment]
Please be patient, Forge and Fabric updates usually involve some templates updates and these can take some time.

**Comment by Earthcomputer** [comment]
What needs changing for Fabric?

**Comment by Mysterious-Dev** [comment]
Maybe class templates

**Comment by Earthcomputer** [comment]
Could you be more specific which ones? Nothing major changed.

**Comment by RedNesto** [comment]
I don't have something specifically in mind, haven't looked into it yet, but I usually check if the mod example changed and update our templates accordingly if it makes sense at least.

I'll probably do it later today.

**Comment by Earthcomputer** [comment]
The example mod has updated to use split source sets, but a single source sets (what we generate already) still work. We should probably make it an option in the creator.

**Comment by ATK422** [comment]
Paper has a stable release for 1.20

**Comment by h0rper** [comment]
Paper takes a stable release 1.20 yesterday

**Comment by Mysterious-Dev** [comment]
minecraft-dev/mcdev.io#51

**Comment by Mysterious-Dev** [comment]
When the PR is merged for Paper, we can close this issue (all versions added) ^^.
