### ISSUE TITLE
I can't create a 1.8.9 plugin

### ISSUE THREAD

**Issue by Aplicat0r** [DemonWav/MinecraftDevIntelliJ#2049]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IntelliJ IDEA 2023.1.2 (Community Edition) Build #IC-231.9011.34

### Operating System

Arch Linux

### Target platform

Paper

### Description of the bug

Im using intellij idea with jdk 1.8 and when i try to create a plugin, the lowest game version is 1.12. I tried to change the version in the pom.xml file by correcting  <version>1.12-R0.1-SNAPSHOT</version> to <version>1.8.9-R0.1-SNAPSHOT</version> but i get this error: Could not find artifact io.papermc.paper:paper-api:jar:1.8.9-R0.1-SNAPSHOT in papermc-repo (https://repo.papermc.io/repository/maven-public/)

**Comment by RedNesto** [comment]
1.8.9 support has been dropped a long time ago
