### ISSUE TITLE
api-version in paper-plugin.yml is not in quotes

### ISSUE THREAD

**Issue by nil-malh** [DemonWav/MinecraftDevIntelliJ#2059]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IU-231.8770.65

### Operating System

Linux

### Target platform

Paper

### Additional description

In the yml file the api-version needs to be in around quotes 

## Expected behaviour

```yml
api-verison: `1.20`
```

## Actual behaviour

```yml
api-version: 1.20
```

This leads to an error when starting the server it can't parse correctly the api-version

**Comment by RedNesto** [comment]
Already fixed in the nightly channel
