### ISSUE TITLE
Need to update addCreative() event

### ISSUE THREAD

**Issue by nullved** [DemonWav/MinecraftDevIntelliJ#2061]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IC-231.9011.34

### Operating System

Windows

### Target platform

Minecraft Forge

### Additional description

the addCreative() event in the main mod class needs to be updated to use BuildCreativeModeTabContentsEvent in Forge 1.20+

**Comment by RedNesto** [comment]
The templates are already updated in the nightly channel.
