### ISSUE TITLE
pom.xml has syntax errors

### ISSUE THREAD

**Issue by robbiestokes21** [DemonWav/MinecraftDevIntelliJ#2063]
### Minecraft Development for IntelliJ plugin version

1.6.5

### IntelliJ version

2023.2 EAP

### Operating System

Windows

### Target platform

Spigot

### Description of the bug

when creating project won't build the pom.xml, only makes the file but won't create insert the xml. Getting a 'pom.xml' has syntax errors empty. Have to import a pom to work.

**Comment by kangarko** [comment]
Same problem on the EAP

**Comment by kangarko** [comment]
![a](https://i.imgur.com/cADVLDP.png) and the pom appears empty
