### ISSUE TITLE
Your plugin doesnt recognise the JDK I've downloaded in it, which makes the plugin useless

### ISSUE THREAD

**Issue by Ex0nl** [DemonWav/MinecraftDevIntelliJ#2064]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5 minecraft-dev

### IntelliJ version

Community Edition Version: 2023.1.2 Build: 231.9011.34

### Operating System

Windows

### Target platform

Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

Whenever I'm trying to select my SDK**(Amazon Corretto 1.8)** which I've downloaded Inside of the Project Creation Wizard, The SDK just disappears and it continues saying < No SDK > which is making the plugin useless. The SDK only reappears when I'm restarting the program. There is an attached file under this comment which shows how it looks to clear confusions. 

https://github.com/minecraft-dev/MinecraftDev/assets/130246966/6e64426d-92c3-462c-9142-96f13067b68f

**Comment by zhangchao257** [comment]
a

**Comment by zhenri-dev** [comment]
i have the same problem

**Comment by RedNesto** [comment]
This happens because the selected Minecraft version is 1.20.1, which requires Java 17 so the creator won't let you select any JDK 8 installation.
