### ISSUE TITLE
Plugin.yml api-version is not a string

### ISSUE THREAD

**Issue by domiehomie** [DemonWav/MinecraftDevIntelliJ#2066]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.5

### IntelliJ version

IntelliJ IDEA 2022.3.1 (Ultimate Edition) Build #IU-223.8214.52, built on December 20, 2022

### Operating System

Windows 11

### Target platform

Bukkit, Spigot, Paper

### Description of the bug

The api-version field in the plugin.yml file is not a string by default. This causes the zero in `1.20` to be cut off, leading to the following exception.
`org.spongepowered.configurate.serialize.SerializationException: [api-version] of type java.lang.String: Provided plugin's version (1.2) is not supported on this version.`
To mitigate this issue, the api-version field should be a string, instead of a float.

**Before:**
```yaml
api-version: 1.20
```

**After:**
```yaml
api-version: '1.20'
```

**Comment by RedNesto** [comment]
Already fixed in the nightly builds

**Comment by Mysterious-Dev** [comment]
It's fixed in nightly build
