### ISSUE TITLE
Creation of Fabric based Mod in default Config

### ISSUE THREAD

**Issue by CarinaSchoppe** [DemonWav/MinecraftDevIntelliJ#2068]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.6

### IntelliJ version

2023.2 EAP Build #IU-232.7754.73

### Operating System

Windows

### Target platform

Fabric

### Description of the bug

When trying to create a new Fabric based mod with the "default" settings and hitting "create" it does not create anything.

Also the "build settings" tab is not realy existing.

**Comment by nullved** [comment]
Same problem here, also on 2023.2-1.6.6

**Comment by Earthcomputer** [comment]
What do you mean the build settings tab is not really existing?

**Comment by CarinaSchoppe** [comment]
Sorry able to Open that section but there is No content

**Comment by Earthcomputer** [comment]
Could you send a screenshot?
