### ISSUE TITLE
Editing Project Wizard Main Class Setting doesn't Work

### ISSUE THREAD

**Issue by ItzTomas** [DemonWav/MinecraftDevIntelliJ#2081]
### Minecraft Development for IntelliJ plugin version

2023.1 - 1.6.7 (Latest at the time of writing)

### IntelliJ version

2023.1.3 (Latest at the time of writing)

### Operating System

Windows 10 Pro (Build 19045)

### Target platform

Bukkit, Spigot

### Description of the bug

It's not painful, but since this option is implemented, I think that should work. When creating a new Project, I always want the Main Class to be called Main.java and not <PluginName>.java, so I always change that option in the Project Wizard. But then, when I create the Project, the Main Class is always called as the Plugin. I thought it was like a feature to change that option in plugin.yml, but I was wrong.

**Comment by CodeCraftPlugin** [comment]
yeah i am also facing this issue

**Comment by CodeCraftPlugin** [comment]
#2007 same
