### ISSUE TITLE
Automatically transform mod name into mod id.

### ISSUE THREAD

**Issue by SzczurekYT** [DemonWav/MinecraftDevIntelliJ#2082]
### Minecraft Development for IntelliJ plugin version

2023-1.6.7

### Description of the feature request

I would be nice thing when creating a mod, that McDev would convert project name into a valid mod id and put in fabric.mod.json or the forge toml file. 
For example `MyCoolProject` should be converted to `my_cool_project`. I don't know how it is on forge, but on fabric both dashes and underscores are valid, personally I think it's better to use underscores, since they are used more in vanilla minecraft, so they fit better, and If someone wants dashes he can change them himself.
I would be nice, so that the generated mod is ready to run like it is with plugins - you press create project button, wait and have a ready to use project.

**Comment by RedNesto** [comment]
Good news for you, I did that yesterday f2f3b1c9dace3985c194b061b2e9761c6ca875d9
It should be in the latest nightly build.
The current conversion is simply lowercase + all invalid characters to `_` for now.

**Comment by SzczurekYT** [comment]
Actually.
If this is implemented we can close this. Or do you want to wait for a release with closing?

**Comment by RedNesto** [comment]
This was released in 1.6.8
