### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by gabiminto** [DemonWav/MinecraftDevIntelliJ#2084]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.7

### IntelliJ version

2022.3.3

### Operating System

Mac Os

### Description of the bug

When attempting to create a project, it just highlights the name of the project. I've tried renaming the project, moving it to different folder, different versions of intellij (2023.1.4, 2023.2 beta specifically) and the nightly build for 6/14/23. Still doesn't work. Forge and plugins don't work as well, however, other projects, such as a blank one or vue, still work. I loaded with the default settings, only changing the java version to Oracale's 17.

**Comment by cloudfuly** [comment]
I have exact the same Problem

**Comment by 0x5BC2** [comment]
Same problem here. Happened on existing project and happened again after I made a new one.
