### ISSUE TITLE
Project does not have src/test when initialized

### ISSUE THREAD

**Issue by yoshi-koyama** [DemonWav/MinecraftDevIntelliJ#2085]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.7

### IntelliJ version

2023.1

### Operating System

macOS Monterey 12.1

### Target platform

Spigot

### Description of the bug

Thank you very much for always providing this plugin.
I have one question.

When creating a project using IntelliJ, I noticed that there is no "src/test" directory and the "build.gradle" file does not include the following configuration:
```java
test {
  useJUnitPlatform()
}
```

A few months ago, when I used it, the "src/test" directory was created automatically when creating a project, and I was able to run tests. Has there been a change in the specifications?

This is how I create a project.
<img width="805" alt="スクリーンショット 2023-07-16 17 53 51" src="https://github.com/minecraft-dev/MinecraftDev/assets/62045457/4663b252-c0e4-48b3-a18f-464cb4deca16">

This is a zip file of my project.
[MinecraftTestProject.zip](https://github.com/minecraft-dev/MinecraftDev/files/12063598/MinecraftTestProject.zip)

**Comment by RedNesto** [comment]
A few months ago we changed the whole project creator. The test sourceset directory is no longer created since then I guess.

Creating the directories is really easy and in most cases plugins don't have tests anyway (unfortunately) so I don't know how relevant adding it back is.

About the Gradle test configuration this can easily be added to the file templates for the platform(s) you use.

**Comment by yoshi-koyama** [comment]
@RedNesto 
Thanks for your advice.

I understand that there have been changes to the processing during project creation.

> Creating the directories is really easy and in most cases plugins don't have tests anyway (unfortunately) so I don't know how relevant adding it back is.

I agree with you. It is straightforward to create a "src/test" directory and add a test configuration to "build.gradle" like this.

```
test {
    useJUnitPlatform()
}
```

**Comment by yoshi-koyama** [comment]
I'm closing it now since the issue has been resolved.
