### ISSUE TITLE
Folia support, Gradle kotlin script DSL

### ISSUE THREAD

**Issue by Cong0707** [DemonWav/MinecraftDevIntelliJ#2086]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.8

### IntelliJ version

IU-231.8109.175

### Operating System

Windows

### Target platform

Paper

### Additional description

hope can add selection for plugin in folia support
and hope can add gradle selection for kotlin DSL

**Comment by RedNesto** [comment]
See #687 and #2016
