### ISSUE TITLE
Bad plugin.yml api-version formatting

### ISSUE THREAD

**Issue by zefir-git** [DemonWav/MinecraftDevIntelliJ#2087]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.5

### IntelliJ version

IU-231.9011.34

### Operating System

Linux

### Target platform

Paper

### Additional description

When creating a new project, `plugin.yml` contains
```yaml
# …
api-version: 1.20
```

I believe this gets parsed as "1.2" in Paper since it is entered as a valid float in the YAML. Manually changing to `"1.20"` naturally fixes this issue. This might not have been spotted due to not having a version ending in `0` since `1.10`. Opening this issue as I ran into this multiple times already and have seen several people being confused.

**Comment by RedNesto** [comment]
You're using an outdated version, this has been fixed already.
