### ISSUE TITLE
Outdated Create Project Wizard

### ISSUE THREAD

**Issue by GevaX** [DemonWav/MinecraftDevIntelliJ#2092]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.8

### IntelliJ version

IU-231.9392.1

### Operating System

Windows

### Target platform

Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

Outdated Create Project Wizard 
Dont showd all platoforms
![image](https://github.com/minecraft-dev/MinecraftDev/assets/138283789/d0842401-7621-4312-831e-f0e202b80a08)

**Comment by Earthcomputer** [comment]
What platform doesn't it show?

**Comment by GevaX** [comment]
paper

**Comment by Earthcomputer** [comment]
That's under the Bukkit menu.
