### ISSUE TITLE
I dont have 1.8.9 version :/

### ISSUE THREAD

**Issue by enjoden** [DemonWav/MinecraftDevIntelliJ#2095]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.9

### IntelliJ version

IC-232.8660.185

### Operating System

Windows

### Target platform

Minecraft Forge

### Additional description

Im slow today but why isnt there the forge version for 1.8.9? 11.15.1.2318.

**Comment by RedNesto** [comment]
Old versions aren't supported. See the first pinned issue.
