### ISSUE TITLE
Unable to download x versions

### ISSUE THREAD

**Issue by obvTiger** [DemonWav/MinecraftDevIntelliJ#2096]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.2

### IntelliJ version

IC-223.8214.52

### Operating System

Mac OS X

### Target platform

Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

While creating a new project it tells me when selecting the platform that it was unable to download x versions

**Comment by RedNesto** [comment]
Update the mcdev plugin and retry, you are using a version that is like 5 months old.
If it still doesn't work then something is preventing you from reaching 3 different sources we use to fetch available versions and we can't do much about it.
