### ISSUE TITLE
I want to start a minecraft plugin but i cant.

### ISSUE THREAD

**Issue by Crusiador** [DemonWav/MinecraftDevIntelliJ#2098]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.9

### IntelliJ version

IU-232.8660.185

### Operating System

Windows

### Target platform

Spigot

### Additional description

I have no idea

**Comment by Budgixous** [comment]
More details please. Say what isn't working and potentially attach a video showing what you are saying.
