### ISSUE TITLE
FountainAPI plugins

### ISSUE THREAD

**Issue by sgdc3** [DemonWav/MinecraftDevIntelliJ#21]
https://github.com/FountainMC/FountainAPI

**Comment by DemonWav** [comment]
It is too early to provide support for Fountain as things are so unstable and changing so drastically. Another issue is user base size, Fountain does not yet have a large enough user base for me to deem worth the effort of supporting it in the plugin. As I have the entire plugin to worry about, I want to focus on the large groups, as I'm sure you understand. If you or the Fountain team or someone else feels like PR'ing support for Fountain and maintaining Fountain support in the plugin I would be open to that.
