### ISSUE TITLE
Project don't creating

### ISSUE THREAD

**Issue by VkProfi** [DemonWav/MinecraftDevIntelliJ#2105]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.9

### IntelliJ version

2023.1

### Operating System

Windows 8.1

### Target platform

Fabric

### Description of the bug

When creating a project, a field with a name is highlighted, but there is no error. Even if leave undefined, the project will not be created. I tried with VPN, create on 2023.1 and 2022.2 version InteliJ, but it doesn't work. Everyone's friends have it, I don't.

**Comment by Mysterious-Dev** [comment]
Please update to 1.6.10

**Comment by OchotaDariusz** [comment]
Got same problem with updated plugin version to 1.6.10:

> ### Minecraft Development for IntelliJ plugin version
> 2023.2-1.6.10
> 
> ### IntelliJ version
> IU-232.8660.185
> 
> ### Operating System
> Windows
> 
> ### Target platform
> Spigot
>

**Comment by Mysterious-Dev** [comment]
Do you have any screenshots?

**Comment by OchotaDariusz** [comment]
> Do you have any screenshots?

After clicking "create" nothing happens. Only got focus on first text field `Name`. Tried other names and create folder before create project but still nothing.

![image](https://github.com/minecraft-dev/MinecraftDev/assets/98316845/c16adc32-4485-4aa4-9bbc-a5e207e35541)

**Comment by RedNesto** [comment]
I can clearly see the Group ID field highlighted in red, the creator won't let you use the default "placeholder" group.
It seems like the platform won't focus on the fields failing validation, don't know if we can do anything about it from the plugin.

**Comment by OchotaDariusz** [comment]
![image](https://github.com/minecraft-dev/MinecraftDev/assets/98316845/6f2b0fe1-5c4f-4af6-812a-c60c474630e0)

Oh... You're right @RedNesto. I didn't noticed that! Thanks! Now it works.

**Comment by traxonLp** [comment]
Hey, the issue remains for me. I got plugin Version 1.6.10
![image](https://github.com/minecraft-dev/MinecraftDev/assets/70008916/de07528a-863f-4f25-b510-8d226fbe03e8)

**Comment by RedNesto** [comment]
![image](https://github.com/minecraft-dev/MinecraftDev/assets/13600250/313e9748-3daf-43bc-8497-afbbdda15a46)

Your theme doesn't display the red highlight.
