### ISSUE TITLE
Cannot create Project

### ISSUE THREAD

**Issue by LukH-MC** [DemonWav/MinecraftDevIntelliJ#2108]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IU-232.8660.185

### Operating System

Windows

### Target platform

Spigot, Paper

### Additional description

I tried to create a new paper project, but clicking the create button does nothing. Also tried with spigot

**Comment by RedNesto** [comment]
See #2105
