### ISSUE TITLE
Please Get The 1.12.2 Back

### ISSUE THREAD

**Issue by Sarocesch** [DemonWav/MinecraftDevIntelliJ#2109]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### Description of the feature request

Somehow The Minecraft Forge 1.12.2 Disappeared During An Update And It Is A Big Problem For Me Is There An Old Version With Or A Possibility To Add It Again

**Comment by Sarocesch** [comment]
thanks for the quick reply but it was working a few months ago so I'm surprised it doesn't work anymore

**Comment by Sarocesch** [comment]
I wonder only in which version it was still I can not find itmehr they should know it or ?
would be nice if you get in touch

**Comment by RedNesto** [comment]
1.12.2 is no longer supported, if you find a version that still works good for you, but you won't get any help for versions this old here.

**Comment by DereC4** [comment]
Anyone know which version works? I'm trying to setup a sponge mod
