### ISSUE TITLE
Can't create a bukkit project in macOS

### ISSUE THREAD

**Issue by Birditch** [DemonWav/MinecraftDevIntelliJ#2110]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IU-232.8660.185

### Operating System

Mac OS X

### Target platform

Spigot

### Additional description

I cant create a bukkit project
nothing in the windows tips.

**Comment by RedNesto** [comment]
See See #2105

**Comment by Birditch** [comment]
> See See #2105

thanks,Based on this topic, I have solved it. Thank you for your help!
