### ISSUE TITLE
CANNOT CREATE NEW PROJECT

### ISSUE THREAD

**Issue by mativv3** [DemonWav/MinecraftDevIntelliJ#2111]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IC-232.8660.185

### Operating System

Windows

### Target platform

Spigot, Paper

### Additional description

Hi, I have a problem with Intellij when creating a new project, it returns me to the "name" field. Im using java 20.

**Comment by RedNesto** [comment]
See #2105
