### ISSUE TITLE
Breaking IDE lint behavior when plugin is enabled

### ISSUE THREAD

**Issue by SrRapero720** [DemonWav/MinecraftDevIntelliJ#2114]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IntelliJ IDEA 2023.2 (Community Edition) Build #IC-232.8660.185, built on July 25, 2023 Runtime version: 17.0.7+7-b1000.6 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10.0 GC: G1 Young Generation, G1 Old Generation Memory: 2048M Cores: 12 Registry:     ide.experimental.ui=true  Non-Bundled Plugins:     com.intellij.ideolog (222.1.0.0)     monokai-pro (1.10)     com.almightyalpaca.intellij.plugins.discord (1.11.0)     com.demonwav.minecraft-dev (2023.2-1.6.10)  Kotlin: 232-1.9.0-IJ8660.185

### Operating System

Windows 10

### Target platform

Minecraft Forge, Fabric

### Description of the bug

when plugin is enabled, lint behavior got broken, basically every "warning" never got removed/updated after code changes
you can see in next video how multiple warnings got stacked in 1 code line

this video show whats the issue, with plugin disabled all works fine, with plugin enabled everything got broken

https://github.com/minecraft-dev/MinecraftDev/assets/29090346/440c4b0a-ecca-4de1-829f-f9fd63a1d76c

## IN CASE WAS NECESARY
Repository of the proyect: https://github.com/SrRapero720/watermedia

**Comment by RedNesto** [comment]
I cannot reproduce it. No idea what could be going wrong here.

**Comment by SrRapero720** [comment]
i found what is causing it
my project was (before) a forge project (Minecraft), but i decide to mocked forge classes to add the capability to be more backwards compatible.

but i didn't remove Minecraft Facet from project structure

After removing facet all starts working fine
![image](https://github.com/minecraft-dev/MinecraftDev/assets/29090346/f47e8ebb-5eb7-4346-b2f1-b8d9720284cf)
