### ISSUE TITLE
Add DSL selection gradle

### ISSUE THREAD

**Issue by dd2x2** [DemonWav/MinecraftDevIntelliJ#2117]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### Description of the feature request

please, when choosing gradle, add the ability to choose between Groovy DSL and Kotlin DSL

**Comment by lucyydotp** [comment]
Duplicate of #1898?

**Comment by Tennessene** [comment]
I agree with this, but this is a duplicate of #687
