### ISSUE TITLE
Choosing a Fabric API Version doesn't get saved

### ISSUE THREAD

**Issue by MacStevins** [DemonWav/MinecraftDevIntelliJ#2118]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IC-232.8660.185

### Operating System

Linux

### Target platform

Fabric

### Additional description

In the `New Project` Window, the plugin makes you choose which versions of Minecraft, and Fabric Loader, Yarn, and it's API

![image](https://github.com/minecraft-dev/MinecraftDev/assets/15080111/8dcd0faa-f2a6-49fb-b83d-09774d790540)

But after processing the project, and looking at `gradle.properties` file, the `fabric_version` is different

![image](https://github.com/minecraft-dev/MinecraftDev/assets/15080111/3c0e4fa9-7c30-487a-b7dc-bf8cec8937fa)
<p style="text-align: center">This is after creating a dummy project, that came from the first screenshot</p>

**Comment by pog5** [comment]
Bump. Very annoying
