### ISSUE TITLE
unable to fetch fabric versions

### ISSUE THREAD

**Issue by trxshonzaza** [DemonWav/MinecraftDevIntelliJ#2123]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.9

### IntelliJ version

IC-232.8660.185

### Operating System

Windows

### Target platform

Fabric

### Additional description

![image](https://github.com/minecraft-dev/MinecraftDev/assets/89441166/c4e7043f-5aac-4ba4-acb2-71efce28892b)
this error keeps popping up when i try to make a fabric project

**Comment by RedNesto** [comment]
This is either an issue on your end, or fabric's or modrinth's API having issues at that time.
Just tested and the versions are downloaded correctly.

**Comment by trxshonzaza** [comment]
I reinstalled and it still doesnt work. Is there any other way i can fix
this?

**Comment by RedNesto** [comment]
I don't know, something likely prevents your IDE from reaching those URLs
- https://meta.fabricmc.net/v2/versions
- https://api.modrinth.com/v2/project/P7dR8mSH/version

**Comment by vacjan321** [comment]
I'm experiencing the same problem. The above urls work fine.
