### ISSUE TITLE
Spigot 1.20.2 is not available in wizard

### ISSUE THREAD

**Issue by Nevah5** [DemonWav/MinecraftDevIntelliJ#2132]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.10

### IntelliJ version

IU-231.9011.34

### Operating System

Windows

### Target platform

Spigot

### Additional description

Version 1.20.2 is not available in wizard

**Comment by RedNesto** [comment]
Thanks for the reminder, 1.20.2 has been added for spigot.
