### ISSUE TITLE
Impossible to create any project

### ISSUE THREAD

**Issue by ColonelGerdauf** [DemonWav/MinecraftDevIntelliJ#2140]
### Minecraft Development for IntelliJ plugin version

2023-1.6.10

### IntelliJ version

2023.2.2

### Operating System

Windows 10 - 20H2

### Target platform

Minecraft Forge

### Description of the bug

I am at my wits end with this plugin.

I update all I can, I check for any problematic setting. But even now, after I updated everything, I cannot hit the "create" button. When I hit the button, the focus jumps to the main title, even when it has been left as default. Changing from Forge to Fabric to Architectury to Paper does nothing to prevent the problem. Changing JDK does nothing, and neither does any of the Minecraft parameters.

All I have as a cause is the plugin maybe struggling to read the correct EOL in the title, or is reading something that does not exist and cannot compute that.

**Comment by RedNesto** [comment]
Have you set a proper version and group id in the Build System Properties section ?

**Comment by ColonelGerdauf** [comment]
Okay, so it is indeed Group ID.

This will be very awkward for people who have no plans to do anything fancy, and simply jump into mod dev.
What can be done to make this less awkward and frustrating for people hopping into this plugin?

I have my own suggestions:
- mark "Group ID" as important
- have Group ID match system username (and skip if it is a real name), as an initial default
- when the project creation fails, move the focus to the Group ID textbox instead of project name

**Comment by RedNesto** [comment]
We've already had 2 or 3 reports about the same issue, I cannot really see what we can improve on our end.

> mark "Group ID" as important

Not sure how we'd do that ?

> have Group ID match system username (and skip if it is a real name), as an initial default

Good luck judging what's a "real name" and what's not. And what if it is detected as a real name ? We'd still have the same issue

> when the project creation fails, move the focus to the Group ID textbox instead of project name

I couldn't find a way to do it on our end, I'd say this is a platform issue, they simply don't focus the problematic text field when validation fails and instead go to the first one in the panel.

**Comment by ColonelGerdauf** [comment]
> Not sure how we'd do that ?

What I have as an idea, and I don't know how viable this is, is to have a red star-character before the "Group ID" text without changing header or textbox position, with a hover text explaining that it should not be left to default. Have the star removed when the title is changed from the default provided by the plugin. 

If this somehow works, this can also be used as an indicator when a build fails.

**Comment by RedNesto** [comment]
I think the initial problem here is that people don't even know this section exists in the first place.
Maybe an additional red text placed as high as we can when validation fails in one of those fields ?

**Comment by ColonelGerdauf** [comment]
That would be nice, to explain why the project is not created. Having nothing but the highlighted main text will confuse people into hunting for the red herrings. People may not be initially aware of what "Group ID" is, or what role it plays in the structure of Minecraft mods.

**Comment by ColonelGerdauf** [comment]
Also when i say to "skip when a real name is used" I was focusing on firstname+lastname system that Windows used to have. Nowadays, People enter their usernames. If that ends up being the "real name", then that is outside the purview of the check, and is no longer your job to check and verify.
