### ISSUE TITLE
MinecraftDev's "New Project" Interface is EXTREMELY Laggy

### ISSUE THREAD

**Issue by TechnicallyCoded** [DemonWav/MinecraftDevIntelliJ#2141]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

2023.2.2

### Operating System

MacOS 13.3.1

### Target platform

Bukkit, Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, Mixins, BungeeCord, Waterfall

### Description of the bug

The interface for creating a new project is extremely slow and lags out the whole UI. Changing the type of project creation, makes it return to working perfectly normal. The issue is very likely directly caused by the MinecraftDev addon.

Screen recording of this happening below as I switch back and forth between Minecraft (1 fps) and whatever else (which doesn't lag at all):

https://github.com/minecraft-dev/MinecraftDev/assets/29813490/951d6763-58b5-480a-b81e-c3bfe5daa992

**Comment by RedNesto** [comment]
This is very likely due to the fact we have a lot of fields that are pre-filled and updated based on the project name, where the other example you provided doesn't have any.

Also I just tested and it isn't nearly as bad on my end.

**Comment by TechnicallyCoded** [comment]
Updating 4-5 text fields is unlikely to require 500ms-1000ms of processing no matter the circumstance.

**Comment by DenWav** [comment]
I have experienced this a number of times myself. We really aren't doing anything crazy, all is the APIs we're using to build the UI are JetBrains, but we should look to find out if there's something we're doing that's slowing it down.
