### ISSUE TITLE
Can't create new Minecraft Projects

### ISSUE THREAD

**Issue by Fadro04** [DemonWav/MinecraftDevIntelliJ#2144]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.9

### IntelliJ version

IU-222.4345.14

### Operating System

Windows 10

### Target platform

Spigot

### Additional description

When I want to create a new Minecraft Project for a spigot Plugin, it does nothing. The only thing that happen is that the input field for the name of the project is selected, no error or something like that.
![Screenshot](https://github.com/minecraft-dev/MinecraftDev/assets/91956823/97f6142b-3378-4c37-afb9-890ca2089d52)

**Comment by RedNesto** [comment]
Change the group ID to something else.

Also 2022.2 is unsupported now.
