### ISSUE TITLE
Gradle & Loom update

### ISSUE THREAD

**Issue by xanthian** [DemonWav/MinecraftDevIntelliJ#2147]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IC-232.10072.27

### Operating System

Windows

### Target platform

Fabric

### Additional description

    id 'fabric-loom' version '1.4-SNAPSHOT'
    gradle wrapper should be on 8.3 also

**Comment by xanthian** [comment]
heres the official fabric template
gradle 8.3
https://github.com/FabricMC/fabric-example-mod/blob/1.20/gradle/wrapper/gradle-wrapper.properties
loom 1.4
https://github.com/FabricMC/fabric-example-mod/blob/1.20/build.gradle

**Comment by nightpool** [comment]
This is really important! I ran into a lot of weird and hard to debug errors when using old loom versions

**Comment by RedNesto** [comment]
I'll do template updates soon as it hasn't been done in a while, thanks for reminding me.
