### ISSUE TITLE
Windows project move to macOS then NO JDK Specified.

### ISSUE THREAD

**Issue by Sam-Chai** [DemonWav/MinecraftDevIntelliJ#2151]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IntelliJ IDEA 2023.2.3 (Community Edition)

### Operating System

macOS Ventura & Windows 11

### Target platform

Fabric

### Description of the bug

I push my fabric mod project from windows pc to GitHub (use GitHub Desktop), and use my macOS laptop to fork them, then I using macOS IDEA 2023.2.3 to open my project. Everything worked. But when I try to use IDEA run (Minecraft Client) to start a Minecraft instance, then back me a error:
```
Error: Could not find or load main class net.fabricmc.devlaunchinjector.Main
Caused by: java.lang.ClassNotFoundException: net.fabricmc.devlaunchinjector.Main
```
And I try to config my "-cp" argument from `XXXProject.main` to `my.domain.XXXProject.main`, then the error gose done.
But when I rerun Minecraft Client, then brings me a crash-report:
```
Description: Initializing game

java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.check(EventLoop.java:33)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1078)
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:75)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:847)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:491)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

```
And then, I add this JVM arg, then Minecraft started. But I can't press any Minecraft TitleScreen button and even no background image and music.
Ofcourse, my mod don't load anymore.

However, when I try to run gradle's runClient and runServer, all works great. Please solve this problem!!!

**Comment by Budgixous** [comment]
Minecraft launches with many JVM arguments so perhaps try researching what they are. But what is the issue of using gradle's runClient? You are meant to use it to launch your mod while testing.

**Comment by Sam-Chai** [comment]
> Minecraft launches with many JVM arguments so perhaps try researching what they are. But what is the issue of using gradle's runClient? You are meant to use it to launch your mod while testing.

well, I solved. The mac use Unix file format(like /User/Minecraft/...), but windows use C:\xxx.
Here's the problem. When I trans the platform from windows to mac, I copy the gradle and .idea folder to mac, and the idea and mcdev didn't match the windows location format.
By the way, I don't use runClient from gradle. I use mvdev provides Minecraft Client idea script to lanuch client instance. the runClient don't have this problem, but the script is.
Is there any way to let mcdev scan the system env auto and try to fix such as location problem automaticlly?

**Comment by DenWav** [comment]
Mcdev just uses IntelliJ's config APIs, so handling that would be up to Jetbrains.
