### ISSUE TITLE
Outdated project wizard

### ISSUE THREAD

**Issue by edy131109** [DemonWav/MinecraftDevIntelliJ#2172]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.11

### IntelliJ version

IC-231.9161.38

### Operating System

Windows

### Target platform

Paper

### Additional description

Can't see the paper platform in the options.

**Comment by RedNesto** [comment]
Select Plugin -> Bukkit -> Paper

**Comment by edy131109** [comment]
Thanks @RedNesto
