### ISSUE TITLE
I18n support stopped working

### ISSUE THREAD

**Issue by phoenix-the-uncreative** [DemonWav/MinecraftDevIntelliJ#2173]
### Minecraft Development for IntelliJ plugin version

1.6.11

### IntelliJ version

2023.2.5

### Operating System

Windows 11

### Target platform

Minecraft Forge

### Description of the bug

Previously, when I called to `I18n#format`, the plugin would notify me if I used a key that does not exist and I could easily add it to the language file from the context menu.

Since 1.6.11, this doesn't work: I can't go to existing keys with ctrl+click, calls to `I18n#format` are no longer folded into the English translation and I can only create new keys when I write a string and manually select it to use the context menu action "Convert string literal to translation".

I've rolled back to 1.6.10 and it works again.

**Comment by RedNesto** [comment]
We changed how I18n methods are identified by the plugin, it now uses a custom annotation and we use external annotations to attach it to existing known classes, looks like some were missed during the migration.

If someone wishes to contribute missing methods here is [an example](https://github.com/minecraft-dev/MinecraftDev/blob/dev/externalAnnotations/net/minecraft/client/resource/language/annotations.xml)

You can add them locally in your project too using the appropriate intention in the editor.

**Comment by Earthcomputer** [comment]
You didn't specify which Minecraft version you were using, but I didn't include MCP mappings during the migration, so it might be that.

**Comment by phoenix-the-uncreative** [comment]
> You didn't specify which Minecraft version you were using, but I didn't include MCP mappings during the migration, so it might be that.

That might be it, yeah. I'm using 1.16.5 with MCP mappings.

**Comment by phoenix-the-uncreative** [comment]
I added the annotations myself, #2197
