### ISSUE TITLE
I can't create a project

### ISSUE THREAD

**Issue by Nerd10000** [DemonWav/MinecraftDevIntelliJ#2175]
### Minecraft Development for IntelliJ plugin version

2023.2-1.6.10

### IntelliJ version

IC-232.8660.185

### Operating System

Windows

### Target platform

Spigot

### Additional description

I do everything right and I click to create but it does nothing.
![image](https://github.com/minecraft-dev/MinecraftDev/assets/96385928/b5090a84-f7f7-44d6-80dd-3a170c0774ee)

**Comment by RedNesto** [comment]
The version should follow semantic versioning.
