### ISSUE TITLE
JDK not selecting

### ISSUE THREAD

**Issue by FinGymPlayz** [DemonWav/MinecraftDevIntelliJ#2176]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.9

### IntelliJ version

IC-222.3345.118

### Operating System

Windows 11

### Target platform

Spigot

### Additional description

![image](https://github.com/minecraft-dev/MinecraftDev/assets/85786554/08ac995b-0ae0-4f3b-9eb7-d4b9a3f4d8de)
Not selecting what so ever, broken Intelij

**Comment by RedNesto** [comment]
That's likely because you don't have any compatible JDK installed (or recognized by IDEA)

Also the version of IDEA you're using is really outdated, we dropped support for 2022.2 a while ago.
