### ISSUE TITLE
IntelliJ Freezes When Plugin Attempts to Read NBT

### ISSUE THREAD

**Issue by PeTcHeNkA** [DemonWav/MinecraftDevIntelliJ#2177]
### Minecraft Development for IntelliJ plugin version

2023.3-1.6.11-434

### IntelliJ version

IntelliJ IDEA 2023.3 (Ultimate Edition)

### Operating System

Windows 10

### Target platform

Minecraft Forge

### Description of the bug

**IntelliJ appears to freeze during the “File system synchronization” process. 
This issue seems to occur when new world (DIMENSION) folders are created in the Minecraft directory. 
The application becomes unresponsive, disrupting workflow and productivity. 
Here is the stack trace associated with this error:**

[threadDump-20231207-150009.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602585/threadDump-20231207-150009.txt)
[threadDump-20231207-150014.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602586/threadDump-20231207-150014.txt)
[threadDump-20231207-150019.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602587/threadDump-20231207-150019.txt)
[threadDump-20231207-150024.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602588/threadDump-20231207-150024.txt)
[threadDump-20231207-150029.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602589/threadDump-20231207-150029.txt)
[threadDump-20231207-150034.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602590/threadDump-20231207-150034.txt)
[threadDump-20231207-150039.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602591/threadDump-20231207-150039.txt)
[threadDump-20231207-150044.txt](https://github.com/minecraft-dev/MinecraftDev/files/13602592/threadDump-20231207-150044.txt)

**Comment by RedNesto** [comment]
Should be fixed by 93f5b9e4002f37b3534552d9a13d26a47a6e7286
