### ISSUE TITLE
The generate menu cannot pop up.

### ISSUE THREAD

**Issue by XXY233** [DemonWav/MinecraftDevIntelliJ#2178]
### Minecraft Development for IntelliJ plugin version

2023.3-1.6.11

### IntelliJ version

IntelliJ IDEA 2023.3 (Ultimate Edition)

### Operating System

Windows 11

### Target platform

Spigot

### Description of the bug

When the "MinecraftDev" plug-in is enabled, IDEA's code generation function cannot be used, and the menu does not pop up after clicking it.
![d7b80695980b780a57bd779a259712b4](https://github.com/minecraft-dev/MinecraftDev/assets/46647646/bb39458f-de39-48bc-a5f9-1c978ab3dcd1)
![15c52baf6ca744de65c8f631e5670eaf](https://github.com/minecraft-dev/MinecraftDev/assets/46647646/9fe006db-fe16-40a6-997e-1e491f7639a0)

When the "MinecraftDev" plug-in is disabled, IDEA will pop up a menu:
![0c77be7a02a0e911baf5f49dd6da739e](https://github.com/minecraft-dev/MinecraftDev/assets/46647646/9ee6226b-b6ee-473c-9cdf-a15bc63d7b6e)

**Comment by RedNesto** [comment]
This should be already fixed in the nightly channel.

**Comment by XXY233** [comment]
Can confirm it has been fixed :)
