### ISSUE TITLE
Project Wizard Outdated

### ISSUE THREAD

**Issue by TreemTG** [DemonWav/MinecraftDevIntelliJ#2187]
### Minecraft Development for IntelliJ plugin version

Minecraft_Development-2023.3-1.6.12

### IntelliJ version

IntelliJ IDEA 2023.3.2 (Community Edition)

### Operating System

Windows 11

### Target platform

Spigot, Paper, Sponge, Architectury, Minecraft Forge, Fabric, Velocity, BungeeCord, Waterfall

### Additional description

When I try Creating a project the project wizard isn't right. The plugin doesn't change the UI.

**Comment by Tennessene** [comment]
Uh, that isn't very specific... If you tell us exactly what you expect and what you're seeing, we might be able to help better

**Comment by TreemTG** [comment]
Well when I trey creating a new minecraft plugin project it doesn't show me
the menu that I am supposed to see.

**Comment by Earthcomputer** [comment]
What menu are you supposed to see?
