### ISSUE TITLE
Outdated Loom/Gradle version used in 1.20.4 fabric

### ISSUE THREAD

**Issue by Phoenix616** [DemonWav/MinecraftDevIntelliJ#2208]
See issue with nightly [here](https://github.com/minecraft-dev/MinecraftDev/issues/2208#issuecomment-1894214706).

### Minecraft Development for IntelliJ plugin version

2023.2.2-1.6.12

### IntelliJ version

2023.2.5 (Ultimate Edition) Build #IU-232.10227.8

### Operating System

Windows 10 (22H2)

### Target platform

Fabric

### Additional description

When creating a new fabric project with latest (1.20.4, see screenshot) it will generate with loom `1.2-SNAPSHOT` and gradle 8.1.1 which do not work for that version.

![image](https://github.com/minecraft-dev/MinecraftDev/assets/5768781/b64c2f93-237e-40c7-8c0f-4f010ea54537)

**Comment by RedNesto** [comment]
The creator has already been updated to use 1.4-SNAPSHOT in the nightly builds along with a bunch of other template updates.
Can you switch to the nightly channel and see if it works correctly?

**Comment by Phoenix616** [comment]
That seems to indeed work correctly, thanks.

I tried to take a look at the commits before and didn't see anything obvious pointing towards this being updated but I don't really know much about the structure of this project so didn't know in which files to look for the versions.

**Comment by Phoenix616** [comment]
Actually it seems that I was a bit too fast with closing this after it went further than before :S 

Loom version `1.4-SNAPSHOT` seems to also cause issues which loom `1.5-SNAPSHOT` did not cause (using plugin version `2023.2.2-1.6.12-443` now):

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 265 ms

> Configure project :
Fabric Loom: 1.4.6

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'FabricTestTest'.
> This version of loom does not support the mixin remap type value. Please update to the latest version of loom.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 12s
```

**Comment by RedNesto** [comment]
Don't worry, the loom version is hardcoded here https://github.com/minecraft-dev/MinecraftDev/blob/59677b86ece5864084819bbbe3c616636e9d37f8/src/main/kotlin/platform/fabric/creator/gradle-steps.kt#L60

Not the most obvious place I reckon.

And I'm pretty sure the gradle version is currently the default one, defined here https://github.com/minecraft-dev/MinecraftDev/blob/59677b86ece5864084819bbbe3c616636e9d37f8/src/main/kotlin/creator/buildsystem/gradle-steps.kt#L64
