### ISSUE TITLE
Get Mixin target reference not showing

### ISSUE THREAD

**Issue by Kat-09** [DemonWav/MinecraftDevIntelliJ#2212]
### Minecraft Development for IntelliJ plugin version

2024.3-1.6.12

### IntelliJ version

2023.3.2

### Operating System

EndeavourOS (Arch Based)

### Target platform

Forge 1.18.2

### Description of the bug

when i right click on a method, "Get Mixin target reference" does not appear.

**Comment by RedNesto** [comment]
The plugin version you're using is made for the 2024.1 EAP but you're using 2023.3.2.

**Comment by Kat-09** [comment]
nvm it was bc it wasn't just right click and then get mixin target reference, it was under a second menu (aswell as incorrect version but it works for me on the older version so yeah)
