### ISSUE TITLE
Support latest intellij idea EAP

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#2213]
### Minecraft Development for IntelliJ plugin version

N/A

### Description of the feature request

Its not showing in the plugin marketplace for latest EAP intellij version (the one that is installed if you use toolbox)

**Comment by RedNesto** [comment]
It is, switch to the nightly channel

**Comment by ghost** [comment]
How do I do that? Nightly channel for the plugin or intellij?

**Comment by RedNesto** [comment]
For the plugin, instructions are here: https://mcdev.io/install/

If you cannot install the plugin simply go to the plugins settings -> cog -> Manage Plugin Repositories and then add `https://plugins.jetbrains.com/plugins/Nightly/8327` to the urls list.
