### ISSUE TITLE
Eu não consigo baixar a jdk 1.8

### ISSUE THREAD

**Issue by kevynpaiva22** [DemonWav/MinecraftDevIntelliJ#2215]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.0

### IntelliJ version

IC-233.13135.103

### Operating System

Windows

### Target platform

Spigot

### Additional description

não aparece minha jdk, quero aprender a fazer plugin, porém não aparece a jdk 1.8 antiga azul zulu

**Comment by Earthcomputer** [comment]
English only please. This is not a problem with the plugin.
