### ISSUE TITLE
Allow viewing/generation of method descriptors for access wideners

### ISSUE THREAD

**Issue by ApionXD** [DemonWav/MinecraftDevIntelliJ#2222]
### Minecraft Development for IntelliJ plugin version

2023.2.2-1.7.1

### Description of the feature request

It would be insanely nice if there was a way to easily obtain a method descriptors for use in access wideners. For instance the one below sets the access of the constructor in `net.minecraft.entity.ai.brain.sensor.SensorType` to public. The constructor takes a java.util.Supplier as a parameter. 

Its possible to have access wideners for classes and fields too, would be nice to have those included.

`transitive-accessible method net/minecraft/entity/ai/brain/sensor/SensorType <init> (Ljava/util/function/Supplier;)V`

[Fabric Docs on Access Wideners](https://fabricmc.net/wiki/tutorial:accesswideners)

**Comment by RedNesto** [comment]
You can already do that
![image](https://github.com/minecraft-dev/MinecraftDev/assets/13600250/8cc0efcb-6369-4472-95b6-a2716436125a)
