### ISSUE TITLE
build.gradle and settings.gradle inconsistencies

### ISSUE THREAD

**Issue by ItzEkans** [DemonWav/MinecraftDevIntelliJ#2223]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.1

### IntelliJ version

2023.3.3

### Operating System

Windows 10

### Target platform

Minecraft Forge

### Description of the bug

There seems to be a forge version inconsistency in the build.gradle and settings.gradle files that are automatically generated when a new project is made. This is the error I get: "Could not resolve dependency: net.minecraftforge:forge:1.19.2-49.0.27:userdev"

I experience this when creating a 1.19.2 project with forge version 43.3.7.

**Comment by RedNesto** [comment]
Oh yeah this is an issue with the saved selected versions, it will use the forge version for the latest mc version instead of the saved mc version one.

Make sure to reselect the forge version in that case.

**Comment by ItzEkans** [comment]
Ah, I didn't realize I had to reselect it. Thanks!
