### ISSUE TITLE
Forge mods.toml 'since version' checks don't work for non-generated projects

### ISSUE THREAD

**Issue by PaintNinja** [DemonWav/MinecraftDevIntelliJ#2237]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.2

### IntelliJ version

2023.3.4

### Operating System

Windows 11

### Target platform

Minecraft Forge

### Description of the bug

If I generate a new 1.17.1 project using the plugin and try adding `displayTest` to the mods.toml, I get an error saying that it is not available in the version I'm using.

If I download the official Forge 1.17.1 MDK, extract the zip, wait for it to import and try adding `displayTest` to the mods.toml, the error is missing.

**Comment by RedNesto** [comment]
This is because the MDK is using FG5 and we have no support for it in the Gradle tooling extension.

I don't think it's worth fixing.
