### ISSUE TITLE
does not recognize NEW <class descriptor> injection points as valid

### ISSUE THREAD

**Issue by tildejustin** [DemonWav/MinecraftDevIntelliJ#2240]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.2-466

### IntelliJ version

2023.3.4 (Ultimate Edition)

### Operating System

EndeavorOS Linux, kernel 6.7.5-arch1-1

### Target platform

Mixins

### Description of the bug

mcdev looks like it does not recognize `NEW` targets as valid when the target signature is a class descriptor instead of a ctor.

this is legal according to the mixin javadoc (https://jenkins.liteloader.com/view/Other/job/Mixin/javadoc/org/spongepowered/asm/mixin/injection/points/BeforeNew.html), but mcdev "Cannot resolve target reference" when this feature is used.

obligatory screenshots:
![image](https://github.com/minecraft-dev/MinecraftDev/assets/66330094/be5fe174-ee8c-4d8b-b296-a6fa4a02b44b)
![image](https://github.com/minecraft-dev/MinecraftDev/assets/66330094/e3797596-8ca2-4f1b-88ac-74274ab23eb9)

**Comment by Earthcomputer** [comment]
This is already fixed in nightly

**Comment by Earthcomputer** [comment]
Apparently it wasn't, thanks RedNesto!
