### ISSUE TITLE
Occasional random freezes in IntelliJ

### ISSUE THREAD

**Issue by embeddedt** [DemonWav/MinecraftDevIntelliJ#2242]
### Minecraft Development for IntelliJ plugin version

1.7.0

### IntelliJ version

2023.3.3

### Operating System

Linux

### Target platform

Minecraft Forge

### Description of the bug

I've been experiencing occasional random freezes in IntelliJ for some time. These got annoying enough that I decided to try to investigate the problem next time it occured, and today I reproduced it and was able to capture the stacktrace of all running threads. I notice that two threads (`AWT-EventQueue-0` and `DefaultDispatcher-worker-8`) appear to be blocked with MinecraftDev code near the top of the stacktrace, and wondered if this might possibly be a race condition in the plugin. If this is not a MinecraftDev issue, feel free to close. I've attached the stacktrace I was able to capture below.

I have no idea exactly what the necessary steps are to trigger this bug, however, I seem to notice it most often when opening another project.

[intellij.txt](https://github.com/minecraft-dev/MinecraftDev/files/14390308/intellij.txt)

**Comment by RedNesto** [comment]
Your version of the plugin is outdated, try 1.7.2, I made changes related to the code freezing the UI since then.
