### ISSUE TITLE
This version of loom does not support the mixin remap type value. Please update to the latest version of loom.

### ISSUE THREAD

**Issue by Hloredea** [DemonWav/MinecraftDevIntelliJ#2243]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.9

### IntelliJ version

IC-222.4167.29

### Operating System

Windows 11

### Target platform

Fabric

### Additional description

![Screenshot 2024-02-25 162622](https://github.com/minecraft-dev/MinecraftDev/assets/105223323/e0fe4d2e-8064-499e-8dda-a6fd03398698)

What a heil I must to do???????????????

**Comment by Gaming32** [comment]
You must update to Loom 1.5 or later. You're currently on 1.2.8, which is pretty old.

**Comment by RedNesto** [comment]
You're using an outdated version of mcdev, you should upgrade to a newer intellij version too.

**Comment by Hloredea** [comment]
it saying like needs gradle 8.3, then this again
