### ISSUE TITLE
无法选择JDK

### ISSUE THREAD

**Issue by yishiwuchu** [DemonWav/MinecraftDevIntelliJ#2246]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.12

### IntelliJ version

2023.1

### Operating System

window11

### Target platform

Bukkit

### Description of the bug

IDEA2023.1版本中无法选择我已经下载好的JDK1.8。
请不要怀疑我的技术问题：
1.我已经安装JDK
2.我安装的JDK可以运行SpringBoot项目和TomCat项目、分布式项目
3.我已经配置好了JDK中环境变量HOME
4.你们IDEA插件无法识别到我的JDK

**Comment by zyklone4096** [comment]
![image](https://github.com/minecraft-dev/MinecraftDev/assets/62649962/ac07a73c-4b66-4288-9f66-a0683d270f83)

**Comment by Earthcomputer** [comment]
Issues in English only please.
