### ISSUE TITLE
Can't Create New Project

### ISSUE THREAD

**Issue by GoodyTaube** [DemonWav/MinecraftDevIntelliJ#2247]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.3

### IntelliJ version

IC-233.14475.28

### Operating System

Windows

### Target platform

Paper

### Additional description

Can't Create Project.
Clicking on "Create" Force me to Enter Field "Name:" but there is already a Name.

**Comment by Lytiy74** [comment]
Change the group ID
