### ISSUE TITLE
[Minor] Maximum pack-format for resourcepacks outdated

### ISSUE THREAD

**Issue by LunaticWasTaken** [DemonWav/MinecraftDevIntelliJ#2256]
### Minecraft Development for IntelliJ plugin version

2023-1.7.3

### IntelliJ version

2023.3.4

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

The Maximum pack-format for resourcepacks is outdated, saying the max format was "18", which is from 1.20.2, while we're now far higher (22 for 1.20.4, or 28 for latest snapshot)
![image](https://github.com/minecraft-dev/MinecraftDev/assets/80840951/90531dfc-bdb7-441a-8483-c7268948a79e)

**Comment by RedNesto** [comment]
The schema is not from the plugin but from schemastore: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/minecraft-pack-mcmeta.json
