### ISSUE TITLE
plugin:minecraft development

### ISSUE THREAD

**Issue by syumai2367** [DemonWav/MinecraftDevIntelliJ#2269]
### Minecraft Development for IntelliJ plugin version

2023.3-1.7.3

### IntelliJ version

IC-233.15026.9

### Operating System

Windows

### Target platform

Minecraft Forge

### Additional description

I cannot use java8 (1.8)
The JDK part is 21 and I cannot select 1.12.2
From the default new project I can use java8 (1.8)

**Comment by RedNesto** [comment]
1.12.2 support has been dropped along time ago
