### ISSUE TITLE
Gradle and Loom versions are outdated

### ISSUE THREAD

**Issue by lapadapdap** [DemonWav/MinecraftDevIntelliJ#2283]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.12

### IntelliJ version

Runtime version: 17.0.7+10-b829.16 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

When creating a new project, the Loom version listed in `build.gradle` and the Gradle version listed in `gradle-wrapper.properties` are out of date. This creates build errors when the project is initially indexing and building.

I've found that changing them like so fixes all issues:

- Change line 2 in `build.gradle` to: `id 'fabric-loom' version '1.6-SNAPSHOT'`
- Change line 1 in `gradle-wrapper.properties` to: `distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip`

I'd make a pull request myself, but I'm not sure where in the codebase these things are edited, so I've opted to make an issue instead.

Thanks!

**Comment by RedNesto** [comment]
You're using a version from december, and we dropped 2023.1 support recently.

Upgrade your IDE to a newer major version and you'll get the latest plugin updates, which uses a newer loom version by default.

**Comment by lapadapdap** [comment]
This made me realise a lot of my IDEs are outdated because Jetbrains Toolbox or something was stopping updates from appearing in the IDE. Sorry for wasting your time.
