### ISSUE TITLE
spigot

### ISSUE THREAD

**Issue by bhholuuu** [DemonWav/MinecraftDevIntelliJ#2286]
### Minecraft Development for IntelliJ plugin version

2024.1-17.4

### Description of the feature request

 how can i select spigot in minecraft projrct ? 

![3](https://github.com/minecraft-dev/MinecraftDev/assets/148367167/c48a3df1-3b46-47f1-8d88-a4788f1fbaa4)
![2](https://github.com/minecraft-dev/MinecraftDev/assets/148367167/7e90071f-6baa-4e6e-9c65-7b7a2a8d5316)

in youtube video, they show to select spigot,
but i dont have that option

**Comment by RedNesto** [comment]
The video is outdated, the wizard UI got updated a year ago.

If you want to use Spigot select the Bukkit option, it covers both Spigot and Paper as a separate option.
