### ISSUE TITLE
Java 17 recommended for 1.20.5

### ISSUE THREAD

**Issue by arnokeesman** [DemonWav/MinecraftDevIntelliJ#2288]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.4

### IntelliJ version

#IU-241.14494.240

### Operating System

Windows 10

### Target platform

Fabric

### Additional description

Java version 17 is recommended for Minecraft 1.20.5
![image](https://github.com/minecraft-dev/MinecraftDev/assets/34793978/c5651897-9ad2-4cf7-9bcc-c7eb48e7a4c8)

**Comment by RedNesto** [comment]
This is fixed in 1.7.5
