### ISSUE TITLE
Support 1.20.6

### ISSUE THREAD

**Issue by minamikana-git** [DemonWav/MinecraftDevIntelliJ#2291]
### Minecraft Development for IntelliJ plugin version

latest

### Description of the feature request

Currently, Minecraft 1.20.4 is supported up to 1.20.6, but now that 1.20.6 of PaperMC has been released, 1.20.6 should be supported as well.

**Comment by RedNesto** [comment]
Paper 1.20.6 builds are experimental, I'd rather wait until it becomes stable before including them in the creator.

**Comment by Onako2** [comment]
It is better that people begin already now to migrate their plugins to 1.20.5/1.20.6 than in a few days/weeks

**Comment by RedNesto** [comment]
We don't need to do anything else for supporting 1.20.6 AFAIK, only the creator needs to be aware of the new version.

**Comment by John-Development** [comment]
Might be unrelated, but fabric mixins also seems broken in 1.20.6, the plugin cant find any `@Inject` method that were working in previous versions.

![imagen](https://github.com/minecraft-dev/MinecraftDev/assets/38006800/cbdc7ca4-8aeb-4fb5-948c-d95231762d99)

**Comment by LlamaLad7** [comment]
Update IDEA

**Comment by John-Development** [comment]
Such a derp... thanks, that fixed the issue!
