### ISSUE TITLE
1.20.6 mixins doesn't work

### ISSUE THREAD

**Issue by Olafcio1** [DemonWav/MinecraftDevIntelliJ#2299]
### Minecraft Development for IntelliJ plugin version

newer,  I  was updating today like 5h ago

### IntelliJ version

2023.4 community

### Operating System

windows 10 22h2

### Target platform

Fabric

### Description of the bug

mixins just doesn't work. @Inject `method` field doesn't allow any  value ,for example I can't inject at HEAD of getWindowTitle function,  in class   that mixins  net.minecraft.client.MinecraftClient.class. cancellable false, empty function, public  void.  this  happens both in intellij idea and when building.

i did everything good, cuz **the same code** works  on 1.20.5, title  changes. i   heard   that   it's a bug  of this plugin,so reported it here. idk if  it really  is, but my  keyboard also didn't like it,  thats why this desc  is  so   weirdly typed lol. idk if it  was already reported anywhere,prob   it was

**Comment by doodlechaos** [comment]
I can confirm I'm having the same bug as well. Any strings in @Inject are unable to be resolved and stuck as red.

**Comment by RedNesto** [comment]
There's no 2023.4 version of Idea, and we need to know the exact version of the plugin you're using, latest doesn't mean anything.

**Comment by doodlechaos** [comment]
![image](https://github.com/minecraft-dev/MinecraftDev/assets/22280498/59f30fe1-6776-4c9a-8c4e-0f75c1226cee)

minecraft-dev 2022.2-1.6.9

![image](https://github.com/minecraft-dev/MinecraftDev/assets/22280498/4d5006e6-a63f-47ba-855b-4a7eb8653c29)

The red text says unresolved, but it works when I build the game.

**Comment by Earthcomputer** [comment]
We dropped support for 2022.2 almost a year ago. Please update.

**Comment by doodlechaos** [comment]
Updated Intellij to 2024.1.2 and everything works great now. Thanks!
