### ISSUE TITLE
Add Options for automatically using Paper PluginBootstraps and -Loaders when selecting to use paper manifest

### ISSUE THREAD

**Issue by Hinterhaeltiger** [DemonWav/MinecraftDevIntelliJ#2301]
### Minecraft Development for IntelliJ plugin version

1.3.2

### Description of the feature request

When you create a plugin, it would be nice to have an option to automatically generate a PluginBootstrap and/or PluginLoader class.

**Comment by RedNesto** [comment]
I don't want to bloat the templates with niche stuff, it's easy enough to add them manually anyway and the templates can be customized in the new creator.
