### ISSUE TITLE
Add NeoForge

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#2302]
### Minecraft Development for IntelliJ plugin version

2022.3-1.5.21

### Description of the feature request

Please add the mod loader NeoForge. The MDK is located at [https://github.com/neoforged/MDK](url)

**Comment by RedNesto** [comment]
Update your IDE and plugin version.

**Comment by ghost** [comment]
I did, and the option the NeoForge still isn't there.

**Comment by RedNesto** [comment]
What version of IDEA and the plugin are you using now?

**Comment by ghost** [comment]
Just noticed, the IDE is outdated. I don't know why it didn't just update to the latest version, but I can do that now.

**Comment by ghost** [comment]
I have finished the updates, and it works now.
