### ISSUE TITLE
Multiple Project support

### ISSUE THREAD

**Issue by PhoenixOrigin** [DemonWav/MinecraftDevIntelliJ#2309]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.5

### Description of the feature request

It would be great if there was multiproject support, I was trying to setup a project with multiple subprojects and there wasn't any in built way to do it and if there was it would be great.

**Comment by Earthcomputer** [comment]
There is multiple subproject support, so I assume you are talking about the creator. In that case it's works as intended. There is a balance between code and UI complexity and how much the creator can do for you. If you need to make a complicated project, you can always change the project structure after using the creator, not use the creator and import the project afterwards, or, if you have to do this often, make your own template.
