### ISSUE TITLE
Java 17 shouldn't be suggested for 1.21

### ISSUE THREAD

**Issue by KekeCreations** [DemonWav/MinecraftDevIntelliJ#2315]
### Minecraft Development for IntelliJ plugin version

2023.1-1.6.10

### IntelliJ version

IC-231.9392.1

### Operating System

Windows

### Target platform

Architectury, Minecraft Forge, Fabric

### Additional description

Minecraft moved to Java 21 for 1.21, so that version should be suggested instead of 17
![image](https://github.com/minecraft-dev/MinecraftDev/assets/89083260/1ab632c2-0be7-450f-b3a1-bcf5f9ed5a3c)

**Comment by RedNesto** [comment]
Update both IDEA and the plugin
