### ISSUE TITLE
I am trying to make a 1.16.5 addon mod 

### ISSUE THREAD

**Issue by Zenoable** [DemonWav/MinecraftDevIntelliJ#2318]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.11

### IntelliJ version

IC-223.8214.52

### Operating System

Windows 11

### Target platform

Minecraft Forge

### Additional description

I am trying to make an addon mod for a mod called **mineminenomi** but when i getnerate all the file before i add anything there is no runClient, i have been trying to find a fix for months with no luck and found out about this page, i dont know if it is for support but i would love it if you could maybe tell me what i am doing wrong (forge 1.16.5, forge 36.2.34 , mod , java 8 1.8.202 ).

**Comment by RedNesto** [comment]
You are using outdated versions of IDEA and the plugin, update both to the latest version and it should be working fine.
