### ISSUE TITLE
Minecraft development not installing in intellij idea

### ISSUE THREAD

**Issue by SirMrNecron** [DemonWav/MinecraftDevIntelliJ#2319]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.6

### IntelliJ version

IntelliJ IDEA 2024.1.1 (Community Edition)

### Operating System

Windows 10

### Description of the bug

Hi I have a problem about installing minecraft development plugin , I CANT INSTALL IT , i think problem is plugin not intellij bc i can download other plugins (or maybe the problem was my intellij idk) but anyways maybe some1 had my problem , when i press install intellij says This : 
"
Plugin Installation
Plugin "Minecraft Development" was not installed: We are sorry, but we are currently unable to provide our products or services to you due to export control regulations.
"
any1 know what i should do to fix This ?? :))
![PROBLEM](https://github.com/minecraft-dev/MinecraftDev/assets/173687134/5f9dfb9c-d489-4f93-b4bc-cc3f460d9bb0)

**Comment by RedNesto** [comment]
I'm not sure why it would only happen with mcdev.

You can always download and update the plugin manually from the [GitHub Releases](https://github.com/minecraft-dev/MinecraftDev/releases/tag/1.7.6-2024.1).

**Comment by SirMrNecron** [comment]
Yes i try downloading plugin from zip file but it says the error again

در تاریخ دوشنبه ۲۴ ژوئن ۲۰۲۴،‏ ۱۸:۲۰ RedNesto ***@***.***>
نوشت:

**Comment by DenWav** [comment]
What country are you in? Will see if we can ask Jetbrains what's going on.

**Comment by SirMrNecron** [comment]
Germany

در تاریخ دوشنبه ۲۴ ژوئن ۲۰۲۴،‏ ۲۰:۰۸ Kyle Wood ***@***.***>
نوشت:
