### ISSUE TITLE
Analysis not completing on 1.20.1 Forge mod

### ISSUE THREAD

**Issue by OmegaRogue** [DemonWav/MinecraftDevIntelliJ#2320]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.6

### IntelliJ version

2024.1.4

### Operating System

Arch Linux

### Target platform

Minecraft Forge

### Description of the bug

After opening a java file in a minecraft forge mod project generated by this plugin, the inspection status in the top right corner of the editor shows "Analyzing..." and doesn't seem to get any further than that, Code inspections don't seem to be available

**Comment by Earthcomputer** [comment]
This is an IntelliJ bug, not a MinecraftDev bug.

**Comment by OmegaRogue** [comment]
Is there a known solution to this intellij bug?
