### ISSUE TITLE
Trying to Create new Project

### ISSUE THREAD

**Issue by SniffieFTW** [DemonWav/MinecraftDevIntelliJ#2326]
### Minecraft Development for IntelliJ plugin version

2022.3-1.6.11

### IntelliJ version

IC-223.7571.182

### Operating System

Windows 11

### Target platform

Spigot

### Additional description

I'm trying to create a new plugin through the Minecraft plugin in IntelliJ, but every time i try to create a new project and click create, its refreshes the screen and doesn't open up the new project.

https://github.com/minecraft-dev/MinecraftDev/assets/29559319/ccda6e46-34b3-4238-8196-1ceb21880e90

**Comment by RedNesto** [comment]
You have to change the "Group ID" value to something else.

Also you are using an outdated version of IDEA and the plugin, you should update both.
