### ISSUE TITLE
Linux: Cant Change the JDK on Project Creation

### ISSUE THREAD

**Issue by NopeImNotHere** [DemonWav/MinecraftDevIntelliJ#2329]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.6

### IntelliJ version

2024.1.2 #IC-241.17011.79

### Operating System

Arch Linux x86_64

### Target platform

Minecraft Forge

### Description of the bug

When trying to create a new Project and trying to choose another JDK in the Dropdown, instead of changing it to the selected JDK, it just removes it from the List. 
Dropdown in Question
![Untiteld](https://github.com/user-attachments/assets/901a4a91-6530-4329-99f3-24ffa31bc8cb)

Does not seem to be an IntelliJ Issue as later in the Project Settings Menu JDK can be changed without Issue
AMA if you need more Info about my System

**Comment by NopeImNotHere** [comment]
Was able to create a Video to further Explain my Issue
https://github.com/user-attachments/assets/fdc40c47-5e60-48f3-9a9a-212b3c4151a5

**Comment by RedNesto** [comment]
That is because Minecraft 1.21 is selected, and it requires using Java 21
