### ISSUE TITLE
Cannot analyze stacktrace

### ISSUE THREAD

**Issue by maxanier** [DemonWav/MinecraftDevIntelliJ#233]
I recently noticed the awesome unscramble stacktrace feature ( #199 ). Unfortunately I am not able to get it to work.

If I select `Analyze -> Analyze Stacktrace`, select unscramble stacktrace with "Remap SRG names" and paste a crash report (e.g. your example one https://pastebin.com/raw/GXSFwvmh) nothing happens when I hit OK.
(When using another unscrambler something happens).

I have checked the standard idea.log file, but could not find anything relevant. Is there another log file?

Setup:
IntelliJ IDEA 2017.1.4 Ultimate
Minecraft Development 2017.1-0.7.2
ModProject with Forge 1.11.2-13.20.0.2228 
Kubuntu 16.04

Log File: https://paste.ee/p/Ixx8K

Please let me know if you need any further information

**Comment by stephan-gh** [comment]
It should open a window like this one if you hit OK. Maybe try a Gradle refresh and make sure you're in a MCP project. It won't work if MCDev doesn't have any mappings.

![screenshot_20170609_110734](https://user-images.githubusercontent.com/3035868/26968862-ee6c3efa-4d03-11e7-918d-0d6f3a1fed2a.png)

**Comment by maxanier** [comment]
Thx, my project has a little Forge icon added so I suppose it is recognized as Forge project (which should include the MCP mappings, doesn't it?) 
**Edit**: Just checked the "Module Types" in the project settings and the project is recognized as Forge and MCP.

However my project (gradle) setup is not exactly like the Forge tutorial one, so maybe some things are not recognized correctly.
I will try another setup.
May I suggest adding some kind of error message if the mappings are not found and hitting the 'OK' button? (As long as this is not to complicated)

**Comment by maxanier** [comment]
I've modified my project to work exactly like the one in cpw's Forge MDK example video, but it still can't find the mappings.
If I create a project using the plugin's creation dialog, everything works fine.

Is there a way to manually specify the mappings location?

**Comment by maxanier** [comment]
I've simply copied the mcp mapping locations from the working project module's .iml to my projects .iml file.
It works now, but it is not a very nice way.

**Comment by stephan-gh** [comment]
Do you have an example project where it is not working in automatically?

**Comment by maxanier** [comment]
https://github.com/TeamLapen/Vampirism

What I did: 
   - Use `New Project from Version Control`  
 - Click `Import Gradle`or similar when IntelliJ offers it (after clone)  
 - Select `Create directories for empty content roots` and __deselect__ `Create seperate module per source set`
 - Run the `setupDecompWorkspace` task (with -Xmx4g -Xms4g)  
 - Refresh the gradle project  
 - Try to analyze stacktrace or to get SRG name

**Comment by stephan-gh** [comment]
I think it's because you import the project before you run `setupDecompWorkspace`. Usually it's better to clone the project on the command line, run `setupDecompWorkspace` and then import it into IntelliJ IDEA because otherwise you will first import an incomplete project.

In your example project, it works for me if I make a minor modification to the Gradle build script (e.g. add a new dependency) and refresh the Gradle project again.

**Comment by maxanier** [comment]
Alright, thank you very much. Then I will do it the other way around from now on. 
No real need to fix this (unless it is a simple fix), although mentioning this in the documentation would be helpful then
