### ISSUE TITLE
Wrong default velocity plugin class

### ISSUE THREAD

**Issue by SeemWind** [DemonWav/MinecraftDevIntelliJ#2330]
### Minecraft Development for IntelliJ plugin version

1.8.0

### IntelliJ version

2024.1

### Operating System

windows11

### Target platform

Velocity

### Description of the bug

```
@Plugin(
        id = "huskchatbridge",
        name = "HuskChatBridge",
        version = "1.0-SNAPSHOT")
    ,description ="a plugin to send message"
        ,authors ={"likewind"}
        )

```
generate wrong default code, bracket is not right

**Comment by RedNesto** [comment]
The code is fine, but for some reason the formatter doesn't fix this bad formatting.
