### ISSUE TITLE
NBT viewer doesn't work on .dat files

### ISSUE THREAD

**Issue by TehNut** [DemonWav/MinecraftDevIntelliJ#234]
Many NBT files are stored as a `.dat` instead of `.nbt` (`level.dat` for example)

**Comment by JBYoshi** [comment]
Also handle [`.mca`](http://minecraft.gamepedia.com/Anvil_file_format) files (they're pieces of NBT save data in Minecraft worlds) - those should be pretty easy to detect, as all `mca` files are NBT, while `dat` is just a generic extension. Support for [`.mcr`](http://minecraft.gamepedia.com/Region_file_format) (also NBT) would work, but may not be useful; it was superseded in 2012.

**Comment by Niko-sk2x** [comment]
IIRC `.mca` files differ from `.mcr` only with the NBT inside, so if it works with mca, it would work with mcr.

**Comment by DenWav** [comment]
All of these can be added manually.

`.dat` isn't handled due to how generic it is. It would be easy to check if a file is an NBT file, so I'll consider it.

**Comment by DenWav** [comment]
Fixed in a538dc7.
