### ISSUE TITLE
Velocity plugin BuildConstants.kt required and suggested!

### ISSUE THREAD

**Issue by RTAkland** [DemonWav/MinecraftDevIntelliJ#2341]
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.0-498

### Description of the feature request

When choosing the project development language, choose kotlin, but BuildConstants is still .java, so I recommend a template file using kt

```kotlin
object BuildConstant {
    const val VERSION = "<%= version %>"
}
```

Pure kotlin!

**Comment by Earthcomputer** [comment]
You can PR any missing templates to https://github.com/minecraft-dev/templates
