### ISSUE TITLE
Add an IDE inspection error for mixin and target type mismatches

### ISSUE THREAD

**Issue by O7410** [DemonWav/MinecraftDevIntelliJ#2343]
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.0

### Description of the feature request

Currently, when the mixin is an interface and the target is a class, there is no IDE error, but there is a compile error that says:
`Targetted type 'net.minecraft.block.Block of mypackage.mixin.BlockMixin is not an interface`
When the mixin is a class and the target is an interface, there is a runtime error that says
`@Mixin target type mismatch: net.minecraft.text.Text is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@75769ab0`
This is the behavior i want:
![image](https://github.com/user-attachments/assets/11d94d16-2d53-480a-96f4-80acccf2bb29)
![image](https://github.com/user-attachments/assets/b1cc9118-e586-428b-a5f9-f443226449cd)

This is low priority since it's very easy to see what the problem is when you try to run it (the compile and runtime errors)

**Comment by O7410** [comment]
should also mention i used fabric with yarn mappings to test

**Comment by Earthcomputer** [comment]
How did you get those screenshots? Did you make this inspection yourself already?

**Comment by O7410** [comment]
Yeah i wrote some horrible code
you can look at it here https://github.com/O7410/MinecraftDev/commit/2de6199d8d4a3b9cca49d3bae181d14e42f63966
