### ISSUE TITLE
Update didn't work!

### ISSUE THREAD

**Issue by DRD2k8** [DemonWav/MinecraftDevIntelliJ#2355]
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.0

### IntelliJ version

2024.1.3

### Operating System

IDK

### Target platform

Architectury

### Description of the bug

So, I updated the plugin to the latest version, it failed to update! And then the plugin uninstalls itself! Why is this happening!?

**Comment by RedNesto** [comment]
This is very likely an IDE bug, you can simply reinstall the plugin.

**Comment by kikugie** [comment]
I second this. The error is 
```
Please try again, and if the problem persists, please report it
to https://jb.gg/ide/critical-startup-errors

The cause: java.nio.file.FileSystemException: C:\Users\KikuGie\AppData\Roaming\JetBrains\IntelliJIdea2024.1\plugins\Minecraft Development\lib\MinecraftDev-2024.1-1.8.0-503-gradle-tooling-extension.jar: The process cannot access the file because it is being used by another process
```
Strangely this occurs if I try to uninstall the plugin as well, in which case it rolls back.

**Comment by RedNesto** [comment]
Make sure to kill all Gradle processes before updating/uninstalling the plugin.

**Comment by kikugie** [comment]
`./gradlew --stop` doesn't work for it

**Comment by kikugie** [comment]
![image](https://github.com/user-attachments/assets/20345f1a-05f2-47e3-bbe7-3f106113dfb3)
Even deleting the folder manually after closing the IDE doesn't work (only for mcdev) - which is concerning

**Comment by RedNesto** [comment]
Yes, kill all running java processes

**Comment by kikugie** [comment]
Why does it keep running in the background though?

**Comment by RedNesto** [comment]
Good question
