### ISSUE TITLE
BSOD Crash

### ISSUE THREAD

**Issue by AzaleaCatgirl99** [DemonWav/MinecraftDevIntelliJ#2361]
### Minecraft Development for IntelliJ plugin version

Latest

### IntelliJ version

Latest

### Operating System

Windows 11

### Target platform

Architectury, Minecraft Forge, Fabric, Mixins

### Description of the bug

Randomly out of nowhere (usually when trying to build) my PC will get a BSOD from Intellij Idea. This was not happening before I updated the plugin a few days ago.

Sadly I am unable to figure out what BSOD crash it was because the screen shows up only for a second before my PC restarts.

**Comment by Earthcomputer** [comment]
Unrealted to mcdev
