### ISSUE TITLE
Methods Implementing Interfaces in Mixins are Required to be Named in Mixin Style

### ISSUE THREAD

**Issue by Taskeren** [DemonWav/MinecraftDevIntelliJ#2364]
### Minecraft Development for IntelliJ plugin version

2024.2-1.8.1

### IntelliJ version

2024.2.0.2

### Operating System

Windows 11

### Target platform

Mixins

### Description of the bug

![image](https://github.com/user-attachments/assets/7c78794d-1ebd-4f59-b212-2704a4607be3)

`getSomeString` is defined in the custom interface `ISomeInterface`, which is used for Interface Injection.

It should not be regulated by the naming style.

**Comment by LlamaLad7** [comment]
Yes, it should be regulated by the naming style. The entire point is that using simple names will cause conflicts between mods. Both the name in your interface and in your mixin need to be prefixed.

**Comment by Taskeren** [comment]
> Yes, it should be regulated by the naming style. The entire point is that using simple names will cause conflicts between mods. Both the name in your interface and in your mixin need to be prefixed.

Sorry, I'm not very good at Mixin. How can I make the implement methods naming in that style without errors? Is that `@Implementation` annotation? I don't see any document about Mixin use it.

**Comment by LlamaLad7** [comment]
> Both the name in your interface and in your mixin need to be prefixed.

**Comment by LlamaLad7** [comment]
You put your modid or similar in front of their names.

**Comment by Taskeren** [comment]
But what if the interface is not MY custom one, but in other dependencies?

**Comment by Earthcomputer** [comment]
It's likely not advisable to implement interfaces from other dependencies into Minecraft classes, in case other mods try to do the same thing. If you are having this problem a lot, you can go into the settings for this inspection and disable the option for inherited methods.

**Comment by Taskeren** [comment]
Thanks for answering! I see the recommended way to do this.

But can it be inspected separately, like have different options for methods from interface and methods injecting?
