### ISSUE TITLE
The "target" content is incomplete

### ISSUE THREAD

**Issue by Crystal0404** [DemonWav/MinecraftDevIntelliJ#2370]
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.1

### IntelliJ version

IntelliJ IDEA 2024.1.5 (Community Edition) Build #IC-241.18968.26, built on August 4, 2024 Runtime version: 17.0.11+1-b1207.30 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 11.0 GC: G1 Young Generation, G1 Old Generation Memory: 2048M Cores: 20 Registry:   ide.experimental.ui=true Non-Bundled Plugins:   com.intellij.zh (241.271)   com.demonwav.minecraft-dev (2024.1-1.8.1)   cn.yiiguxing.plugin.translate (3.6.4) Kotlin: 241.18968.26-IJ

### Operating System

Windows11 23H2 22631.4037

### Target platform

Mixins

### Description of the bug

I'm trying to aim at this line of code in the diagram(Fabric Yarn 24w36a+build.4)
![image](https://github.com/user-attachments/assets/cdcac992-d150-44ab-822b-8b8e02943a45)

But MCDEV generates the wrong arguments
![image](https://github.com/user-attachments/assets/e31a0d10-0e7a-4070-a6fa-5715bcaf530d)

In fact, the correct parameter should be `Lnet/minecraft/world/TeleportTarget;<init>(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;FFLjava/util/Set;Lnet/minecraft/world/TeleportTarget$PostDimensionTransition;)V`

Thank you for developing this amazing plugin!

**Comment by RedNesto** [comment]
Can't reproduce, do you observe any error in the bottom right corner of the window after generating the target?

**Comment by Crystal0404** [comment]
I updated my IntelliJ last night and now it's working fine

```
IntelliJ IDEA 2024.2.3 (Community Edition)
Build #IC-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.demonwav.minecraft-dev (2024.2-1.8.1)
  cn.yiiguxing.plugin.translate (3.6.5)
Kotlin: 242.23339.11-IJ
```
