### ISSUE TITLE
Access Transformers not working in 1.21 NeoForge

### ISSUE THREAD

**Issue by SaltSouls** [DemonWav/MinecraftDevIntelliJ#2374]
### Minecraft Development for IntelliJ plugin version

2024.2-1.8.1

### IntelliJ version

2024.2.1

### Operating System

Manjaro Linux x86_64

### Target platform

NeoForge

### Description of the bug

When using ATs, the IDE will complain about the method still being protected/private despite the AT being there and having the proper method call. This is preventing any kind of building/running of the program, and despite my best efforts, I can't find a single way to force the IDE to recognize my ATs and make the appropriate changes.

**Comment by RedNesto** [comment]
Make sure you're using mojang names, the plugin is not aware of them on NeoForge yet but this will be implemented soon

**Comment by SaltSouls** [comment]
> Make sure you're using mojang names, the plugin is not aware of them on NeoForge yet but this will be implemented soon

How can I tell if I am? I'm currently using parchment for the mappings, so I'm not sure if that is messing with the names of any of the methods.

**Comment by RedNesto** [comment]
mojang names are actual names, SRG names are mostly numbers. And I mean as field and method names in your AT file.
