### ISSUE TITLE
Can't create new NeoForge Project

### ISSUE THREAD

**Issue by stevengreens10** [DemonWav/MinecraftDevIntelliJ#2382]
### Minecraft Development for IntelliJ plugin version

2024.1-1.8.1

### IntelliJ version

2024.2.3

### Operating System

Windows 11

### Target platform

NeoForge

### Description of the bug

Whenever I try to create a NeoForge project, I get an error saying "Version must be a valid semantic version" despite it being valid, and the GUI can no longer scroll all the way down. I can only scroll down to the optional settings. If I switch the project type back to Forge, I can create the project without any issues.

Before attempting to create:
![image](https://github.com/user-attachments/assets/14956cbe-3705-48ad-bc23-9beb1cd87083)

After attempting to create:
![image](https://github.com/user-attachments/assets/f7ba74d1-d6e2-4639-8ef6-affd4a2ea14d)

**Comment by RedNesto** [comment]
As a workaround, under Optional Settings check `Include older Minecraft versions` and select the latest version available.
