### ISSUE TITLE
Creating a new project fails

### ISSUE THREAD

**Issue by iseal56** [DemonWav/MinecraftDevIntelliJ#2394]
### Minecraft Development for IntelliJ plugin version

v2 2.1.4.242

### IntelliJ version

IntelliJ IDEA Ultimate 2024.3 (243.21565.193)

### Operating System

Zorin OS 17.2 x86_64

### Target platform

Spigot

### Description of the bug

[gist](https://gist.github.com/iseal56/3d0af0724c86a73de658b60109f5aca8) with the stacktrace

Steps to reproduce:
1. Go to File -> New -> Project
2. Select Minecraft
3. Select: Plugin, Spigot, Maven, Java, 1.19.4, JDK 21
4. Click create
5. Sometimes it crashes and sends an error message, without creating the project. Sometimes it throws the error, but makes the project anyway

**Comment by iseal56** [comment]
Update: Group ID and Project ID have been changed from defaults. 
Thats not the issue

**Comment by RedNesto** [comment]
The plugin version doesn't match our versioning scheme, but by the looks of it you're using the 2024.2 version on IJ 2024.3, this might be an issue.

**Comment by iseal56** [comment]
The v2 is to say Discord Integration V2, probably should have made that more obvious. the actual version is after that (or at least the one idea reports).
I have the latest version intellij gives me, is there any updated version i can download?

**Comment by RedNesto** [comment]
All versions are available there: https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions.

I was able to reproduce the error, will look into it whenever I get the time.
