### ISSUE TITLE
Launching files

### ISSUE THREAD

**Issue by ilikeminecraft22** [DemonWav/MinecraftDevIntelliJ#2398]
### Minecraft Development for IntelliJ plugin version

2024.2-1.8.2

### IntelliJ version

2024.2.4

### Operating System

Windows 11 Pro Education 23H2

### Target platform

Spigot, Paper

### Description of the bug

![obraz_2024-11-21_183242255](https://github.com/user-attachments/assets/9ba0f112-1eff-4e6f-b043-e820bdf27b32)
When i try to run, build files it randomly just doesn't let me and says: This file is unrunnable i tried to fix it by running it in Grade, but it's just the same thing over and over. No matter if i put something in those 2 main functions it just doesn't let me.

**Comment by ilikeminecraft22** [comment]
Gradle*

**Comment by RedNesto** [comment]
You need to select a run configuration first, you likely want to run the `build` gradle task, which can be found in the Gradle toolwindow.

**Comment by ilikeminecraft22** [comment]
> You need to select a run configuration first, you likely want to run the `build` gradle task, which can be found in the Gradle toolwindow.

Thank you so much that i don't have to spend the 3rd day searching through **Google** trying to find some help. It worked perfectly.
