### ISSUE TITLE
Add Quilt mod template

### ISSUE THREAD

**Issue by xdoxx123** [DemonWav/MinecraftDevIntelliJ#2401]
### Minecraft Development for IntelliJ plugin version

2024.2-1.8.2

### Description of the feature request

Add a quilt mod template since its a **PAIN** to use a default
it would be just a good add since quilt is growing

**Comment by Earthcomputer** [comment]
#1827 please search before creating new issues

**Comment by xdoxx123** [comment]
Okay but it still isnt done??

**Comment by Earthcomputer** [comment]
Please, use the other issue
