### ISSUE TITLE
Material with item stack issue

### ISSUE THREAD

**Issue by Snowbeast138** [DemonWav/MinecraftDevIntelliJ#2405]
### Minecraft Development for IntelliJ plugin version

2022.2-1.6.1

### IntelliJ version

IC-222.4459.24

### Operating System

Windows 10

### Target platform

Spigot

### Additional description

I create a default plugin, and when i want to make a ItemStack and add the Material, this one can reconize that Class
![image](https://github.com/user-attachments/assets/eda117ef-7b0c-4fc1-8903-cd179c5293d4)
I try to implement it but it refuese

**Comment by Earthcomputer** [comment]
This is not an issue with the MinecraftDev plugin
