### ISSUE TITLE
External translation annotations are no longer attached on latest intellij

### ISSUE THREAD

**Issue by Earthcomputer** [DemonWav/MinecraftDevIntelliJ#2408]
### Minecraft Development for IntelliJ plugin version

2024.3-1.8.2-532

### IntelliJ version

IU-243.21565.193

### Operating System

Linux

### Target platform

Fabric

### Description of the bug

MinecraftDev is supposed to attach external annotations to Minecraft, so that e.g. `Component.translatable` has the `@Translatable` annotation on its parameter, but it doesn't seem to be doing that anymore on the latest intellij version

**Comment by RedNesto** [comment]
I believe the issue is that the Gradle option `Download external annotations for dependencies` is disabled by default. Turning it on should bring the external annotations back.
