### ISSUE TITLE
Minecraft Fabric mod setup not loading!

### ISSUE THREAD

**Issue by TheDangerDuck** [DemonWav/MinecraftDevIntelliJ#2413]
### Minecraft Development for IntelliJ plugin version

2024.2-1.8.2

### IntelliJ version

2024.2.0.2

### Operating System

Windows 11

### Target platform

Fabric

### Description of the bug

![image](https://github.com/user-attachments/assets/367effbb-59ea-420b-b339-ac2443034f0b)

The versions of the Fabric setup are not loading.
(red circle)

**Comment by Earthcomputer** [comment]
It gets the Fabric version from Modrinth, which is currently down. You can check its status here: https://status.modrinth.com/

**Comment by TheDangerDuck** [comment]
Thank you!
