### ISSUE TITLE
The plugin stopped working

### ISSUE THREAD

**Issue by 7byLoper** [DemonWav/MinecraftDevIntelliJ#2415]
### Minecraft Development for IntelliJ plugin version

2024.1-1.7.1

### IntelliJ version

IC-241.15989.150

### Operating System

Windows

### Target platform

Spigot, Paper, Sponge

### Additional description

![Screenshot_13](https://github.com/user-attachments/assets/88f5a956-5748-46f2-91b1-c85d8bc53996)
Hi, I recently reinstalled IDEA and downloaded the plugin for it. There used to be the spigot platform and paper, but now they are not there, and even when I open the creation menu, I have a sponge loading and when I close the menu, IDEA crashes

**Comment by Earthcomputer** [comment]
> I recently reinstalled IDEA and downloaded the plugin for it

I don't know why your intellij and mcdev versions are so out of date then.

**Comment by 7byLoper** [comment]
When I downloaded the latest version of intellij and mcdev, the problem remained unresolved
