### ISSUE TITLE
Kotlin Mixin completion

### ISSUE THREAD

**Issue by Seggan** [DemonWav/MinecraftDevIntelliJ#2418]
### Minecraft Development for IntelliJ plugin version

2024.3-1.8.2

### Description of the feature request

Support mixin completion in Kotlin mixins. I have created a [plugin](https://github.com/Seggan/kmixin) that generates Java wrappers around Kotlin mixin files, and it would be really nice to have completions and stuff when working in this environment. [Here](https://github.com/Seggan/deathview/blob/master/src/client/kotlin/io/github/seggan/deathview/client/mixin/GameRendererMixin.kt) is a specific example, and [this](https://github.com/Seggan/deathview/tree/master/src/client/kotlin/io/github/seggan/deathview/client/mixin) is a folderful of them.

**Comment by Earthcomputer** [comment]
See #1974.
In fact, writing mixins in Kotlin is such bad practice that mcdev is supposed to generate a warning when you have a Kotlin mixin. Are you not seeing this warning?

**Comment by Seggan** [comment]
> See #1974.
> In fact, writing mixins in Kotlin is such bad practice that mcdev is supposed to generate a warning when you have a Kotlin mixin. Are you not seeing this warning?

In fact I did. However, if you read my post, you will have read that I have a Gradle plugin to automatically generate Java wrappers around the Kotlin code (so I'm not actually doing any Kotlin mixin, the Java forwards to the Kotlin).

**Comment by Earthcomputer** [comment]
Sorry, but I don't think it's worth investing our time to support such an esoteric setup. If your Gradle plugin becomes popular then we may reconsider.

**Comment by Seggan** [comment]
Would you accept it if I PR'ed this?
