### ISSUE TITLE
Add Gradle compileOnly support.

### ISSUE THREAD

**Issue by mishyy** [DemonWav/MinecraftDevIntelliJ#246]
Due to some issues I have come across with another Gradle plugin, I now have to use the `compileOnly` scope for the Bukkit/Paper APIs (Haven't tested with any others as I do not use them right now) instead of the default `compile`.

As a result of this MinecraftDev no longer shows the icon pertaining to my API type in the top left of the project view, implying that MinecraftDev no longer acknowledges my plugin as a Minecraft plugin.

For those we have no idea what I mean:

Default:
```gradle
dependencies {
    compile 'org.bukkit:bukkit:1.11.2-R0.1-SNAPSHOT'
}
```
CompileOnly:
```gradle
dependencies {
    compileOnly 'org.bukkit:bukkit:1.11.2-R0.1-SNAPSHOT'
}
```

**Comment by DenWav** [comment]
Yes you're right it should be `compileOnly`.

**Comment by stephan-gh** [comment]
Confirmed for Bukkit, but for some reason it works for SpongeAPI. (At least for one of my projects, not for all XD)

**Comment by stephan-gh** [comment]
Well, it definitely re-appears after I close the project and open it again. So as far as I can see, `compileOnly` works fine.

**Comment by DenWav** [comment]
Oh I completely misunderstood this issue, I though this was stating the `build.gradle` templates should use `compileOnly`, which they should. I don't see how this would cause an issue though, with the current system.
