### ISSUE TITLE
[Sponge] Default java template seems bloated

### ISSUE THREAD

**Issue by Redrield** [DemonWav/MinecraftDevIntelliJ#256]
The default .java file template for Sponge plugins seems fairly bloated in its contents. As opposed to default plugin templates for the other server platforms, the sponge template has a listener for player joining, and comments that seem to be trying to tutor people in the absolute basics of the API. It would be a lot less annoying when creating a new sponge plugin to have a template more like the Bukkit templates, with onServerStart declared, and with a logger field. So more like this:

```java
package <package>

import ...

@Plugin(id = <id>, name = <name>)
public class <PluginName> {
    @Inject
    private Logger logger;

    @Listener
    public void onServerStart(GameStartedServerEvent event) {
        this.logger.info("Hello World!");
    }
}
```

**Comment by gabizou** [comment]
I remember making the tutorial bits a checkbox when I first introduced it. Not sure if it was removed or not.

**Comment by DenWav** [comment]
@gabizou it only toggles Javadocs.
