### ISSUE TITLE
Where is the fucking Support for MCP ?

### ISSUE THREAD

**Issue by flawnn** [DemonWav/MinecraftDevIntelliJ#274]
PLEASE GIVE IT TO US, I AM FUCKED UP WITH MANUALLY CONFIGURING IT

**Comment by DenWav** [comment]
What the fuck even is this issue.

**Comment by kashike** [comment]
![what](https://media.giphy.com/media/oQ6P5nknXM40w/giphy.gif)

**Comment by MarkTwoFive** [comment]
We don't have to know what this is about apparently ¯\\_(ツ)_/¯

**Comment by loordgek** [comment]
i got it he wants the directly edit the minecaft jar
and that is not supported but you can use mixin for this (sad face, no MCDEV project template for it, hint hint @DemonWav )

**Comment by flawnn** [comment]
Yep that i want

Am 21.07.2017 9:37 nachm. schrieb "loordgek" <notifications@github.com>:

**Comment by loordgek** [comment]
why ??????? and why not use forge ??

**Comment by kashike** [comment]
![no](http://s2.quickmeme.com/img/48/483ef0911f5e27073a015b45aee7a288b9c8d3bfa104f8bfe6625572f97cfa52.jpg)

**Comment by flawnn** [comment]
And how lol, i want to make an standalone Minecrat Jar, like labymod....

**Comment by flawnn** [comment]
If there is an Solution, say it to me, maybe i can Build it in to the jar,
labymod makes it also like this

**Comment by Dockter** [comment]
Thats a nice decompiled version of Minecraft I see in your repo library.  Mojang assets and a decompiled version of Optifine too.

You've gone full retard.  You should never go full retard.

**Comment by loordgek** [comment]
https://twitter.com/stefan10709629/status/888475775636320256

**Comment by kashike** [comment]
![bye](https://media0.giphy.com/media/i67uIY4a61ejm/giphy.gif)
