### ISSUE TITLE
Methods with client-side parameter should warn about needing to be client-side

### ISSUE THREAD

**Issue by mezz** [DemonWav/MinecraftDevIntelliJ#285]
Found another edge case for the sided static analysis.
`ITooltipFlag` is client-side only, I added some tooltips methods like `public void getTooltip(Tooltip tooltip, ITooltipFlag tooltipFlag)`, and I didn't get a warning telling me the method needs to be client-side.
Thanks again for the plugin!

**Comment by DenWav** [comment]
Good point, hadn't thought of parameters before. Should sideness be inferred from parameters, or should it always be explicit?

**Comment by mezz** [comment]
I think ideally things should be inferred as much as possible. I don't like explicitly marking things as client-only except when necessary, because it can get in the way during porting when mojang or forge changes the sidedness of something.

**Comment by DenWav** [comment]
Perhaps I could develop a "reason" system for inferred sideedness. I could see a system like this being very powerful, actually. This would also make error messages much clearer as it could explain _why_ something was inferred. This will take quite a bit of work to implement, however.
