### ISSUE TITLE
can't find minecraft version

### ISSUE THREAD

**Issue by SacredAI** [DemonWav/MinecraftDevIntelliJ#289]
So when ever I try to make a project with the plugin it can't seem to find my minecraft version

please help?

**Comment by kashike** [comment]
What version of Minecraft can it not find?

**Comment by SacredAI** [comment]
it can't find any

**Comment by kashike** [comment]
Elaborate. IntelliJ IDEA version? Plugin version? etc

**Comment by SacredAI** [comment]
My idea version is Intellij IDEA Ultimate 2017.2.2 and I havn't made a plugin minecraft Development is the latest version and it can't find any minecraft versions when I select it to create a project

**Comment by DenWav** [comment]
https://minecraftdev.org/docs/create.html

**Comment by SacredAI** [comment]
that dosn't help
