### ISSUE TITLE
Forge/Spongeforge combo doesn't load sponge when running test server in dev enviroment

### ISSUE THREAD

**Issue by Evolht** [DemonWav/MinecraftDevIntelliJ#291]
As the title states, I'm having trouble testing my sponge/forge combo plugin in the dev environment. I can build it and test on a server, but that means I can't debug in environment. Am I doing something wrong?

**Comment by JBYoshi** [comment]
Could you post the error?

**Comment by Evolht** [comment]
There isn't an error, because the run configuration doesn't start sponge with the server. Sorry I wasn't clearer. That was the issue I was having. I need forge to load the spongeforge mod for a fresh project when I try to run. Have I somehow set up my project incorrectly?

**Comment by DenWav** [comment]
How did you set up your project?

**Comment by Evolht** [comment]
File > New > Project...
[MinecraftPlugin]

Then ticked forge mod and sponge plugin.
https://puu.sh/xkDYb/2302e5f32b.png

Then chose "A single plugin which uses both the sponge and foge api's"

From there I filled in my build settings and continued till it finalised

**Comment by Evolht** [comment]
This is my current build.gradle file, in case it helps
https://gist.github.com/anonymous/10862807cf6f0b2946c736182d947b73

**Comment by loordgek** [comment]
dont use spongecommon use spongeforge

**Comment by DenWav** [comment]
Yes this looks like a problem with your build configuration. In either case that build.gradle is not generated by MCDev, it was modified. While MCDev is a plugin specific for Minecraft mod development in IntelliJ, it's not MCDev's responsibility to reimplement standard IDE tasks which IntelliJ already provides. Hence in this case, it's only a configuration issue and not a problem with MCDev, as far as I can tell.

**Comment by Evolht** [comment]
Hi again, sorry if I wasn't clearer. Am I wrong in thinking that a default project with both sponge and forge selected should mean that the server should start up a forge server with the sponge plugin installed as part of that? I understand that you all used to use spongestart, but it's no longer part of the default set up. 

Here's my setup, step by step:
![image](https://user-images.githubusercontent.com/3460315/30678781-e068c1ca-9ee8-11e7-8ece-da782e4575e6.png)
![image](https://user-images.githubusercontent.com/3460315/30678799-008df448-9ee9-11e7-8e7f-5751bd28b0f2.png)
![image](https://user-images.githubusercontent.com/3460315/30678824-1cf3838c-9ee9-11e7-91b3-bfd919a5700d.png)
![image](https://user-images.githubusercontent.com/3460315/30678839-47b9ca7c-9ee9-11e7-84b4-a3cda306a258.png)


This is the default build gradle as generated by MCDev. 
https://gist.github.com/anonymous/98ed53f4998da065026c08d9c45124cd

Default run configuration:
![image](https://user-images.githubusercontent.com/3460315/30679084-eecf130c-9eea-11e7-8224-edf7039319ba.png)

And the server log from starting.
https://gist.github.com/anonymous/3b67646e5f326f031b9a854952bb37c5

Sponge isn't loaded with the server on run with MCDev's default configuration.

If you are able to tell me what I need to change in my configuration in order to test in environment, as well as being able to build, I would very much appreciate it. I'm sorry if these feel like noob questions, I just want to get as much out of your plugin as possible :)

**Comment by DenWav** [comment]
The default generated config doesn't, no. I suppose I could add the SpongeForge dependency to the `build.gradle` to make it work.

**Comment by Evolht** [comment]
Do you know how I might do this properly? I'm having trouble ^_^;;
