### ISSUE TITLE
How add custom mc version?

### ISSUE THREAD

**Issue by ipl-adm** [DemonWav/MinecraftDevIntelliJ#296]
How add custom mc version? How i can do this? Cant find version list in ur repo

**Comment by kashike** [comment]
Why do you need to add a custom Minecraft version?
Versions are pulled from the website: https://github.com/minecraft-dev/minecraftdev.org/tree/master/versions

**Comment by ipl-adm** [comment]
I need add 1.7.10, cuz it comfortably for me.

**Comment by kashike** [comment]
You're on your own. We don't support 1.7.10.
Duplicate of #76.
Duplicate of #165.
Duplicate of #190.
Duplicate of #295.

**Comment by DemonWav** [comment]
Duplicate of #76

**Comment by DemonWav** [comment]
Duplicate of #76 and #165

**Comment by DemonWav** [comment]
Duplicate of #76
Duplicate of $165

**Comment by DenWav** [comment]
Duplicate of #76

**Comment by kashike** [comment]
Duplicate of #165.
Duplicate of #190.
Duplicate of #295.
