### ISSUE TITLE
Run configuration for Sponge plugins

### ISSUE THREAD

**Issue by ImMorpheus** [DemonWav/MinecraftDevIntelliJ#305]
It would be great to have run configs to launch a SpongeVanilla server while working on Sponge plugins. (Much like runServer for Forge mods).

**Comment by DenWav** [comment]
I think this would need to be something which is opt-in (checkbox default unchecked) since the added complexity and project setup time required for running `setupDecompWorkspace`. But yes, this is probably a good idea.

**Comment by ImMorpheus** [comment]
I probably missed something, can't you use the SpongeAPI version selected during the project setup to download the latest SpongeVanilla for that version ?
Once you have the SpongeVanilla jar you can create a run folder and the configuration to launch the server. Do you need to run setupDecompWorkspace ?

**Comment by DenWav** [comment]
Setting up a jar run config isn't exactly what I would consider optimal - though I could just add the jar to the classpath quietly in a modified application run config.

**Comment by vintprox** [comment]
SpongeGradle, that this boilerplate depends on, has a `runServer` Gradle task exposed. It already automatically installs needed version of SpongeVanilla for you, like `run-paper`. I had to manually add run configuration in IntelliJ IDEA for `runServer` to work by shortcut + debug.

**Comment by ImMorpheus** [comment]
This is a really old issue and we have VanillaGradle now.
