### ISSUE TITLE
Add support for custom forks of plugin servers

### ISSUE THREAD

**Issue by theminecoder** [DemonWav/MinecraftDevIntelliJ#306]
Users should be able to add custom dependency's as forks of a server type so that all of the features of the plugin can be used while working with forked versions of server software.

**Comment by DenWav** [comment]
You can enable the Minecraft facet manually on any IntelliJ module. `Project Structure -> Modules -> <right-click module> -> Add -> Minecraft`. Each module type can be enabled or disabled manually this way.

MCDev will never allow project generation for custom forks other than the projects already defined.

**Comment by kinggoesgaming** [comment]
hey I was about to say that... you are a ninja monster @DemonWav
