### ISSUE TITLE
Disable/enhance "unused" warning for event handling methods

### ISSUE THREAD

**Issue by PaleoCrafter** [DemonWav/MinecraftDevIntelliJ#31]
Note that I'm only going to talk from a Forge perspective here since I don't know any of the other systems in-depth.

Due to the fact that methods annotated with `SubscribeEvent` or `EventHandler` (usually) never get called directly, IDEA marks them as unused. This can easily be disabled by using IDEA's built-in support for marking certain annotations as "users". It would be great if the plugin could automatically add these exceptions.

Alternatively, enhanced usage detection could be put in place. This would entail marking the method as used whenever an instance of the containing class is passed into the event bus's `register` method. Whilst this is a great solution for simple setups, there are some mods out there which search for classes marked by their own annotation (something like `@RegisterBus`) and then create and register an instance automatically. These mods would obviously have to fall back to the built-in method mentioned above.

**Comment by DemonWav** [comment]
The plugin actually does add these exceptions automatically, but only when you create the project (so if you open an already-made project it won't do it). I've been thinking about enabling it for whenever a Minecraft mod is detected, to catch these cases as well.

How prevalent are the more complex mods vs the standard mods which use the event bus explicitly?

**Comment by PaleoCrafter** [comment]
I honestly do not know how common automatic registration of event handlers is. I personally can only come up with one case off the top of my head and I'm not even sure if that still uses this system.

However, it's great to read that the exceptions are already automatically added, even if only on project creation.
