### ISSUE TITLE
PaperSpigot API 1.8.8 isn't being downloaded (Gradle)

### ISSUE THREAD

**Issue by bn4t** [DemonWav/MinecraftDevIntelliJ#310]
The PaperSpigot API isnt being downloaded when using gradle and paper.

**Comment by bn4t** [comment]
It is listed as a Library but it doesn't exists.

**Comment by stephan-gh** [comment]
@DemonWav I think we should drop everything below `1.9.4` and `1.10` from the list, because they  don't seem to be actually available on the Maven repository: https://repo.destroystokyo.com/repository/maven-public/com/destroystokyo/paper/paper-api/maven-metadata.xml

**Comment by kashike** [comment]
Different group id: https://repo.destroystokyo.com/repository/maven-public/org/github/paperspigot/paperspigot-api/maven-metadata.xml

**Comment by DenWav** [comment]
Oh yeah I forgot about that change.

**Comment by DenWav** [comment]
So yeah, I figured I don't want to add a special case for this, and I don't want to support older versions anyways, so I went ahead and just removed it from the version selector. "Fixed" in [`82d5148`](https://github.com/minecraft-dev/minecraftdev.org/commit/82d51488cb76097966cc216269aa538056e71871).
