### ISSUE TITLE
How to decompile mc?

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#311]
When I create a new liteloader mod, it only lets me build, how can I run the mod

**Comment by DenWav** [comment]
To setup the LiteLoader run config, run the Gradle task provided by ForgeGradle `genIntellijRuns`. MCDev should automatically run this task during project setup, but I haven't gotten to adding that yet.

**Comment by DenWav** [comment]
Duplicate of #111.
