### ISSUE TITLE
Facet:minecraft not supported.

### ISSUE THREAD

**Issue by Narimm** [DemonWav/MinecraftDevIntelliJ#324]
**Unknown facet type: 'minecraft'**
Options
Would you like to ignore facet 'Minecraft' from module 'Monolith'?
Plugins Suggestion
					Plugin supporting feature (Facet[minecraft]) is currently not installed.
					Configure plugins...
					Ignore Unknown Features

However the minecraft plugin is enabled - I checked the plugins list...

This only occurred after upgrading to

IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by gabizou** [comment]
I had to uninstall the plugin and reinstall the plugin to get it to work again.

**Comment by Narimm** [comment]
Ok ty I will try that

**Comment by DenWav** [comment]
Did that fix it?
