### ISSUE TITLE
Handle multi-module Maven projects

### ISSUE THREAD

**Issue by DenWav** [DemonWav/MinecraftDevIntelliJ#328]
It's about time I get around to doing this.

Obviously won't be available for MCP or Forge project structures.

**Comment by loordgek** [comment]
i asked amadornes if you can do multi-module gradle projects w/ forge ?
yes it can but he tells it's extremely unstable because ForgeGradle is pretty crap
https://gist.github.com/amadornes/e5985fd8799715cfd3421acc9317bace

**Comment by loordgek** [comment]
@DemonWav ^

**Comment by DenWav** [comment]
I've never had issues with it personally.
