### ISSUE TITLE
Wrong syntax for dependencies block in mcmod.info

### ISSUE THREAD

**Issue by ImMorpheus** [DemonWav/MinecraftDevIntelliJ#330]
The default mcmod.info contains:
```
"dependencies": [
      ""
 ]
```

From: https://forums.spongepowered.org/t/mixins-not-applied-on-production/

> It looks like you don’t have any dependencies, but adding an empty string to it isn’t the way to do that. You can just remove the empty string (leaving it as just dependencies: []) or remove the dependencies block altogether.

**Comment by DenWav** [comment]
I wasn't aware of this, oops.

**Comment by DaemonUmbra** [comment]
I was having this issue with forge, it took me a while to find because it throws a runtime exception on the version parser, so I was looking in the wrong place
http://www.minecraftforge.net/forum/topic/42482-mod-detection-error/?do=findComment&comment=228820

**Comment by Musician101** [comment]
Still an issue in MCDev v. 2018.3-1.2.11
