### ISSUE TITLE
Unchecking Canary/Neptune plugin doesn't remove text

### ISSUE THREAD

**Issue by phase** [DemonWav/MinecraftDevIntelliJ#334]
I'm running `2017.3-0.7.5`

![image showing error](https://i.imgur.com/2ToDmPh.png)

If I check Canary or Neptune, the text appears. When I uncheck the box the text stays there. This isn't true for the other plugin types.

**Comment by DenWav** [comment]
Can you reproduce this on `2017.3-1.0.0`?
