### ISSUE TITLE
Attempt to find and warn about mixing block coords, chunk coords and chunk-local coords

### ISSUE THREAD

**Issue by Niko-sk2x** [DemonWav/MinecraftDevIntelliJ#336]
Using chunk coords instead of block coords, local coords instead of block coords, block coords instead of local coords etc seems to be a very common error in code. Would be a good idea to attempt to do static analysis to find it.

I usually prefix my coord names with `local`, `chunk` or `block` to distibuish that amd make the errors obvious but there are still cases where an error slips through (and sometimes goes undetected for a long time).

**Comment by DenWav** [comment]
Before I mark this as accepted, it would help me if you could show me specific examples in your code where you have (or might have) fallen into this trap, so I can try and formulate a method for analyzing these situations.
