### ISSUE TITLE
Prepare for supporting .json language files

### ISSUE THREAD

**Issue by kinggoesgaming** [DemonWav/MinecraftDevIntelliJ#337]
As of 18w02a, language files have changed from using`language.lang` to `language.json`. Major changes with this:

* key-value pair changes from `key=value` to `"key":"value"`
* newlines are now handled

[Source](https://minecraft.net/en-us/article/minecraft-snapshot-18w02a)

**Comment by marvin-roesch** [comment]
I already plan on updating PR #267 to accommodate for these changes. I'm not entirely sure *how* I'm going to do it, as the system currently relies on the files as "data storage", too.

Feature-wise, I should be able to keep parity with the current PR except for comments.
