### ISSUE TITLE
NullPointerException in Railcraft development

### ISSUE THREAD

**Issue by liach** [DemonWav/MinecraftDevIntelliJ#341]
https://gist.github.com/anonymous/b6851cb650fa76173a092cf4ae9ff349

Idea later says that there were too many errors so that its monitoring stopped.

**Comment by liach** [comment]
And what's worse, I cannot submit this issue within the ide using your bot.

**Comment by liach** [comment]
More info: branch: liach-1.10.2
happens when I ctrl+alt+l reformat code or at other times.

**Comment by DenWav** [comment]
Duplicate of #338.

Fixed in 822607e.

The fix will be deployed in the new release tomorrow. Otherwise, use the nightly build for the time being.

**Comment by liach** [comment]
Hmm. I thought I updated yesterday. This does not affect most of the features, such as sideonly checks, so it's fine.
