### ISSUE TITLE
Allow defining annotated parameters for a method as a lang key string

### ISSUE THREAD

**Issue by DenWav** [DemonWav/MinecraftDevIntelliJ#351]
For methods which take in a lang key string, but the plugin isn't able to determine that due to higher complexity (say for example, a class stores the string to a variable passed from the constructor, which is later used as a lang key).

I can see this happening one of three ways:

1. We define our own annotation that developers can include in their project via a single-class library. This annotation would only have `SOURCE` retention.
    - **Pros**: Universal support for anyone using mcdev with no configuration required. The annotation could take in a parameter which defines any prefix to the keys that should be added.
    - **Cons**: Developers would have to add in another dependency to their project. They may not know of this feature, so may not ever use it even if they wanted to. Might be considered cluttering of the code, especially for Eclipse users.
2. We let developers define their own annotations in their project.
    - **Pros**: Doesn't require the developer to pull in another dependency. Could also include the parameter defining a prefix.
    - **Cons**: This would require some setup by the developer, to add that annotation as a lang annotation in the plugin settings somewhere. Also has the same issue of cluttering code.
3. We let developers add it implicitly to their methods through an intention. Nothing in the code base, it's simply stored as the method signature in the plugin configuration.
    - **Pros**: Doesn't clutter the code at all. Again, the configuration can include a prefix.
    - **Cons**: Would require even more setup than a custom annotation (the annotation would only need to be setup once for all methods, this would require running the intention on even method they want to add). Maybe even more obtuse, so again, developers might never use it. At least with annotations, they would see them in the project to at least ask what it's for.

Maybe you could argue that options 2 and 3 are fixed by sharing project level `.idea` configurations, but I don't believe in sharing those files (even if they are "meant to be shared") and I don't want to put the expectation on other developers to do so.

I would really like feedback on this idea, and any implementation ideas you might have.

---

For the first two ideas, it would look something like this:

```java
public class TranslationContainer {
    private final String key;

    public TranslationContainer(@LangKey("some.prefix") final String key) {
        this.key = key;
    }

    public String getTranslationKey() {
        return "some.prefix." + key;
    }
}
```

In this case, `@LangKey` would be an annotation that we provide in a single-class library for option `#1`, and an annotation the developer has to add to their project and associate with mcdev for option `#2`.

This would allow folding of calls such as:

```java
public class Main {
    public static void main(final String[] args) {
        final TranslationContainer container = new TranslationContainer("key");
        System.out.println(container.getTranslationKey());
    }
}
```

In this case the folding would match to `some.prefix.key`, because the `@LangKey` annotation provided the prefix of `some.prefix`, and the parameter value is `key`.

**Comment by RedNesto** [comment]
https://github.com/minecraft-dev/annotations/blob/master/src/main/java/com/demonwav/mcdev/annotations/Translatable.java
