### ISSUE TITLE
Mixin cannot find <clinit>

### ISSUE THREAD

**Issue by mattmess1221** [DemonWav/MinecraftDevIntelliJ#355]
`<clinit>` is a valid internal method, but mixin cannot find it when used as the value for `method`. It throws an error. The gradle build is successful.

> Cannot resolve method '<clinit>' in target class

This doesn't prevent IDEA from building successfully, but it is a slight annoyance.

![image](https://user-images.githubusercontent.com/3409962/35773821-131618d2-092b-11e8-8758-d84b18765030.png)

**Comment by gabizou** [comment]
For starters, you shouldn't be injecting *instance* methods into the *static class initializer*, the method should be static. I'm fairly sure this would fail 100% at runtime otherwise.

**Comment by stephan-gh** [comment]
Note that instead of injecting into `<clinit>` you can just use a static initializer block to add code to `<clinit>`. But this won't work for the redirect obviously.

**Comment by DenWav** [comment]
I thought bugs were supposed to be considered accepted. Must have messed something up.

Oh, messed up the tag: https://github.com/minecraft-dev/MinecraftDev/blob/dev/.github/stale.yml#L12

**Comment by Earthcomputer** [comment]
#1221
