### ISSUE TITLE
Minecraft facets are not allowed in Shared sources module

### ISSUE THREAD

**Issue by Katrix** [DemonWav/MinecraftDevIntelliJ#359]
Just got this error when opening up one of my projects. It consists of a shared sources module, and 3 modules depending on the shared sources.

![tmp](https://user-images.githubusercontent.com/11007080/36068215-41049ad4-0ed0-11e8-919e-886241f80613.png)

**Comment by DenWav** [comment]
What's a shared sources module? I wonder what is special about it that would prevent it from being allowed.

**Comment by Katrix** [comment]
Not sure about the exact definition, but I think the easiest way to explain it is as a weird fusion between a source folder and a module. It has dependencies, but it those are only there for code completion sake from my understanding, and the user of the source module supply the dependency.

For example, in my case I have 3 modules, for 3 different sponge versions (sponge5.0.0, sponge6.0.0, sponge7.0.0). Each has their own separate set of sponge dependencies. They also all depend on the module called shared. Shared has all three sponge dependencies, while also not having any as it's not responsible for compiling any code. From the 3 sponge modules, the shared module is more like an extra source folder.

It seems like it's fine about the shared source module at first, but when I close and open the project again, it detects the shared source module again, even though it already detected it, while complaining that the previous detection was invalid.

I can give you the iml files of the shared source module, and a module using the shared source module if that helps.

**Comment by DenWav** [comment]
That would help, and I think I have an idea of what might be wrong.

**Comment by Katrix** [comment]
Ok here's the iml files for the shared sources module, and a module using the shared sources. The project for the iml files can be found here. https://github.com/Katrix-/KatLib

[ideaImls.zip](https://github.com/minecraft-dev/MinecraftDev/files/1714093/ideaImls.zip)

**Comment by RedNesto** [comment]
It doesn't seem to happen anymore.
