### ISSUE TITLE
Rename 'plugin.yml' to 'bungee.yml' for Bungeecord plugins

### ISSUE THREAD

**Issue by Vinetos** [DemonWav/MinecraftDevIntelliJ#360]
When we create a Bungeecord Project, The name of the plugin file have to be``bungee.yml`` and not ``plugin.yml``. 
If we have two submodules wiches create one Jar file, it will fail

**Comment by kashike** [comment]
This is something that, in my opinion, should be changed on a per-project level.

**Comment by Vinetos** [comment]
I made a pull request to fix this issue
