### ISSUE TITLE
Sponge plugin/injection mistakes

### ISSUE THREAD

**Issue by Cybermaxke** [DemonWav/MinecraftDevIntelliJ#361]
Related to https://github.com/LanternPowered/LanternServer/issues/26

Warn if a `java.util.logging.Logger` is requesting a guice injection in a sponge plugin, `org.slf4j.Logger` should be used instead. Could be expanded to warn if a injection type isn't supported, but will need to be kept up to date if sponge changes these.

Example:
```java
@Plugin(id = "my_plugin")
public class MyPlugin {

    @Inject private java.util.logging.Logger loggerA; // BAD
    @Inject private org.slf4j.Logger loggerB; // GOOD
}

**Comment by DenWav** [comment]
Should this be a general inspection on _any_ usage of `java.util.logging` in a Sponge plugin, if Sponge uses `org.slf4j`?

**Comment by Cybermaxke** [comment]
Yeah, that will work too.
