### ISSUE TITLE
Easy Keys

### ISSUE THREAD

**Issue by wyatt-herkamp** [DemonWav/MinecraftDevIntelliJ#364]
Please include the following information in all issues:

* Minecraft Development for IntelliJ plugin version
* IntelliJ version 17.03
* Operating System Fedora (Linux) 64bit 
* Target platforms Spigot/Paper/Bukkit
I was thinking as  a feature that would on a key pattern create things such as Commands and Listeners. Such as Intellij's Plugin designer you can create an action.
So I can do something like Ctrl-L and it will pull up a  menu you make a listener class with it position in the package. And What Listeners to add. So I can select OnPlayerJoin, OnPlayerQuit, PlayerDeathEvent and it will add those methods to the class. Also you can run another key pattern to pull up a menu to add more event methods. Thank you.
The Idea came from this: https://github.com/Corey-Null/SpigotProjectBuilder
I was also thinking of a same for command classes. 

Another feature. The ability to chose the language so I can chose Kotlin or Java.

**Comment by DenWav** [comment]
I'm not sure about this.

There already exists a generate code target for event listeners. All you'd have to do before that is create the class.

MCDev doesn't support Kotlin. Maybe it could generate Kotlin projects, but no other features would work with it. Maybe someday it will properly support other JVM languages...

**Comment by wyatt-herkamp** [comment]
What am I suppose to do?

**Comment by DenWav** [comment]
This functionality is better handled with other planned and requested features. Closing in favor of those.
