### ISSUE TITLE
Forge Run Configs should use GradleStart

### ISSUE THREAD

**Issue by TehNut** [DemonWav/MinecraftDevIntelliJ#37]
Instead of launching using `runClient` and `runServer`, Forge mods should launch as an Application using `GradleStart` and `GradleStartServer`. 

* This should use the classpath of the `PROJECT_main` module.
* The working directory should default to `PROJECT_DIR\run`.

![Example](http://i.imgur.com/MhIR4Rl.png)

**Comment by DemonWav** [comment]
I agree, this was part of a PR that did something else and I just accepted it as is. This will be fixed at some point, hopefully soon.
