### ISSUE TITLE
Forge Listeners not modified with a Gutter Icon

### ISSUE THREAD

**Issue by gabizou** [DemonWav/MinecraftDevIntelliJ#379]
For IntelliJ 2018.1 with Minecraft Development 2017.3-0.7.5

Sponge listeners have the gtutter icon, but forge event listeners are not showing up, even with the forge class path available.
![screen shot 2018-04-26 at 4 59 17 pm](https://user-images.githubusercontent.com/1203877/39337737-668250b6-4973-11e8-9c3a-6067a51f0954.png)

This is a little difficult to replicate because of the nature of the module:
https://github.com/SpongePowered/SpongeForge/blob/e32e5e2edc2ab018a87c8fcdb27b80fbbfadb825/testmods/build.gradle

**Comment by TehNut** [comment]
Forge events are subscribed with `@SubscribeEvent`, not `@Subscribe`.

**Comment by gabizou** [comment]
Yeah, my bad being stupid, somehow I thought it was still using guava's `@Subscribe`...

**Comment by liach** [comment]
well, forge custom mod container classes uses guava subscribe and listens from a guava bus
