### ISSUE TITLE
What's meaning of this？

### ISSUE THREAD

**Issue by forestbat** [DemonWav/MinecraftDevIntelliJ#385]
![qq 20180510155419](https://user-images.githubusercontent.com/23413915/39858918-9e0b3d8e-546a-11e8-896c-b3d9c6be5a2a.png)
What's meaning of this？Why MCP versions are always wrong when it's 1.x.2 MC version？

**Comment by DenWav** [comment]
[MCP only has versions for 1.12 currently.](http://export.mcpbot.bspk.rs/) 1.12 mappings are compatible with 1.12.2, but I haven't yet implemented checks for compatibility yet (not sure where I'd  get that information programmatically, actually), so it just checks if the versions match.

I recommend using either the most recent MCP version, or whatever version of MCP Forge is currently using for your target Minecraft version.
