### ISSUE TITLE
Cannot jump to inner class in Mixin config

### ISSUE THREAD

**Issue by Aaron1011** [DemonWav/MinecraftDevIntelliJ#391]
Mixin supports using static inner classes as mixins. However, MinecraftDev is unable to parse references to static inner classes in Mixin configs (e.g.`OuterClass$MixinInner`). Even though the class exists, and is properly loaded by Mixin, MinecraftDev displays it in red.

Version: `v. 2018.1-1.2.5`

**Comment by RedNesto** [comment]
Inner mixin references have been working for a while now.
