### ISSUE TITLE
platform:forge [Bug]There was an error while attempting to retrieve versions

### ISSUE THREAD

**Issue by hohserg1** [DemonWav/MinecraftDevIntelliJ#436]
Please include the following information in all issues:
* plugin version 2018.1-1.2.8
* IntelliJ version 2018.1.4
* windows 10
* forge
  * getting versions of forge,mcp
  * few last days

When I  try to create new forge mod list of versions of forge is empty and is not downloading

Screenshot:
http://prntscr.com/k654xc

**Comment by DenWav** [comment]
I'll go ahead and use #444 as the base issue for this.
