### ISSUE TITLE
Eclipse support？

### ISSUE THREAD

**Issue by Mgazul** [DemonWav/MinecraftDevIntelliJ#438]
I have been using eclipse, I hope the plugin can support eclipse, thanks!

**Comment by gabizou** [comment]
Sorry, this is strictly an IntelliJ IDEA plugin. A LOT would have to change just to support eclipse, it's almost impossible to make this plugin compatible for two disparate types of IDE's.

**Comment by DenWav** [comment]
The amount of work that would be required for even the most basic MCDev features in Eclipse is enormous. I'd be more than happy to work with a contributor that I trusted if they wanted to pick up development of an Eclipse version of the plugin, but that doesn't look like something that is going to happen.

**Comment by yannicklamprecht** [comment]
Solution: Download IntelliJ idea -> go into settings/preferences -> search for keymap -> select Eclipse keymap.
