### ISSUE TITLE
Error occurs when creating a Forge Project.

### ISSUE THREAD

**Issue by reserveword** [DemonWav/MinecraftDevIntelliJ#444]
* Minecraft Development for IntelliJ plugin version:**2018.2-1.2.9**
* IntelliJ version:**2018.2(ultimate version)**
* Operating System (this has come up enough times to be important):**windows 10 1803**
* Target platforms:**windows**
* Where the issue occurs:
when i am creating a project, i get stuck at this view:
![image](https://user-images.githubusercontent.com/12995615/43702175-78c6e71a-998b-11e8-8edd-8a9b4265b450.png)
for very long(more than 30 minutes). sometimes it tells me there's an error like this:
![image](https://user-images.githubusercontent.com/12995615/43702366-25a625ae-998c-11e8-8707-3832f0dfb838.png)

when i ignore this error and continue, the minecraft-dev plugin fails to init.
(kotlin.UninitializedPropertyAccessException: lateinit property pluginName has not been initialized)

**Comment by Mumfrey** [comment]
Can you access this url:

[`https://files.minecraftforge.net/maven/net/minecraftforge/forge/json`](https://files.minecraftforge.net/maven/net/minecraftforge/forge/json)

In your web browser? It could be that there is some firewall or other security software preventing access to the server on your PC/network.

**Comment by DenWav** [comment]
There are two issues here:

1. Bad error message not explaining the problem
2. You aren't supposed to be allowed to go to the next page without those values filled in.

**Comment by reserveword** [comment]
@Mumfrey 
I can access the url in your comment. I even found some json sources they use like [export.mcpbot.bspk.rs](url) and also tested the accessibility of that website.
The result shows that there's no permanent barriers through it can fail at some particular attempts.

**Comment by Stampede2011** [comment]
Currently receiving this issue while trying to create a Forge mod. Is there any update on if this bug is being fixed or has been fixed?

**Comment by DenWav** [comment]
This code is fairly different now with the rewrite to handle FG3.
