### ISSUE TITLE
Using static import for ChatColor changes color in left of screen

### ISSUE THREAD

**Issue by bristermitten** [DemonWav/MinecraftDevIntelliJ#445]
* Minecraft Development for IntelliJ plugin version: 2018.2-1.2.9
* IntelliJ version: 2018.2.2 EAP - #IU-182.4219.4
* Operating System: Ubuntu 18.04.1 LTS
* Target platforms: In IntelliJ

This may be an issue with the EAP.

When using the Bukkit ChatColor enum, a colored square appears next to the line number, clicking it brings a color picker. This can be seen in this screenshot:
![screenshot from 2018-08-12 12-36-41](https://user-images.githubusercontent.com/18754735/44001567-84d1e53c-9e2c-11e8-852e-2f794711871a.png)
Upon using a static import for the ChatColor enum (to reduce repeating ChatColor over and over), the color in the left changes to the respective DARK_[COLOR] counterpart. This has been tested and seems to occur with RED, BLUE, and GREEN, but not GRAY, AQUA, etc.
Here's a screenshot:
![screenshot from 2018-08-12 12-38-15](https://user-images.githubusercontent.com/18754735/44001599-0d643ada-9e2d-11e8-8ed7-5d0e9ca61f81.png)

As said, this may be an issue with the IntelliJ EAP as I don't recall it happening to me before being upgraded, however I haven't tested with it.

**Comment by DenWav** [comment]
Well that's rather bizarre.

**Comment by RedNesto** [comment]
Doesn't happen anymore.
