### ISSUE TITLE
[Problem] CraftPlayer not a thing.

### ISSUE THREAD

**Issue by TheDaChicken** [DemonWav/MinecraftDevIntelliJ#446]
Please include the following information in all issues:

* Minecraft Development for IntelliJ plugin version:  2018.2.-1.2.9
* IntelliJ version: 2018.2
* Operating System (this has come up enough times to be important): Windows 10 
* Target platforms: SPIGOT Coding. VERSION: 1.8.8
  * Either where the issue occurs
  * Or where the feature request is relevant

Hey! I used your "Minecraft Development" Plugin for the past few weeks and it's really helpful using IntelliJ but there is one problem, Intellij is not picking up CraftPlayer as a thing and also anything under, net.minecraft. Is there a fix to this?

**Comment by DenWav** [comment]
The Spigot API does not contain NMS classes. You have to setup your project differently to access those classes, which isn't relevant to this project. I don't condone NMS plugins and will not help you set that up, but there are many people in the community you can ask that can help you.
