### ISSUE TITLE
Add new Run Configuration type for Bukkit/Spigot projects.

### ISSUE THREAD

**Issue by Senmori** [DemonWav/MinecraftDevIntelliJ#448]
* MinecraftDevelopment Version: 2018.2-1.2.9-112
* IntelliJ Version: 2018.2.2 (Build # IC-182.4129.33)
* OS: Windows 10 (64 bit)
* Target platforms:
  - Bukkit/Spigot projects (Paper?)

### Requested Feature:
Add the ability to apply bukkit/spigot patches without having to enter the terminal every time.
I think this would be best as a Run Configuration (RC), so it's simple to create and modify.
Ideally, you would just point the 'Apply Patches' and/or 'Make Patches' RC to the BuildTools directory and it would scan for the most recent mappings directory.
Or, if there is no clean way to do it. You could have the patches directory be manually specified (and remembered preferably).

Optionally, you could be able to specify the interpreter to use. Similar to how BashSupport requires you to specify the bash interpreter to run .sh scripts with. No real reason for this other than people who want to use a certain bash interpreter.

I believe this would be very useful so all new developers have to do is create a run configuration, point it to the newest decompile directory, and run the configuration.

### Notes:
I did not include Paper in this because they have a completely different patching system that I don't think would be within the scope of this request. Although I'm not very familiar with their system outside of how to get Paper running in a development environment.

**Comment by DenWav** [comment]
No, this isn't a problem.
