### ISSUE TITLE
Make patch releases read the correct mapping sets

### ISSUE THREAD

**Issue by adrwa** [DemonWav/MinecraftDevIntelliJ#451]
When creating a new forge project, due to MCP not exporting mapping sets for versions like 1.12.1 or 1.12.2, they reset to the latest stable, for the longest time we had no 1.12 stable which made using the plugin to create forge projects completely pointless for most.
I believe the plugin should change to ignore patch versions when selecting mappings.

**Comment by DenWav** [comment]
There's a better solution than just ignoring patch versions, but I can never remember what it is. I'll need to find that source again, there's a source that shows compatibility for MCP versions. Might be in the Forge API, not sure.

**Comment by marvin-roesch** [comment]
Oof, misclicked.
