### ISSUE TITLE
Support for Velocity Proxy plugins

### ISSUE THREAD

**Issue by AoElite** [DemonWav/MinecraftDevIntelliJ#464]
An option to select Velocity as a plugin when creating a project.
Velocity Proxy: https://github.com/VelocityPowered/Velocity
This could also help as well: https://media.readthedocs.org/pdf/velocity/latest/velocity.pdf

**Comment by callmesensey** [comment]
You do not plan to add this feature?

**Comment by RedNesto** [comment]
Nobody is working on it AFAIK, but I'm interested in picking it up and at least add it to the project wizard and some basic platform-agnositc features that all other platforms have.
