### ISSUE TITLE
[Feature Request] Abstraction Support for Bukkit / Spigot

### ISSUE THREAD

**Issue by GreatThane** [DemonWav/MinecraftDevIntelliJ#470]
Most plugins (At least for platforms like paper, spigot, and bukkit) rely on supporting multiple versions of the base game with the same jar to pull in more users. The issue is, for most plugins that do anything in-depth require NMS or packet work. To achieve this, they either have to work with these functions indirectly through another plugin's API (such as ProtocolLib) or work with them directly, which offers more freedom and flexibility, but the instant you do so you have limited your jar to only work for that specific game version. 
There are two ways around this issue, one through reflection, and the other through abstraction. Reflection, which can have the ability to support newer versions of the game, it is hindered whenever API changes occur, along with being difficult to write and read. In contrast, abstraction allows for different code to be run depending on the version, along with being somewhere between 2 to 4 times faster depending on your use cases. On top of all of that, you can actually use reflection in abstraction, allowing a "catch-all" version method that uses reflection. There are very few cases which reflection would be preferred. The major issue with this is initially set up, which is infuriating due to contradicting and outdated information online along with most not having a solid grasp on the pom.xml format and options necessary to make a successful abstraction project (specifically parents and modules).
I believe it would be a great addition to this service to have options to auto-create or reformat your plugin projects to use abstraction with a friendly interface rather than confusing sources. Such an addition would pull in not only new developers but experienced ones who do not want to deal with the hassle of setting these annoying files up with every new project.
Here's as far as I can tell the most in-depth tutorial for abstraction, even if incredibly old: https://bukkit.org/threads/support-multiple-minecraft-versions-with-abstraction-maven.115810/
This thread also has a few links to projects taking advantage of abstraction.
Here's the only thread on spigot's wiki, which does not contain much information but could be useful to some: https://www.spigotmc.org/wiki/nms-on-different-versions-without-reflection/

**Comment by DenWav** [comment]
NMS will never be supported. Someone who is confused by how to set up an NMS workspace shouldn't be using NMS in the first place.

**Comment by GreatThane** [comment]
I am deeply sorry if my point was not clear enough. My intent was not to ask for a built-in NMS de-obtusifier (users can simply look through the same game version of forge for that), nor a friendlier API built on top of spigot to make NMS easier to work with (I don't even think that would be possible to do), but for setting up abstraction. The reason for it is the lack of information, and as far as I can tell the way it is used specifically for plugins means that no information on how to set it up exists outside of the spigot and bukkit forums. Abstraction doesn't specifically have to do with NMS, just like reflection doesn't have to do with it. It simply can be used to write version-independent plugins that take advantage of the full capabilities of NMS, but also just write different code for different versions of the game.
For instance, a plugin could have code for a crate system, where you right-click a block and get an inventory GUI. Let's say the developer is a big fan of concrete (which was added in 1.12), so they use brown concrete as the block. But, there is still a huge chunk of 1.8 servers they want to support! They could use abstraction to have the block be stained clay in pre-1.12 versions.
While this specific case would probably be overkill, there are other cases where abstraction can be incredibly useful, such as the change in 1.13 were Minecraft committed to the switch from magic number ids to string-based ids. Because of this, the Material class was updated to use both the new ids, and the previous with the tag "LEGACY_" put on them. This broke a large number of plugins for 1.12, and makes both forward and reverse compatibility difficult to achieve after 1.13.
Abstraction is powerful not because it makes NMS easier to use or understand, but just make plugins that use raw NMS compatible across multiple base game versions, which is why I felt I should suggest an extra menu or checkbox when setting up one's project for abstraction, because it is so powerful and easy to use once you have set it up properly. The only issue is it can be infuriating trying to do so, even for experienced developers. Because creating these projects is normally very formulaic (move NMS dependencies to the version-specific modules, have a base "API" module that version-specific modules extend/implement classes, have all modules have the same package structure), it should not be all too difficult to have a program do this set up for the user. However, it would be up to the user to understand how to effectively use abstraction.
I agree with you that if users do not know how to use NMS, they would be better off using APIs like ProtocolLib or the various NBTTag APIs available, and let those plugins deal with abstraction for them while still getting the benefits of easier to understand and use classes and methods.
If this explanation has not changed your mind on my suggestion, I apologize wasting your time.
Thank you for your consideration.
