### ISSUE TITLE
Add Hibernate Support

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#476]
# Feature Request <br>
Please add the option to include hibernates to the boilerplate, that would be helpful if you have to work with huge bills of data like requested by ml-based anticheats and others like shop systems.
would be a really nice help to have hibernate on board.

**Comment by ryantheleach** [comment]
Is there a good reason why the UI should be more cluttered with this option? what about support for JOOQ / insert library here?

Or is there a direct analog to the McDev UI, that does have this option, which makes it look 'missing' from McDev that I've not picked up on.

**Comment by ghost** [comment]
I just want a little option to add hibernates, basically for ORM.
