### ISSUE TITLE
Main Class not being created properly.

### ISSUE THREAD

**Issue by theCarso** [DemonWav/MinecraftDevIntelliJ#508]
Please include the following information in all issues:

MCDev: v2018.3-1.2.14
IDE: IntelliJ IDEA Community Edition 2018.3.4 x64
OS: Windows 10 Home

![image](https://user-images.githubusercontent.com/40255057/52904999-7a511100-3201-11e9-8009-7dd4cc46cc17.png)

Think that picture says it all- created a Spigot 1.13.2 plugin with the MCDev Facet and it misplaced a semicolon.

**Comment by yannicklamprecht** [comment]
It did not misplace the semicolon. It didn't add the import.

**Comment by theCarso** [comment]
> It did not misplace the semicolon. It didn't add the import.

Not the Import box thing - talking about the line at the top and the extra semicolon 2 lines down, that semicolon should be between bugtest and import.

**Comment by DenWav** [comment]
Well that's bizarre. Is this reproducible?

**Comment by theCarso** [comment]
It happens any time I make a new module with McDev, I've tried restarting IntelliJ. I am going to try reinstalling MinecraftDev then I'll post the results if it fixed or not.

**Comment by theCarso** [comment]
![image](https://user-images.githubusercontent.com/40255057/52905885-d1a9ae00-320e-11e9-97be-832d7c4fb5a3.png)
Same result. Looks like it is just a misplaced semicolon.

**Comment by DenWav** [comment]
Fixed in a16a87054875e0668482abee74165a92f20fd9f4.
