### ISSUE TITLE
MC and Sponge Sources Not Available After Creating LiteLoader Project

### ISSUE THREAD

**Issue by willies952002** [DemonWav/MinecraftDevIntelliJ#53]
When creating a project using the LiteLoader template, it seems that `net.minecraft.*` and `org.spongepowered.*` are missing from the project, meaning that any time that an import from those package is needed, they will not properly import, as well as show up as a sea of red when viewing LiteLoader's sources.

Please keep in mind, this is an observation and there are no related error logs.

**Comment by DemonWav** [comment]
Doing a normal project creation I was not able to reproduce this. Please give a specific set of steps for how to properly reproduce this bug.

**Comment by willies952002** [comment]
Sorry for the late reply but here's what you asked for:

1) Create New Project with `Minecraft Plugin: LiteLoader Mod` template
MCP Version: snapshot_20160830
Minecraft Version: 1.20.2
everything else doesn't matter (groupid, artifactid, etc.)

2) Wait while project gets setup

3) Import Module from Gradle
- Use auto-import
- Create directories for empty content roots automatically
- Use default gradle wrapper
Gradle home: `/usr/share/gradle`
Gradle JVM: `User Project JDK (java version "1.8.0_101, path: <path>)`

You can call me stupid all you want, I've never really worked w/ gradle =P

btw.. I ended up finding the solution: don't use default wrapper *facepalm*

**Comment by ryantheleach** [comment]
I thought that default wrapper should have worked.? can someone help me understand why it shouldn't work?

**Comment by DemonWav** [comment]
Yes, the default wrapper should work fine. I don't know of any reason why it wouldn't.

**Comment by willies952002** [comment]
I ended up using `Use gradle wrapper task configuration`

![Image](http://i.imgur.com/2JxmJb9.png)

**Comment by DemonWav** [comment]
I'll leave this closed for now. If someone else has this issue then this can be investigated further.
