### ISSUE TITLE
Latest version dropped support for 1.11 and below

### ISSUE THREAD

**Issue by Shawn11564** [DemonWav/MinecraftDevIntelliJ#591]
Why was support dropped for these versions. I can only make a plugin for 1.12+ now.

**Comment by DenWav** [comment]
Because I have no interest in continually supporting older versions nor do I want to be part of the problem that continues to support it.

If you want to create a plugin for an older version you can do it the old-fashioned way, but I'm not going to continue to support older versions.

**Comment by Shawn11564** [comment]
According to bStats, 1.8.8 is still the 2nd most used spigot version. I don't see what problem there is? https://bstats.org/global/bukkit

**Comment by yannicklamprecht** [comment]
I recommend looking at all the Spigot threads where people begging to get support for an outdated Spigot version. If they don't get the fix they behaving impropriate.

Getting Bugfixes for a 4-5 years old Minecraft version is not the way evolving a opensource project. And DemonWav doesn't want to be a part of the problem.

**Comment by Tallerik** [comment]
But he can say that he will not give support for this versions and not block them completely

**Comment by electrolys** [comment]
i think you should allow people to use all the versions (even if they are broken) that you used to have but i know that your probably not going to change your mind

**Comment by yannicklamprecht** [comment]
> But he can say that he will not give support for this versions and not block them completely

Don't you read? He says that he doesn't support it.


> i think you should allow people to use all the versions (even if they are broken) that you used to have but i know that your probably not going to change your mind

Then just use a IntelliJ Version where the plugin supported your Minecraft version.

It's like saying that Anno 1604 doesn't work on your Windows 11 System. If you want it working just install Windows XP.
🤷🏼‍♂️

**Comment by electrolys** [comment]
> > But he can say that he will not give support for this versions and not block them completely
> 
> Don't you read? He says that he doesn't support it.
> 
> > i think you should allow people to use all the versions (even if they are broken) that you used to have but i know that your probably not going to change your mind
> 
> Then just use a IntelliJ Version where the plugin supported your Minecraft version.
> 
> It's like saying that Anno 1604 doesn't work on your Windows 11 System. If you want it working just install Windows XP. 🤷🏼‍♂️

i did actually try that and i couldn't get it to work for some reason do you know the specific version he removed it i couldn't find it out i just used a really old version and it didn't work

**Comment by HyperSkys** [comment]
> i think you should allow people to use all the versions (even if they are broken) that you used to have but i know that your probably not going to change your mind

Sorry to inform you man but nobody in their right mind should find this as an issue I instantly go to my pom.xml to go from the Spigot API to normal Spigot built with BuildTools but let's assume you don't then it's just a simple value change in the pom.yml file

**Comment by Derailedzack** [comment]
If you want to use 1.7.10 use [ExampleMod1.7.10](https://github.com/SinTh0r4s/ExampleMod1.7.10).

**Comment by SzczurekYT** [comment]
> According to bStats, 1.8.8 is still the 2nd most used spigot version. I don't see what problem there is? https://bstats.org/global/bukkit

You should also consider fabric and forge mods. Plugins aren't everything.

**Comment by AshwaysDev** [comment]
> > According to bStats, 1.8.8 is still the 2nd most used spigot version. I don't see what problem there is? https://bstats.org/global/bukkit
> 
> You should also consider fabric and forge mods. Plugins aren't everything.

Hum... 90% of total players are in multiplayers, and using plugins, with bstats. Fabric/Forge don't mean anything in the statistics
