### ISSUE TITLE
pom.xml has literal before variable name 

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#618]
Plugin: v. 2019.1-1.2.22
IntelliJ 2019.3 community
OS: linux ubuntu 18.xx

With the default generated pom.xml, Maven errors on compile.
in the pom.xml:
                    <source>\\${java.version}</source>
                    <target>\\${java.version}</target>

With the backslash removed it compiles.

**Comment by darbyjack** [comment]
PRed a fix #621
