### ISSUE TITLE
There is no option to create new MinecraftDev Project in 'New Project'

### ISSUE THREAD

**Issue by portlek** [DemonWav/MinecraftDevIntelliJ#624]
* Minecraft Development for IntelliJ plugin version: 2019.2-1.2.22
* IntelliJ version: 2019.2 EAP (192.5281.24)
* Operating System: Windows 10 v1903

![alt text](https://i.snag.gy/JTAYh3.jpg "Logo Title Text 1")

**Comment by GMatrixGames** [comment]
I had this issue as well, it's due to the add-on not being supported in that version

**Comment by portlek** [comment]
> I had this issue as well, it's due to the add-on not being supported in that version

well, we need a update which includes 2019.2 :)
