### ISSUE TITLE
Support for MCP

### ISSUE THREAD

**Issue by LukasDoesDev** [DemonWav/MinecraftDevIntelliJ#626]
# YOU CAN DO IT!

**Comment by portlek** [comment]
why you don't use forge?

**Comment by LukasDoesDev** [comment]
cuz im pro and make a custom client ha

**Comment by portlek** [comment]
> cuz im pro and make a custom client ha

hello pro man, bro you can use http://www.modcoderpack.com/ this site, and its creating a workspace to create clients or mods or anything ;)
