### ISSUE TITLE
Highlight performance-critical contexts. 

### ISSUE THREAD

**Issue by cadenkriese** [DemonWav/MinecraftDevIntelliJ#632]
Hi all,

When using JetBrains Rider along with Unity, the IDE highlights methods that are 'performance-critical' due to the number of times they're fired when the game is running.

<img width="473" alt="Picture from Rider" src="https://user-images.githubusercontent.com/13630061/61000880-a5a4db80-a31b-11e9-8524-ad0cbcab8880.png">

I believe this could be useful for developing in Minecraft as well, to remind developers to be cautious with their code within certain events such as PlayerMoveEvent, ChunkLoad/UnloadEvent or any Bukkit timers that fire relatively quickly.

**Comment by DenWav** [comment]
This is interesting, would need a list of events that would qualify for this.
