### ISSUE TITLE
Discord link broken?

### ISSUE THREAD

**Issue by Machine-Maker** [DemonWav/MinecraftDevIntelliJ#645]
Not really an issue, but both the discord invite on the README.md page and on the website are broken.

**Comment by DenWav** [comment]
Hard for me to test this, seems like it's valid to me though?

**Comment by RedNesto** [comment]
He joined the discord server 1 week after opening this issue, so I guess he got it working.

**Comment by DenWav** [comment]
Nice eye.

**Comment by Machine-Maker** [comment]
Yeah, this was strange. It wasn’t working in my browser but if a copied and pasted the link into a discord channel, it then worked.
