### ISSUE TITLE
No spell checking in .lang files

### ISSUE THREAD

**Issue by prplz** [DemonWav/MinecraftDevIntelliJ#648]
* Minecraft Development version 2019.1-1.2.23
* IntelliJ IDEA 2019.1.3 (Ultimate Edition)
* Operating System: Windows 10
* Target platforms: ForgeGradle 2.1 / Forge 1.8.9

Spell checking appears to be completely unavailable in .lang files while using the plugin, yet works with the plugin disabled.

**Comment by RedNesto** [comment]
Implemented in 6e03da27145157c900b0c4fd5a464f4b9cbf608a
