### ISSUE TITLE
Gradle error after creating project

### ISSUE THREAD

**Issue by leytilera** [DemonWav/MinecraftDevIntelliJ#649]
Please include the following information in all issues:

* Minecraft Development for IntelliJ plugin version: 1.2.23.1
* IntelliJ version: 2019.2.1 Ultimate
* Operating System: Windows 10
* Target platforms: Forge 1.12.2-14.23.5.2838

When I create a new project and run the gradle sync this error comes:
Unable to find method 'org.gradle.api.internal.TaskOutputsInternal.dir(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputs;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by DenWav** [comment]
Can you be more specific about what you're trying to do and your environment?

**Comment by TimmyOVO** [comment]
switch idea boot jdk version to jdk8 instead of java11
