### ISSUE TITLE
Disable warning for mixins

### ISSUE THREAD

**Issue by RDIL** [DemonWav/MinecraftDevIntelliJ#650]
How can I disable https://github.com/minecraft-dev/MinecraftDev/blob/71c01208d75e573f20290575e201cd3a2ff639c0/src/main/kotlin/com/demonwav/mcdev/platform/mixin/MixinCustomJavaDocTagProvider.kt#L45 ?
Thanks!

**Comment by DenWav** [comment]
`Alt - Enter` on the warning and go to inspection settings and disable it - it's just a standard inspection, nothing special required.
