### ISSUE TITLE
Mod class is not created anymore

### ISSUE THREAD

**Issue by leytilera** [DemonWav/MinecraftDevIntelliJ#651]
*Minecraft Development for IntelliJ plugin version: 1.2.23.1
*IntelliJ version: 2019.2.1 Ultimate
*Operating System: Windows 10
*Target platforms: Forge 1.12.2-14.23.5.2838

When I create a new project, the plugin isnt creating the mod class anymore

**Comment by DenWav** [comment]
I recently pushed FG3 support to nightly, which also fixed a few issues with Forge project creation. Hopefully this can be released soon.
