### ISSUE TITLE
Please do not drop support for Java 8

### ISSUE THREAD

**Issue by LoganDark** [DemonWav/MinecraftDevIntelliJ#654]
I created this issue just to beg you to _please_ not force JDK11, I need to use JDK 8 as the IDE boot JDK or ForgeGradle won't work.

Maybe I misunderstood the commit messages, but I'm just putting this out there. It would be a shame if you left people like me behind by suddenly starting to require a new JDK :(

**Comment by RedNesto** [comment]
Since 2019.2-1.3.1 the plugin is compiled with JDK 8 again, so this should no longer be an issue.

**Comment by LoganDark** [comment]
Yeah, this issue is here to say "please don't do that again". I never actually got that update, I just saw that there was one and checked the GitHub commits to see what changed.

**Comment by DenWav** [comment]
As soon as IntelliJ requires JDK11 so will this plugin. Frankly the fact that both 1. the Gradle tooling API has such a requirement at all and 2. IntelliJ doesn't mitigate that with any kind of sandboxing API is just straight up bonkers.

Once IntelliJ requires JDK11 there won't even be an option to go back to 8 anyways.  Hopefully that is (gotta push forward). Don't worry though, they'd only do that once they've mitigated any issues with interacting with Gradle etc.
