### ISSUE TITLE
Some error and cannot auto report to github

### ISSUE THREAD

**Issue by liach** [DemonWav/MinecraftDevIntelliJ#658]
* Minecraft Development for IntelliJ plugin version: 2019.2-1.3.1
* IntelliJ version: 
`IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1953M
Cores: 8
Registry: 
Non-Bundled Plugins: GLSL, com.tsunderebug.discordintellij, com.demonwav.minecraft-dev, org.jetbrains.kotlin`
* Operating System (this has come up enough times to be important)
* Target platforms
  * Possibly only mixin (in a fabric project)

1. Error when closing a class file? (I forgot the exact action unfortunately)
https://gist.github.com/6cc56b803bb5b756751e51d3451b201c

2. Cannot automatically submit error report with the submit button.
Message:
```
Error Submitting Issue: no protocol:  /api.github.com/repositories/42327118/issues?state=closed&creator=minecraft-dev-autoreporter&per_page=100&page=3 Consider opening an issue on the GitHub issue tracker.
```

**Comment by DenWav** [comment]
I had a feeling it wasn't working considering new reports stopped coming in...

**Comment by liach** [comment]
Just curious, will this auto-report system ever come back

**Comment by liach** [comment]
Sure, we don't need auto report
