### ISSUE TITLE
[Feature Request] Default config value views

### ISSUE THREAD

**Issue by jpeaceau** [DemonWav/MinecraftDevIntelliJ#661]
Hey, this is a feature request (hence why I removed the formatting). There has been countless times where I'd look for the wrong value in the configuration lol. It would be really helpful if when you hover over getConfig().[getInt() get() getString etc...] it shows you the default value it will receive.

**Comment by Vinetos** [comment]
Yeah ! It would be awesome ! Do you have any example to show us ?
Maybe another plugin / tools for IDEA which do that ?
