### ISSUE TITLE
Add support for FabricMC

### ISSUE THREAD

**Issue by Martmists-GH** [DemonWav/MinecraftDevIntelliJ#663]
[FabricMC](https://fabricmc.net) is becoming increasingly popular for modding 1.14 and above.

I hereby suggest adding support similar to all other platforms supported. The tools required can be found on the [FabricMC Github](https://github.com/FabricMC) and an example mod can be found at [FabricMC/fabric-example-mod](https://github.com/FabricMC/fabric-example-mod).

**Comment by Martmists-GH** [comment]
Bump to keep the request open

**Comment by Yive** [comment]
Now that it is 2020, I hope we'll see this being supported 🤞

**Comment by KisaragiEffective** [comment]
yep

**Comment by jamierocks** [comment]
People are more than welcome to PR support for the platform, see [Forge](https://github.com/minecraft-dev/MinecraftDev/tree/dev/src/main/kotlin/com/demonwav/mcdev/platform/forge) for an example implementation.

**Comment by JustPyrrha** [comment]
@Earthcomputer's fork has support for Fabric https://github.com/Earthcomputer/MinecraftDev

**Comment by Earthcomputer** [comment]
I've been meaning to make a PR here for a while, it's just a matter of extracting the relevant changes from my fork. I've also had the advantage of having people test it and report bugs... it's my first time using kotlin, the intellij platform SDK and mcdev code, and it's not easy to get things right first try. However I think it's almost at the stage where I'm happy with its basic Fabric support.

There is a lot of work in supporting a platform like Fabric, as it's quite different from any other existing platform. Adding a basic project generator and project type is the beginning (and is what would likely make up a PR for here), but proper support will involve extending existing inspections, intentions and code folding to work with yarn mappings and the Fabric platform, and updating some of mcdev's other inspections to 1.14/1.15 Minecraft. I've kind of started on this aspect in my fork but there is a lot of work still to go, so these things can come in a later PR.

**Comment by DenWav** [comment]
I was planning on implementing support, more than happy to accept a PR (especially since I've never worked with Fabric that will help). I'm currently in a major rewrite of a large portion of the project so I want to get that done first, but I will be done soonish hopefully.
