### ISSUE TITLE
1.8 Environment's ForgeGradle version

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#664]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version: 2019.3-1.3.1
* IntelliJ version: 2019.3 EAP
* Operating System (this has come up enough times to be important): Windows 10, 18362.418
* Target platforms
  * Either where the issue occurs: Forge 1.8.9

Creating a Forge 1.8 project will automatically assign the ForgeGradle version as 2.2, which causes a slight annoyance with people that aren't typically aware, or slightly incapable of reading the error when it spits out the "ForgeGradle 2.2 only supports 1.9 - 1.11" or whatever.

**Comment by RedNesto** [comment]
This won't be fixed, only 1.12.2 and up are supported.
