### ISSUE TITLE
Plugin is not supported with latest InteliJ version

### ISSUE THREAD

**Issue by DanBTechnology** [DemonWav/MinecraftDevIntelliJ#674]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version
- 2019.2-1.3.2
* IntelliJ version
- 2019.2.4 (build 192.7142.36)
- Latest version is 2019.3.1 (build 193.5662.53)
* Operating System (this has come up enough times to be important)
- Windows 10
* Target platforms
  * Either where the issue occurs
  * Or where the feature request is relevant

![CaptureTemp](https://user-images.githubusercontent.com/6370453/71788053-eccf0900-2fec-11ea-94f7-40baac1878d6.PNG)

For feature requests, try to avoid vague requests. The more details there are explaining what the feature request is, how it should work,
and why it would be useful, the more likely it'll be able to be add quickly.  Feel free to be vague if you have a general idea that
something might be cool, but you can't think of specifics, but these are less likely to be prioritized.

For issues, bugs, or error stack traces, always include a stack trace if there is one. Otherwise, the more information you can provide in
terms of how to reproduce the problem, the more likely it'll be fixed. If there is something specific about your project, a link to the
GitHub project can be very helpful.

**Comment by DreenDex** [comment]
Same for 2020.1 EAP

**Comment by RedNesto** [comment]
See #676 for 2020.1

About the original issue, this is probably an IDEA bug, the plugin is even compatible with 2019.3.3 Preview.
