### ISSUE TITLE
"cannot resolve symbol 'bukkit'" and "cannot resolve symbol 'JavaPlugin'"

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#680]
Hi.

* Minecraft Development for IntelliJ plugin version: 1.3.2
* IntelliJ version: 2019.3
* Operating System: Windows
* Target platforms: Spigot
* Either where the issue occurs: When I create a new spigot 1.15.2 plugin it says "cannot resolve symbol 'bukkit'" and "cannot resolve symbol 'JavaPlugin'". Idon't do anything it just creates a project and a few seconds later it gives these errors. But I just created a project 2 days ago and it worked perfectly, after I got this errors I uninstalled and installed the plugin, but it's same the plugin I created 2 days ago works but plugin I create now doesn't. Please help me. Thanks

**Comment by MTGPROD** [comment]
What was wrong ?

**Comment by t0g3pii** [comment]
same question here^^
