### ISSUE TITLE
Suggest depends & softdepends in bungee.yml

### ISSUE THREAD

**Issue by Proximyst** [DemonWav/MinecraftDevIntelliJ#682]
For `bungee.yml` files, `depend` & `softdepend` are suggested, as these are the Bukkit values. BungeeCord requires `depends` and `softdepends`; the plural versions of these values.

As the plugin clearly knows `bungee.yml` is applicable for it, it should also adapt to suggest correct values which will result in the plugin functioning as expected.

**Comment by RedNesto** [comment]
The plugin does not suggest anything in the plugin manifests, those are probably from the [bungee-plugin schema](http://json.schemastore.org/bungee-plugin) of SchemaStore, which is wrong.

**Comment by Proximyst** [comment]
Thank you! I've created https://github.com/SchemaStore/schemastore/pull/960.

/closed
