### ISSUE TITLE
[Linux] Minecraft doesn't release mouse cursor at a breakpoint

### ISSUE THREAD

**Issue by realmayus** [DemonWav/MinecraftDevIntelliJ#686]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version: 
2019.3-1.3.3

* IntelliJ version
```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to 
Subscription is active until January 22, 2021
For educational use only.
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-7629-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1925M
Cores: 12
Registry: 
Non-Bundled Plugins: com.demonwav.minecraft-dev
```
* Operating System (this has come up enough times to be important)
Linux (Pop!_OS with GNOME desktop environment)

* Target platforms
Minecraft Forge (1.15.2)

**I saw a commit that addressed this issue (#132), but my mouse still isn't being released when the debugger reaches a breakpoint, thus making debugging impossible because of the missing cursor.**

**Comment by RedNesto** [comment]
That's likely because of LWJGL 3, I'll try to fix it.

**Comment by RedNesto** [comment]
After testing for a good amount of time I found that IntelliJ takes the focus most of the time (on both 2019.3.3 and 2020.1 EAP). There's a few cases where it didn't work (I can't find out why).

Make sure the option `Focus application on breakpoint` is checked in `File | Settings | Build, Execution, Deployment | Debugger`

I still have a fix for newer version of minecraft, but I'm not sure if it is still needed.

**Comment by realmayus** [comment]
Hi, yeah, a fix would be still appreciated. The checkbox has been ticked.

**Comment by DenWav** [comment]
Fixed in 840fde8752b7d6d8e3e69ec8d90211ee6fcc5797.

**Comment by kyleedwardsny** [comment]
This is still a problem for me even though my version of the plugin should have the fix. I am using:

IntelliJ IDEA 2020.1.1, build IC-201.7223.91
Minecraft Development 2020.1-1.3.5
Minecraft 1.15.2

Is there a way to manually trigger the ungrabbing?

**Comment by Earthcomputer** [comment]
> Is there a way to manually trigger the ungrabbing?

The way I did it was by opening the "evaluate expression" dialog (alt + shift + 8), then typing `MinecraftClient.getInstance().mouse.unlockCursor()` and pressing enter. That's fabric mappings, the MCP mappings version is `Minecraft.getMinecraft().mouseHelper.ungrabMouse()`.

However it's very weird that it's not fixed for you, what's your exact OS?

**Comment by kyleedwardsny** [comment]
> However it's very weird that it's not fixed for you

In fairness, it may simply be that the plugin is not loaded/not being activated for this particular mod. How can I check to see if that's the case?

> what's your exact OS?

Linux Mint 18.1 (based on Ubuntu 16.04.)

**Comment by Kyu** [comment]
Ubuntu 18.04.5 I came here from https://github.com/minecraft-dev/MinecraftDev/issues/132   

Alt Shift 8, then Minecraft.getInstance().mouseHelper.ungrabMouse() worked for me in Forge 1.16.4
