### ISSUE TITLE
Using spigradle in spigot

### ISSUE THREAD

**Issue by andret2344** [DemonWav/MinecraftDevIntelliJ#704]
There is an amazing gradle binary plugin Spigradle (https://github.com/EntryPointKR/Spigradle) that gives us `spogot()` repository and other, and `spigot` configuration that can completely replace `plugin.yml` file (it's being generated on build task)

**Comment by DenWav** [comment]
That plugin looks nice, but this project aims to create a base "vanilla" project structure that closely matches the platform's recommended plugin or mod setup, so it's outside of the scope of mcdev to use this.
