### ISSUE TITLE
Older verisons

### ISSUE THREAD

**Issue by CatLoving21** [DemonWav/MinecraftDevIntelliJ#705]
Hello, I want to code a plugin on 1.8  but 1.12 is the oldest verison. I understand  you guys will not add support, But you had it in the past, What verison was the last verison you guys last supported  1.8 on and what verison of intelij would that work on? thats all i ask. thank you

**Comment by CatLoving21** [comment]
For anyone who needs to code in 1.8, You can download a older verison of intelij, then search for this plugin in intelij and you will be able to. intelij version 2016.3.8 worked for me.

**Comment by LeafHacker** [comment]
Why not just download the (old) forge MDK instead of using this plug-in? Surely that's better than using a 4 year old IDE

**Comment by CatLoving21** [comment]
> 
> 
> Why not just download the (old) forge MDK instead of using this plug-in? Surely that's better than using a 4 year old IDE

Im coding plugins not a mod, Unless that does the same thing?

**Comment by RedNesto** [comment]
The platform you are using probably has a documentation explaining how to setup a plugin project,
but that won't change the fact that the plugin will no longer "promote" these versions via its wizard.
