### ISSUE TITLE
Inspection for Entity constructor is no longer correct

### ISSUE THREAD

**Issue by pha3l** [DemonWav/MinecraftDevIntelliJ#707]
The inspection defined here [/mcp/inspections/EntityConstructorInspection.kt](https://github.com/minecraft-dev/MinecraftDev/blob/2020.1/src/main/kotlin/com/demonwav/mcdev/platform/mcp/inspections/EntityConstructorInspection.kt) no longer makes sense for 1.15 Forge builds.  The constructor necessary for registration now should have an `EntityType<T extends Entity>` parameter as well.

MinecraftDev Plugin version: 2020.1-1.3.5 (latest as of this report)
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to Luke Merry
Subscription is active until August 29, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.demonwav.minecraft-dev, com.mallowigi, io.protostuff.protostuff-jetbrains-plugin, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, org.toml.lang
IntelliJ version: Ultimate 2020.1 Build

**Comment by Earthcomputer** [comment]
I think this inspection is no longer really necessary, and should be automatically disabled when mcdev detects you're on a newer Minecraft version.

**Comment by RedNesto** [comment]
Indeed it seems in 1.15 Entity creation is handled in EntityType, via a EntityType.IFactory.
Haven't checked for earlier version, but I guess there aren't many mods for 1.14 anyway.
