### ISSUE TITLE
Auto-reporter failed to submit issue

### ISSUE THREAD

**Issue by zackman0010** [DemonWav/MinecraftDevIntelliJ#712]
I attempted to use the auto-reporter from IntelliJ. Included below is the error message I received and my IntelliJ details.

> Error Submitting Issue: no protocol:  /api.github.com/repositories/42327118/issues?state=closed&creator=minecraft-dev-autoreporter&per_page=100&page=3

> IntelliJ IDEA 2020.1.1 (Ultimate Edition)
> Build #IU-201.7223.91, built on April 29, 2020
> Runtime version: 11.0.6+8-b765.40 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

The issue I was attempting to report appears to related to #550, so I will post details about it there.

**Comment by DenWav** [comment]
Thanks for the error message, that's pretty helpful. I'll look into what that message means in this context.

**Comment by ThexXTURBOXx** [comment]
![grafik](https://user-images.githubusercontent.com/12763829/107875264-314ef880-6ebf-11eb-9888-d7a4ad534f1f.png)
This issue still seems to be around
