### ISSUE TITLE
Please Add 1.8.8 Only Please I Use It It Was The Best Minecraft Server 

### ISSUE THREAD

**Issue by SolDevelop** [DemonWav/MinecraftDevIntelliJ#714]
Why You Removed 1.8.8 There Are a lot Of Servers Works By 1.8.8 I Want Develop Plug-ins For My Server And My Server Very Big And it have a lot of plugins I can’t change it

**Comment by TheFruxz** [comment]
Yes, please make the 1.8 available. He is right about the fact that many servers **still** rely on 1.8 (and 1.8.8).

**Comment by RedNesto** [comment]
As stated too many time already on the Discord server, we will not bring back support for those versions. Nothing prevents you from setting up your project manually though, or even use this plugin's wizard to create the project and downgrade the version yourself.

**Comment by SolDevelop** [comment]
Pls I need this verison

**Comment by SolDevelop** [comment]
can you send me an only verison of your plugin it support 1.8.8

**Comment by SekoiaTree** [comment]
Dude, this is git. You can seriously just go through the old versions
