### ISSUE TITLE
Can You Give Me Pls The Old Verison Of Your Plugin That Support 1.8.8 pls

### ISSUE THREAD

**Issue by SolDevelop** [DemonWav/MinecraftDevIntelliJ#715]
I NEED IT PLS PLS PLS PLS PLS PLS

**Comment by SekoiaTree** [comment]
Dude. Stop.

**Comment by andret2344** [comment]
@SolDevelop You can just create the 1.12 plugin using this plugin and manually change the version of bukkit/spigot version in `build.gradle` file to any needed of following: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot-api/, e.g.
```
compileOnly group: 'org.spigotmc', name:'spigot-api', version: '1.8.8-R0.1-SNAPSHOT'
```
And this will be plugin for 1.8.8 as you wish.

It **really** doesn't need to be supported by the IntelliJ plugin. Even more, you don't even need to use this plugin to set up any plugin project on your own. So stop creating issues with this request as developer said they won't do it, period.

**Comment by FinnT730** [comment]
"I need 1.8"
well.... update to later versions, and have more fun!
