### ISSUE TITLE
Generation of a non-existing "api-version".

### ISSUE THREAD

**Issue by LB45440078L** [DemonWav/MinecraftDevIntelliJ#721]
**Plugin build**: Minecraft Development build 2020.1-1.4.0
**IntelliJ build**: IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
**Operating System**: macOS Catalina 10.15.3 19D76 x86_64 (Hackintosh)
**Target platform**: Paper 1.15.2

Issue:
When creating a brand new project the **plugin.yml** in the src/main/resources has an invalid api-version '1.15.2'. This should be instead replaced with '1.15'.
![immagine](https://user-images.githubusercontent.com/29604693/84491639-22b3a000-aca5-11ea-8444-442568ba2653.png)

**Comment by RedNesto** [comment]
This is already fixed by #717 in nightly builds.
