### ISSUE TITLE
Mixin inspections should take the bytecode of the target class into account

### ISSUE THREAD

**Issue by Earthcomputer** [DemonWav/MinecraftDevIntelliJ#724]
Only using the source code causes a multitude of issues and inconsistencies. The mixin module should be refactored to allow for looking in the bytecode of the target class rather than the source code. There would need to be a way to map between elements of the source code and elements of the bytecode, for code navigation purposes. This is possible using a form of intermediate decompiler representation.

This would fix/would enable us to fix the following issues:
- Various issues where the target method is unknown (#355)
- Making "get mixin target reference" always accurate (#659)
- Making `@At` references target properly (#135)
- Making it easier to support similar `@At`-style references in the future (#373)
- Visualizing mixins directly in the target class (#137)
- Visualizing overwrite diffs in a decompiler-independent way, without need for local variable name mapping (#152)

I understand there was already an attempt at some of these in a refactor that was started a couple of years ago. Not being entirely familiar with that code, would it be better to try and pick up that refactor again for this, or start afresh?

**Comment by DenWav** [comment]
Anything we do from now on should be done fresh, old branches that are a couple years old aren't very useful. I remember finding it annoyingly difficult to find the bytecode of a class last time I looked at this, but I didn't work on this long enough, I probably just missed an API somewhere in IntelliJ. I'm definitely interested in doing this though.

**Comment by Earthcomputer** [comment]
#1221
