### ISSUE TITLE
Entity constructor warning on abstract entity

### ISSUE THREAD

**Issue by Novarch129** [DemonWav/MinecraftDevIntelliJ#725]
Minecraft version: 1.15.2
IntelliJ version: 2019.3.3 Community
OS: Windows 10
Target platform: Forge 31.2.20

The "entity requires a constructor with one parameter of type net.minecarft.world.World" should not appear on **abstract** classes that extend Entity, as they cannot be instantiated.

**Comment by Earthcomputer** [comment]
Duplicate of #707, and already fixed, please update the plugin.
