### ISSUE TITLE
Wrong auto-generation of api-version in spigot plugins

### ISSUE THREAD

**Issue by WOLFI3654** [DemonWav/MinecraftDevIntelliJ#728]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version **2020.1-1.4.1**
* IntelliJ version **IntelliJ IDEA 2020.1.2 (Ultimate Edition)** Build #IU-201.7846.76, built on June 1, 2020
* Operating System (this has come up enough times to be worth noting) **Windows**
* (optional) Target platform, if relevant **Spigot**

The auto-generated plugin.yml contains a wrong api-version.
When creating a new plugin for the 1.15.2 for example, the tool sets the api-version in plugin.yml to "1.15.2" which is not correct. The api-version field only accepts major versions like "1.15", "1.16" etc.

Furthermore, plugin.yml autocomplete is broken.

**Comment by RedNesto** [comment]
This is already fixed, and I confirm it is fixed for me in 1.4.1 for 2019.3, 2020.1 and 2020.2. Make sure you are up to date.

**Comment by WOLFI3654** [comment]
Thank you. But the autocomplete still appears to be broken.

**Comment by RedNesto** [comment]
Oh forgot that part. The plugin never added completion to the plugin.yml so that's not on our end.

**Comment by WOLFI3654** [comment]
Oh. I remember that it used to. At least I had autocompletion for the plugin.yml in the past with your plugin.

**Comment by RedNesto** [comment]
It may come from JSON schemas, or an IDEA built-in contributor.

I think the original issue is resolved, and the completion thing has never been part of the plugin so I'll close it.
