### ISSUE TITLE
Spigot support for 1.8.8

### ISSUE THREAD

**Issue by Marcelektro** [DemonWav/MinecraftDevIntelliJ#739]
Hello. Im using your plugin MC Dev. It works perfectly fine for Bungeecord, however, I would need support for 1.8 spigot in order to use it in Spigot developement.
Is there a chance of adding support to it?
Regards

**Comment by RedNesto** [comment]
https://github.com/minecraft-dev/MinecraftDev/issues/727#issuecomment-650534713
Duplicate of #727
