### ISSUE TITLE
Add 1.8 support

### ISSUE THREAD

**Issue by Nuckerr** [DemonWav/MinecraftDevIntelliJ#747]
I personally code plugins in Minecraft version 1.8. I use the mc dev plugin to make these projects a bit easier to create. The way around to make your project 1.8 is to do it in the pom file. I would really like it if you added 1.8+ support.

**Comment by RedNesto** [comment]
No, won't happen, 1.8 is long dead. You can still edit the version in your pom file as you said, but it won't change.
