### ISSUE TITLE
mcmod.info is not being found by forge

### ISSUE THREAD

**Issue by Appw0** [DemonWav/MinecraftDevIntelliJ#748]
I am running Minecraft Development 2020.1-1.4.2 with IntelliJ 2020.1.3 on Windows 10. I am trying to build for Forge 1.12.2-14.23.5.2854.

This is reproducible with a fresh setup, with no alterations to code or file structure whatsoever. I'm getting no errors, but in Forge's log, after finding the mod, Forge logs that it found no mcmod.info file. This is only happening with the runClient run configuration. Building the jar and plopping it in a separate Forge client does not have this issue.

If this is something on my end, or something resulting from improper installation, please let me know.

**Comment by RedNesto** [comment]
I've created a new Forge project with the wizard, exact same version of IDEA, forge and the plugin, and it works fine. Try to regenerate the run configurations with `gradlew genIntellijRuns`.

**Comment by Appw0** [comment]
After successfully regenerating the run configurations, it appears nothing has changed. Is there a log I can send that may have more information?

**Comment by RedNesto** [comment]
Well I doubt this is an issue with the plugin in the first place, and 1.12.2 is no longer supported by forge.

You can still send the whole log, can't promise anything though.

**Comment by Appw0** [comment]
Well, after clearing Gradle's cache and rebuilding the dependencies, I'm now getting an error.
`Could not find net.minecraftforge:forge:1.12.2-14.23.5.2854_mapped_stable_39-1.12.
  Searched in the following locations:`
Followed by a list of broken urls.

**Comment by RedNesto** [comment]
You did it wrong then, make sure you are not using the gradle daemon. Clear the build directory too.

**Comment by Appw0** [comment]
You're correct, it's not something with your plugin. I've now tried running a Forge MDK, and am still getting no mcmod.info. Sorry for wasting you time. I've still got a lot to learn about Forge's modding environment.
