### ISSUE TITLE
plugin.yml getting JSON schema error

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#751]
Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version: 2020.1-1.4.2
* IntelliJ version: 2020.1.4
* Operating System (this has come up enough times to be worth noting): Windows 10
* (optional) Target platform, if relevant: Spigot/Bukkit
  * E.g., Bukkit, Forge, Mixin, etc

Always include a stack trace if there is one. Otherwise, the more information you can provide in terms of how to reproduce the problem, the more likely it'll be fixed. If there is something specific about your project, a link to the GitHub project can be very helpful.

When I create a new spigot project, it auto generates a plugin.yml, but it doesn't have the auto completing and in the bottom right it says "JSON schema error". If I disable the plugin the error goes away and it works as intended.
![image](https://user-images.githubusercontent.com/68562239/88436537-56600a80-cdb9-11ea-840d-a8ae031e8828.png)

**Comment by RedNesto** [comment]
Hi, the plugin has nothing to do with JSON schemas nor completion in the .yml files (that comes from schemas btw).

Also I can't reproduce this, no schema error and completion is fine on a newly generated spigot 1.16.1 project.

Could you send you IDE logs after opening the spigot.yml that has the schema error? I can still search for an error related to mcdev.

**Comment by ghost** [comment]
I _think_ [this ](https://hastebin.com/unihehugiz.pl)is the log you want? [Also included a video](https://www.dropbox.com/s/fatmkvr7axkxjib/1MbJl92xkb.mp4?dl=0)

**Comment by RedNesto** [comment]
This is indeed the file I needed, unfortunately it does not show anything related to your problem.

Have you clicked the schemas widget when it displays the error? It may help you fix it or at least tell what's wrong.

**Comment by ghost** [comment]
When I hover over it it says "File is not a schema", and if I click it I can change the schema to something else.  I followed the error in the log to where the schema is supposed to be and saw this, all of which are identical with the schema except the last one which is empty.
![explorer_7h49HhVYQu](https://user-images.githubusercontent.com/68562239/88464503-3dfef700-ce70-11ea-8dfe-f349bc0c2664.png)
I then disabled the plugin and did it again, and the folder looked like this
![explorer_cljxeIW0fO](https://user-images.githubusercontent.com/68562239/88464527-6e469580-ce70-11ea-8b14-03f820b8fcd2.png)

I saved a copy of this file and just manually pointed it there myself and that seems to be working?

**Comment by RedNesto** [comment]
Well, I have no idea why the plugin seems to interfere with this. I didn't expect schemas to be stored there.

I hope it's fixed for good because I can't help you further on this.
