### ISSUE TITLE
Mod not found while running the game on the default setup done by the plugin

### ISSUE THREAD

**Issue by sidambhire** [DemonWav/MinecraftDevIntelliJ#752]
Minecraft Development for IntelliJ plugin version: 2020.1-1.4.2
IntelliJ version: 2020.1.2
Operating System: Manjaro Linux
Target platform: Forge:1.12.2-14.23.5.2854

I just made the mod from the `New Project` option. After the code is done configuring, the mod is missing from the game when it runs. Please help!

[Error Log](https://gist.github.com/sidambhire/e47eb6d2a808fac4fb9e42cc86bc0b74)

**Comment by RedNesto** [comment]
Read the logs... the mod id must not contain uppercase characters.
The plugin should have caught that before creating the project though.

**Comment by sidambhire** [comment]
Never mind, it worked!
