### ISSUE TITLE
Add colour support for Adventure

### ISSUE THREAD

**Issue by me4502** [DemonWav/MinecraftDevIntelliJ#754]
The Kyori adventure library is a popular text library and is used in many popular platforms (such as the new API8 of Sponge). Adding colour support for this library would be beneficial.

https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/format/TextColor.java
https://github.com/KyoriPowered/adventure/blob/master/api/src/main/java/net/kyori/adventure/text/format/NamedTextColor.java

**Comment by RedNesto** [comment]
Implemented in 11efb2c631bc81ce1ec64b5d04e585abee7e48f0
