### ISSUE TITLE
3 Gradle import tasks running after project is opened

### ISSUE THREAD

**Issue by Leo40Git** [DemonWav/MinecraftDevIntelliJ#757]
* **Minecraft Development for IntelliJ plugin version:** 2020.2-1.5.0-177
* **IntelliJ version:** Community 2020.2
* **Operating System:** Windows 10 20H2 (build 19042.421)
* **Target platform:** Fabric

After opening a Fabric project, 2 Gradle imports occur in parallel. After those two finish and the project is seemingly set up, *another* Gradle import task spins up.
This doesn't really break anything, the project itself is loaded correctly, it's just somewhat... perplexing.

**Comment by DenWav** [comment]
Does this happen after project creation when you re-import the Gradle project? Or just when the project is created? I'm not sure what can be done here but I can investigate if it's still happening. If it's a one time thing then I'm not that worried about it.

**Comment by Leo40Git** [comment]
It happened after I opened a freshly-created Fabric project, IIRC. It hasn't happened again, though.

**Comment by DenWav** [comment]
Newly created projects have a few Gradle tasks to run to finish setting up the project which likely causes a couple more imports than normal. If it only happens for new project creation then I'd say this probably isn't an issue.
