### ISSUE TITLE
Entrypoint issues with Fabric

### ISSUE THREAD

**Issue by ramidzkh** [DemonWav/MinecraftDevIntelliJ#759]
* Minecraft Development for IntelliJ plugin version: **2020.2-1.5.0**
* IntelliJ version: **IU-202.6397.94**
* Operating System (this has come up enough times to be worth noting): **Windows**
* Platform: **Fabric**

- [x] Refactoring classes/methods does not modify fabric.mod.json
- [x] Method references mark the method as used, but not the class
- [x] Autocompleting the entrypoint is not possible

**Comment by Earthcomputer** [comment]
Hmm, it looks like the 3rd one doesn't happen in a mixin config file either.
