### ISSUE TITLE
Forge Builld Error

### ISSUE THREAD

**Issue by BingZi-233** [DemonWav/MinecraftDevIntelliJ#774]
* 2020.2-1.5.0
* 2020.2.1
* Windows 10 1903 18362.1016
*  Forge
## First:
> * Cause: error in opening zip file
## Second:
> * A problem occurred configuring root project 'FirstMod'.
> * Invalid patcher dependency: net.minecraftforge:forge:1.12.2-14.23.5.2854:userdev3

**Comment by aoxiangtianji** [comment]
Same problem. Is there a solution?

**Comment by RedNesto** [comment]
It doesn't look like a problem with mcdev, might happen because Gradle can't download a file properly.

**Comment by aoxiangtianji** [comment]
How can I reset gradle?

RedNesto <notifications@github.com> 于2020年9月12日周六 下午7:33写道：

**Comment by RedNesto** [comment]
You can try deleting you gradle home folder (make sure you don't have properties in it), you'll need to download everything again though.

I can only guess but I think it can happen if your network has limited access to wherever it tries to download the file.

Anyway this is probably not an mcdev issue, if I guessed right other chinese modders might help you much better than me with it.

**Comment by aoxiangtianji** [comment]
Thank you for your help!

RedNesto <notifications@github.com> 于2020年9月12日周六 下午7:41写道：
