### ISSUE TITLE
Forge Packet class generator

### ISSUE THREAD

**Issue by Tom-The-Geek** [DemonWav/MinecraftDevIntelliJ#775]
When I was working on a project recently, I realised that I was repeating myself multiple times every time I wanted to create a new packet and I decided to create an InteliJ template for an empty packet class.

I was wondering if this would be something the MinecraftDev plugin would be interested in including, and if it is, I will be happy to make a pull request to add it. If anyone else also has any idea for other templates I would be happy to include them.

The packet template is in a gist here: https://gist.github.com/Geek202/5f8354e120b4756ae9025688a7c5be0e

**Comment by DenWav** [comment]
Seems like a good feature, apologies for the inactivity, I'm not able to stay as active as I'd always like to be.

**Comment by Tom-The-Geek** [comment]
No worries, I think the reason I closed this was because #779 (the PR I made with these ideas) was merged and I felt there wasn't really a need for it to remain open

**Comment by DenWav** [comment]
Ah gotcha.
