### ISSUE TITLE
Dynamic add resources

### ISSUE THREAD

**Issue by MDReal32** [DemonWav/MinecraftDevIntelliJ#780]
# At Russian. Original...
Добрый день! Мой идея поможет в разработке ассетов. Суть очень просто. Когда создается наследования например от класса Блок автоматический создается нужные ассеты в заданном именем. Или добавите новую кнопну чтобы создать.

# Translated by Google Translate...
Good day! My idea will help in developing assets. The essence is very simple. When inheritance is created, for example from the Block class, the necessary assets are automatically created in the specified name. Or add a new button to create one.

**Comment by DenWav** [comment]
I'm curious exactly what this would look like, if anyone has any ideas or input?
