### ISSUE TITLE
Major Issues at creation

### ISSUE THREAD

**Issue by TheFruxz** [DemonWav/MinecraftDevIntelliJ#783]
> Please include the following information in all bug reports:
> 
> * NEWEST Version
> * 2020.3 EAP
> * Windows 10 Pro Insider Preview, Version 2004, Build 20206.1000, Windows Feature Experience Pack 120.22800.0.0
> 

---

The automatic completion of the input fields is completely faulty and enters wrong and duplicated values in the wrong places. Packages/Paths do not match the input values and upper/lower case is converted in Auto-Complete

**Comment by RedNesto** [comment]
Not enough information provided, and might have already been fixed.
