### ISSUE TITLE
Section Symbol code inserter for Strings

### ISSUE THREAD

**Issue by Moire9** [DemonWav/MinecraftDevIntelliJ#784]
So, I used to have the section-symbol color codes memorized. However, for a long time I didn't do anything related to Minecraft, so I forgot them. I am getting back into development, and while I have most of the codes memorized, some of them I don't. Additionally, since I am on Linux, I can't just do an `ALT + 21` to insert a section symbol, I have to search it up (yeah there's probably some sort of numpad program I am lazy). So I thought it would be a nice feature, if the plugin had a option (which you could assign a keyboard shortcut to with IJ or access with the double-shift menu) to insert a color code. It brings up a menu like the typo dictionary one, which you can select from one of the colors or formats, and upon pressing enter it inserts the section symbol and code at the caret's position.  
<img width="124" alt="image" src="https://user-images.githubusercontent.com/31591796/94512022-d77bb980-01cf-11eb-9863-a0ff104dac95.png">
Like this. Each of the options could say the color, and maybe the code too in greyed out parentheses, so you can learn them. For example, `Dark Red (§4)`, or `Dark Blue (§9)` or `Reset (§r)`. 

Additionally, you could have two settings for it, which control if the letter ones are inserted as capitals or lowercase (this could be represented in the aforementioned greyed out parentheses). Maybe pressing shift+enter when selecting one of the options will insert the opposite of your capitalization scheme. 

There is also some disagreement over the naming of some of the colors. Some call `§4` Dark Red and `§c` Red, while others call `§4` Red and `§c` Light Red. So maybe an option to change which one is the primary color and if the other one is Light or Dark would be appreciated by some people.

**Comment by ChachyDev** [comment]
+1

**Comment by zml2008** [comment]
The section symbol has been deprecated since MC 1.7.2, and is for the most part no longer used in modern minecraft.

(Also every fixed colour has an official name defined by mojang, so there is no disagreement 😛)

**Comment by Earthcomputer** [comment]
You aren't supposed to directly use the section symbol. On every platform there is an enum of colours whose `toString` method returns the section code, so you are supposed to use for example `ChatColor.RED + "This is an error!"`.

**Comment by Moire9** [comment]
What? Really? But that makes the code so much larger especially when you have to use a lot. And how are you supposed to color item names and text output and whatnot?

**Comment by Earthcomputer** [comment]
The ChatColor enum is literally no different than adding the section sign yourself, it produces exactly the same string, so I'm not sure what your second argument is.
And you should be optimizing your code for readability, not for number of keystrokes.

**Comment by itsTyrion** [comment]
> You aren't supposed to directly use the section symbol. On every platform there is an enum of colours whose `toString` method returns the section code, so you are supposed to use for example `ChatColor.RED + "This is an error!"`.
```java
"§cCorrect usage§7: §c/coins §7<§cname§7> [§a add §7|§e set §7|§c remove §7|§4 reset §7]"
"" + RED + "Correct usage" + GRAY + ":" + RED + " /coins " + GRAY + "<" + RED + "name" + GRAY + "> [ " + GREEN + "add" + GRAY + " | " + RED + "remove" + GRAY + " | " + DARK_RED + "reset" + GRAY + " ]"
```
Eww. And that's with static * import. Yes, I used a lot of color codes.

When you use Kotlin (you should^^), the length is barable, though. If you don't like writing a ton of code to get the job done, you'll probably love it. If you know Java and have some experience with JS, you'll feel home right away. IDEA can do a relatively good conversion with CTRL-Alt-Shift-K
```kotlin
"${RED}Correct usage$GRAY:$RED /coins $GRAY<${RED}name$GRAY> [$GREEN add$GRAY |$RED remove$GRAY |$DARK_RED reset$GRAY ]"
```
(This actually made me question why I still use the § codes.. Old habits die hard, I guess)

**Comment by Hubry** [comment]
I'd personally argue that there is no place for making a rainbow in commands like this. Vanilla commands returning an error give red, commands returning successfully give white. Not to mention, the current vanilla standard way is much more verbose than this - the most current pattern is like 
```java
new TranslatableText("lang.key.with.placeholders.here", 
    new TranslatableText("other.key").formatted(Formatting.RED), 
    new TranslatableText("yet.another.key").formatted(Formatting.RED))
.formatted(Formatting.GRAY);
```
You can always define helper methods to wrap a part in a color if you have to keep it short.

**Comment by Earthcomputer** [comment]
Let's not forget this option:
```java
String.format("%sCorrect usage%s: %s/coins %s<%sname%s> [%s add %s|%s set %s|%s remove %s|%s reset %s]", RED, GRAY, RED, GRAY, RED, GRAY, GREEN, GRAY, RED, GRAY, RED, GRAY, DARK_RED, GRAY)
```
Or this option:
```java
"REDCorrect usageGRAY: RED/coins GRAY<REDnameGRAY> [GREEN add GRAY|RED set GRAY|RED remove GRAY|DARK_RED reset GRAY]".replace("DARK_RED", "" + ChatColor.DARK_RED).replace("RED", "" + ChatColor.RED).replace("GREEN", "" + ChatColor.GREEN).replace("GRAY", "" + ChatColor.GRAY)
```
Or a helper function to that effect.
There are many things you can do to make that code less verbose, though I would even argue that your string concatenation is more readable than the section signs, at least you know what colour everything is if you haven't memorized the colour codes.

**Comment by Moire9** [comment]
I suppose that the repository collaborators voicing their lack of support for the idea counts as denying it.

**Comment by Earthcomputer** [comment]
Yes, use the named constants your platform provides.

**Comment by DenWav** [comment]
Apologies for never commenting, lots of things going on and I'm not always good about managing my GitHub notifications. I've unsubscribed from a lot of bigger repos so maybe I can get better at it. I do agree using the proper mechanisms for the platform you're using is the better option, but no I didn't mean to simply ignore this issue.
