### ISSUE TITLE
ChatColor preview for Kotlin

### ISSUE THREAD

**Issue by itsTyrion** [DemonWav/MinecraftDevIntelliJ#785]
ChatColor preview next to the line numbers works really well, as long as you're writing Java.
Would it be possible to do the same thing for Kotlin?
Edit: I found a plugin that does this for hex colors, including on Kotlin, so it _should_ be possible

**Comment by RedNesto** [comment]
Fixed in 4ca621591ceb0ead18885c617cf9302117a3f9b9
