### ISSUE TITLE
fabric.mod.json not being created

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#786]
Minecraft Development for IntelliJ plugin version: 2020.2-1.5.1
IntelliJ version: 2020.2.2 community
Operating System: Windows
Target platform: fabric

The fabric.mod.json file is not being created which means  the mod is not being loaded into Minecraft whenever I try to run it

**Comment by RedNesto** [comment]
Works for me, tested with the same IDE & plugin version. Make sure to not interrupt background tasks and wait until the end before doing anything, just in case.

Could you retry and upload the IDE log file if it doesn't work correctly ?

**Comment by ghost** [comment]
I tried again and this time the file was successfully created. I don't know what happened the first time. I just waited and did nothing.
