### ISSUE TITLE
Fabric project creation broken

### ISSUE THREAD

**Issue by Leo40Git** [DemonWav/MinecraftDevIntelliJ#789]
* **Minecraft Development for IntelliJ plugin version:** 2020.2-1.5.1-194
* **IntelliJ version:** 2020.2
* **Operating System:** Windows 10
* **Target platform:** Fabric
* **Stack trace:** https://pastebin.com/76NLCnmx

Tried to create a new Fabric project in an existing folder (folder was pretty much empty outside of a .git folder), and then this happened. The mod initializer file was extremely incomplete, too:
```java
package adudecalledleo.speedtrading;public class SpeedTrading {
}
```

**Comment by BoogieMonster1O1** [comment]
Can confirm
Plugin version - 2020.2-1.5.1
Idea version - 2020.2.3

```java
package example;
@net.fabricmc.api.Environment(net.fabricmc.api.EnvType.CLIENT)
public class Example {
}
```
this happened when making a client mod initializer

should probably also mention that this happened when i chose Sponge and Fabric

**Comment by RedNesto** [comment]
Can't reproduce, IDEA 2020.2.3, same plugin version.

Make sure you don't start or stop anything until it's done.

**Comment by Leo40Git** [comment]
I didn't touch it for the duration of the process.
IntelliJ popped up a "do you want to add this file to the git repository" prompt, maybe that interrupted it?

**Comment by RedNesto** [comment]
That's unlikely, and it worked flawlessly on an empty git repository on my end.
Could you send the whole IDEA log ? There's probably an error right before the one blamed on MCDev.

**Comment by Leo40Git** [comment]
*Entire* idea.log: https://gist.github.com/Leo40Git/d0f053569572612aa3a38c138fffb281
Warning: it's huge.

**Comment by Earthcomputer** [comment]
Could it be this?
```
Caused by: java.lang.ClassNotFoundException: com.demonwav.mcdev.inspection.IsCancelledInspection
```
That inspection was added recently

**Comment by RedNesto** [comment]
The inspection isn't the issue.

Did you update the plugin and directly create the project without restarting ?

**Comment by Leo40Git** [comment]
Yes. IntelliJ didn't tell me to restart so I assumed things would be fine.

**Comment by RedNesto** [comment]
Well it isn't the case, for some reason I haven't found yet the plugin can't be reloaded. That's the issue.

I guess the only way to avoid that is to mark the plugin as not dynamic, IIRC there's a property we can add in the plugin descriptor for that. It's sad but that's the only way to make sure this kind of issue doesn't happen until we find what's wrong.

**Comment by RedNesto** [comment]
Just to be sure this isn't only on my machine, does the project wizard work correctly after a restart ?

**Comment by Leo40Git** [comment]
Yep, works after reset.

**Comment by RedNesto** [comment]
Ok thank you, I'll open a separate about the reloading issue.
