### ISSUE TITLE
Latest Mapping's do not show when creating new forge project.

### ISSUE THREAD

**Issue by dmodoomsirius** [DemonWav/MinecraftDevIntelliJ#796]
Please include the following information in all bug reports:

Plugin version: 2020.2-1.5.1
IntelliJ version: 2020.2.3
OS version: Windows 10
Target Platform: Forge

When trying to create a new Forge Project All the mappings are red. I scrolled through the Entire mapping list and there is none avaiable for the newer versions of Minecraft. I manually downloaded the MDK to see the latest Mappings that are in there latest it selects is stable-60 and the highest snapshot version it shows is snapshot_20201115 for minecraft 1.16.4 forge version 35.0.17. Latest snapshot is snapshot_20201028-1.16.3.

**Comment by RedNesto** [comment]
I think the mappings arent uploaded to their usual repo so the plugin can't find them. Daily snapshots are still made but for 1.15.2 only.

I will see how to fetch snapshots for 1.16.+ as a workaround, given MMS is far from ready last time I checked.

**Comment by Tom-The-Geek** [comment]
Currently, the temporary mappings are uploaded to the normal repo (`https://files.minecraftforge.net/maven/`), but are not listed in the normal MCPBot metadata JSON ([this](http://export.mcpbot.bspk.rs/versions.json)). However, tterag maintains file with the same structure, but only the temporary versions, on his site [here](https://assets.tterrag.com/temp_mappings.json). This file can be merged with the standard one from MCPBot to create a set with all the available mappings.

[Here](https://github.com/Geek202/McBotV2/blob/master/src/main/java/me/geek/tom/mcbot/mappings/MappingsApiUtils.java#L29-L49)'s how I do the metadata merging in my Discord bot, but it may not be perfect.

**Comment by RedNesto** [comment]
Thank you for motivating me to do this change, and thank you @Geek202 for letting me know about tterrag's manifest list, this is much cleaner than hardcoding versions.
