### ISSUE TITLE
Repository URL dont work for Spigot/Bungee Plugins

### ISSUE THREAD

**Issue by Elias177Dev** [DemonWav/MinecraftDevIntelliJ#799]
* Minecraft Development 2020.3-1.5.1
* IntelliJ IDEA Ultimate 2020.2.4
* Windows 10
* BungeeCord and Spigot

When i create a new Project via Minecraft Development in Maven than it comes this Error and the BungeeCord API wasn't downloaded:

`Cannot resolve net.md-5:bungeecord-api:1.16-SNAPSHOT`

And when i press "Run Configuration -> build"

It comes this error:

`The POM for net.md-5:bungeecord-api:jar:1.16-SNAPSHOT is missing, no dependency information available`

**Comment by RedNesto** [comment]
I'm pretty sure the repositories are correct, the problem is that the [bungeecord's version scheme changed](https://oss.sonatype.org/#nexus-search;gav~net.md-5~bungeecord-api~~~~kw,versionexpand) for 1.16 and MCDev doesn't take it into account.
