### ISSUE TITLE
Plugin incompatible with lastest Intellij update

### ISSUE THREAD

**Issue by thanhminhmr** [DemonWav/MinecraftDevIntelliJ#800]
* Minecraft Development for IntelliJ plugin version: 2020.3-1.5.1
* IntelliJ version: IntelliJ IDEA 2020.2.4 (Ultimate Edition) Build #IU-202.8194.7, built on November 24, 2020
* Operating System: Windows 10 1909 x64

![image](https://user-images.githubusercontent.com/31412085/100829547-35f53a80-3494-11eb-978d-135d3c450fb6.png)

**Comment by RedNesto** [comment]
Seems like a problem on your end, you use IDEA 2020.2 but somehow the installed plugin version is for 2020.3.
Try reinstalling the plugin, the IDE should pick the correct version (should be [2020.2-1.5.1](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/stable/97704)).

**Comment by thanhminhmr** [comment]
I uninstall and reinstall the plugin from the Plugin market and now the IDE correctly picks up version 2020.2-1.5.1 for the plugin.
Somehow IDEA decided to update the plugin to the wrong version while updating itself, and somehow I didn't think about this possiblity at all.
Hope this helps someone with similar issue in the future.
