### ISSUE TITLE
Something about "Invalid range specified: (1, 0);"

### ISSUE THREAD

**Issue by gracen-writes-code** [DemonWav/MinecraftDevIntelliJ#801]
Version: 2020.3-1.5.1
IntelliJ Version: 2020.3
Windows 10 version 20H2 (Build 19042.685)
Platform: Forge

Stack trace (I don't know how to use spoilers):
https://pastebin.com/yUgeJLdt

I don't know what the heck this is, but it doesn't do anything except pester me with notifications. I don't know if this is something worth noting and/or fixing, but I felt that it would be worth it to bring up to you.

**Comment by DenWav** [comment]
How often does it happen, and does it happen when you have a particular file or open?

**Comment by gracen-writes-code** [comment]
This happens every time I restart Intellij, and I don't think that it has to do with what file is open.

**Comment by Earthcomputer** [comment]
Can you share you translation file (en_us.json)?

**Comment by gracen-writes-code** [comment]
Here it is:
(Sorry I haven't been active on this issue, I mainly code for myself and thus don't use github).
```
{
  "itemGroup.general": "Antiquark (Use JEI for items, it's better)",
  "block.antiquark.metal_block_copper": "Copper Block",
  "block.antiquark.metal_block_tin": "Tin Block",
  "block.antiquark.metal_block_lead": "Lead Block",
  "block.antiquark.metal_block_silver": "Silver Block",
  "block.antiquark.metal_block_lithium": "Lithium Block",
  "block.antiquark.metal_block_cobalt": "Cobalt Block",
  "block.antiquark.metal_block_silicon": "Silicon Block",
  "block.antiquark.metal_block_electrum": "Electrum Block",
  "block.antiquark.metal_block_invar": "Invar Block",
  "item.antiquark.ingot_copper": "Copper Ingot",
  "item.antiquark.ingot_tin": "Tin Ingot",
  "item.antiquark.ingot_lead": "Lead Ingot"
  //this goes on for a while, all of it follows the same pattern
}
```

**Comment by Earthcomputer** [comment]
Maybe you should have gisted the whole thing, you ommitted precisely the important information... Anyway, I think it's because of an empty string in the json somewhere, mcdev needs to be fixed to handle that.

**Comment by gracen-writes-code** [comment]
Oh well, sorry about that. Anyways, I can't seem to recreate it anymore. Hopefully this hasn't been too much of a bother.
Here's a full pastebin if you think it would be helpful: https://pastebin.com/ZxHuY0QC
