### ISSUE TITLE
Shadow generation that adds the abstract modifier to mixin class does not remove the final modifier from said class

### ISSUE THREAD

**Issue by necauqua** [DemonWav/MinecraftDevIntelliJ#812]
plugin version: `2020.3-1.5.2`
intellij version: `2020.3 (build #IU-203.5981.155)`

The title pretty much says it - I have a setting that all new classes are final by default and so are my mixin classes until I use the shadow generation from autocompletion - it adds the abstract modifier to the class, but does not remove the existing final modifier and it then has to be removed manually each time because having them both is obviously an error.

**Comment by Earthcomputer** [comment]
Do you mean accessor / invoker generation? Shadows don't generate classes.

**Comment by Earthcomputer** [comment]
Ah, lol. Does this also affect accessor/invoker generation?

**Comment by DenWav** [comment]
> Ah, lol. Does this also affect accessor/invoker generation?

It can't, accessors and invokers are interfaces.
