### ISSUE TITLE
Edit default files

### ISSUE THREAD

**Issue by dkim19375** [DemonWav/MinecraftDevIntelliJ#813]
I don't know if this is possible, but here's a feature request: to make the files generated (such as `build.gradle`) configurable.
So if I set it to something else, every time I made a new project, it would use the `build.gradle` that I put in instead of the current one (in this github repository).

**Comment by RedNesto** [comment]
You can already change it because we use IntelliJ's built-in templates, in the settings go to `File | Settings | Editor | File and Code Templates` in the `Other` tab, every template the plugin adds can be found under `Minecraft`.

**Comment by dkim19375** [comment]
oh! Thanks!
