### ISSUE TITLE
An error occured 

### ISSUE THREAD

**Issue by whitebear60** [DemonWav/MinecraftDevIntelliJ#814]
* Minecraft Development for IntelliJ plugin version: 2019.3-1.5.2
* IntelliJ version: 2019.3.5 (build #IC-193.7288.26)
* Operating System: macOS 10.10 Yosemite
* Target platform: Fabric

I haven't seen when it is occured, I have noticed the red error icon in the bottom right corner of IDEA. Probably it is occured when I edited my lang file, but I don't know exact when it occured.

Stack trace: https://hastebin.com/agigovixux.apache

**Comment by whitebear60** [comment]
Probably, this issue is duplicate of #801

**Comment by Earthcomputer** [comment]
Yes, duplicate of #801
