### ISSUE TITLE
Manifest attribute "version" is null.

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#818]
Minecraft Development for IntelliJ plugin version: 2020.3-1.5.2

* IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)
* Operating System (this has come up enough times to be worth noting): Windows 10 Home
* Target platform
  * Sponge + Forge
* Minecraft Version: 1.12.2

**The Issue:**

Upon building a new project with Sponge and Forge selected, Gradle errors out with this:
A problem occurred evaluating project ':spongeforgedevelopmentlibraries-forge'.
> The value of a manifest attribute must not be null (Key=Implementation-Version).

spongeforgedevelopmentlibraries is the quick test project I made to test if it can be reproduced. and well, it was.

Exact details as to project creation steps with the amazing name of "TestTestTestProject":

1. New Project
2. Select Forge and Sponge
3. Group id with no capital letters in it (for example, test.test.test
4. Artifact id: testid
5. version: left as default.
Sponge Setup:

1. Plugin Name: TestId
2. Main class name: test.test.test.testid.TestidSponge
3. Sponge API version: 7.3.0
4. All optional left blank.

Forge setup:

1. Mod Name: Testid
2. Main class name: test.test.test.testid.TestidForge
3. Forge version: 14.23.5.2855
4. MCP version: stable_39
5. Minecraft Version: 1.12.2
6. All optional left blank.

Project Setup:

1. Project Name: TestTestTestProject
2. Project Location: Wherever you want... I highly doubt that's the issue :D
3. More Settings left as default.

Let Gradle do its stuff... and you'll be left with the same error.

**Comment by ghost** [comment]
Update: Probably should have mentioned this in the original post: It's the forge gradle that has issues... Just created another test project with Forge and Spigot and the issue is still there, so it will probably be there with forge alone too.

**Comment by RedNesto** [comment]
Hi ! Sorry about that, I updated the forge template a while ago and did not test multi-project setups.

I'm pretty sure the fix is to use `project.version` instead of `version` in the jar manifest builder. I'll push a fix soon.
