### ISSUE TITLE
"Minecraft Class" generation helper is broken for versions below 1.13

### ISSUE THREAD

**Issue by ghost** [DemonWav/MinecraftDevIntelliJ#819]
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)
    Operating System (this has come up enough times to be worth noting): Windows 10 Home
    Target platform
        Forge
    Minecraft Version: 1.12.2

This issue is about the Minecraft Class generation context menu item. These are: 
"Block", "Item" and "Packet".

Each of them has errors upon generation. Firstly, Block and Item share the same issues:

Generated code:
Block:
```
package test.test.minecraftclasses;

import net.minecraft.block.Block;

public class TestBlock extends Block {
    public TestBlock(Properties properties) {
        super(properties);
    }
}
```
Item:

```
package test.test.minecraftclasses;

import net.minecraft.item.Item;

public class TestItem extends Item {
    public TestItem(Properties properties) {
        super(properties);
    }
}
```

The issue in these two are: 
Firstly, "Properties" isn't imported. I assume it's meant to be the "Properties" in the `net.minecraftforge.common.property` namespace...

Secondly, even if you import it... "Item()' in 'net.minecraft.item.Item' cannot be applied to '(net.minecraftforge.common.property.Properties)'" Similarly in the Block class it's the same, but "Block()' in 'net.minecraft.block.Block'

As far as I can see, neither Item or Block has a constructor that takes "Properties", as such, the constructor errors out...

I'm assuming the issue lies somewhere along the lines of "the constructor was added later than 1.12.2". I don't know if the plugin offers different "Minecraft Classes" dependent on what MC version you mod for...

As for the "Packet" class...

```
package test.test.minecraftclasses;

import net.minecraft.network.PacketBuffer;
import net.minecraftforge.fml.network.NetworkEvent;
import java.util.function.Supplier;


public class TestPacket {
    public TestPacket() {
    }
    public TestPacket(PacketBuffer buf) {
    }
    public void toBytes(PacketBuffer buf) {
    }
    public void handle(Supplier<NetworkEvent.Context> ctx) {
        ctx.get().enqueueWork(() -> {
        });
        ctx.get().setPacketHandled(true);
    }
}

The `import net.minecraft.forge.fml.network.NetworkEvent` isn't found- "network" isn't inside the "fml" namespace. 

That in turns makes most of the "handle" method invalid, since `NetworkEvent.Context`,  `enqueueWork()` and `setPacketHandled()` don't exist.
```

**Comment by Tom-The-Geek** [comment]
`Properties` is a subclass of Block/Item, but maybe forge changed the name? Same with the missing import from Forge, they might have changed the package

**Comment by ghost** [comment]
> 
> 
> `Properties` is a subclass of Block/Item, but maybe forge changed the name? Same with the missing import from Forge, they might have changed the package

As for the package, there is fml.common.network which contains an FMLNetworkEvent... that doesn't contain "Context" however. There is also an fml.common.events, but that doesn't contain anything with the name "network". 

Also, Properties is a subclass? It's not among the list of known direct subclasses on the forge javadocs from what I saw

**Comment by Tom-The-Geek** [comment]
Oh wait, you're on 1.12.2. The helpers are designed for _modern_ versions of Forge/Minecraft (1.13+) and so there will be problems using them on outdated versions.

**Comment by ghost** [comment]
> 
> 
> Oh wait, you're on 1.12.2. The helpers are designed for _modern_ versions of Forge/Minecraft (1.13+) and so there will be problems using them on outdated versions.

Mhm. I assumed that would be the situation... Do you know what the 1.12.2 alternative to the 3 classes would be?

**Comment by Tom-The-Geek** [comment]
This should be an item:
```java
import net.minecraft.item.Item;

public class ItemBasic extends Item {
	
	public ItemBasic(String name) {
		setUnlocalizedName(name);
		setRegistryName(name);
	}
}
```
and this a Block
```java
public class BlockBasic extends Block {

	public BlockBasic(String name, Material material) {
		super(material);
		setUnlocalizedName(name);
		setRegistryName(name);
	}
}
```
(don't trust me 100% on those, I haven't modded 1.12.2 for a long time, and not with Forge for a while either)

**Comment by ghost** [comment]
> 
> 
> This should be an item:
> 
> ```java
> import net.minecraft.item.Item;
> 
> public class ItemBasic extends Item {
> 	
> 	public ItemBasic(String name) {
> 		setUnlocalizedName(name);
> 		setRegistryName(name);
> 	}
> }
> ```
> 
> and this a Block
> 
> ```java
> public class BlockBasic extends Block {
> 
> 	public BlockBasic(String name, Material material) {
> 		super(material);
> 		setUnlocalizedName(name);
> 		setRegistryName(name);
> 	}
> }
> ```
> 
> (don't trust me 100% on those, I haven't modded 1.12.2 for a long time, and not with Forge for a while either)

Alright, I know that "setUnlocalizedName()" was removed. from what I've read, it was replaced with "setTranslationKey" but other than that, it looks good
