### ISSUE TITLE
[Type: Bug]-[System: Version Detection]-[Version: 2020.3-1.5.2-208] Suspected issue with plugin MC Version Detection

### ISSUE THREAD

**Issue by Lanse505** [DemonWav/MinecraftDevIntelliJ#820]
Software Versions:
  - Plugin: 2020.3-1.5.2-208
  - Intellij: 2020.3.1
  
Hardware:
  - OS: Windows 10 Pro 64-bit
  - CPU: Intel I7 7700k [ /w Virtualization Enabled ]
  - GPU: GTX 1080ti

Target Platform:
  - Forge (In my case, but I suspect this is more generic)

Conversation from Discord:
![bild](https://user-images.githubusercontent.com/1495068/105858436-9b286080-5feb-11eb-87cd-ef1edc1b73b2.png)

**Comment by Lanse505** [comment]
If additional information is required feel free to reach out on Discord.

**Comment by RedNesto** [comment]
Fixed by 92f39c1937f9ecef7cafafdb6d5dd404541601a0
