### ISSUE TITLE
Support for Architectury API

### ISSUE THREAD

**Issue by ThexXTURBOXx** [DemonWav/MinecraftDevIntelliJ#823]
I haven't seen this feature request yet, so I am just dropping this here as I have started developing my mods again after quite some time... Now, [Architectury API](https://github.com/architectury/architectury-api) seems to be another major modding API.

If there is interest in adding support for this multiplatform API, this would be great! :)

**Comment by DenWav** [comment]
I don't think I would call that major. Will leave this open and may be willing to merge PRs for it, but I don't think we're likely to implement this ourselves.

**Comment by ThexXTURBOXx** [comment]
Reopening since not yet implemented

**Comment by KP2048** [comment]
I can attempt this, I’d have to learn some kotlin though

**Comment by KP2048** [comment]
For some reason IntelliJ is not adding the sdk so all the idea plug-in stuff has broken imports.

**Comment by KP2048** [comment]
#1797

**Comment by KP2048** [comment]
pr ready to merge

**Comment by Charismara** [comment]
Damn you're awesome ❤️

**Comment by KP2048** [comment]
Feel free to clone my fork and build it :)

**Comment by KP2048** [comment]
Merged

**Comment by ThexXTURBOXx** [comment]
Thank you very much for your work :)

**Comment by Charismara** [comment]
Architectury Support on the next update 🥇 awesome!
