### ISSUE TITLE
Mixin lambda method target is not resolved, but code is valid

### ISSUE THREAD

**Issue by LCLPYT** [DemonWav/MinecraftDevIntelliJ#824]
**Minecraft Development for IntelliJ plugin version**: 2020.3-1.5.3
**IntelliJ version**: 2020.3.2 Community Edition
**Operating System**: Windows 10
**Target platform**: Mixin (Forge)

I think this screenshot describes the problem best:
![Screenshot 2021-02-16 152539](https://user-images.githubusercontent.com/35002345/108076263-87609f00-706b-11eb-99bc-aef2cd9ee675.jpg)

The mixin targets a lambda inside a function which looks like this:
```java
   private void renderParrot(MatrixStack matrixStackIn, IRenderTypeBuffer bufferIn, int packedLightIn, T entitylivingbaseIn, float limbSwing, float limbSwingAmount, float netHeadYaw, float headPitch, boolean leftShoulderIn) {
      CompoundNBT compoundnbt = leftShoulderIn ? entitylivingbaseIn.getLeftShoulderEntity() : entitylivingbaseIn.getRightShoulderEntity();
      EntityType.byKey(compoundnbt.getString("id")).filter((p_215344_0_) -> {
         return p_215344_0_ == EntityType.PARROT;
      }).ifPresent((p_229137_11_) -> { // <- the target lambda
         matrixStackIn.push();
         matrixStackIn.translate(leftShoulderIn ? (double)0.4F : (double)-0.4F, entitylivingbaseIn.isCrouching() ? (double)-1.3F : -1.5D, 0.0D);
         // etc.
      });
   }
```
In this case, the lambda passed to `.ifPresent(...)` is targeted.

This code is working completely fine, but the MinecraftDev plugin does not seem to recognize the lambda as a valid method for mixins and thus creates an error inside of IntelliJ.
To be fair, it's not really a declared method, but it's signature is clearly visible in the byte code:
```
 // access flags 0x1002
  private synthetic lambda$renderParrot$1(Lcom/mojang/blaze3d/matrix/MatrixStack;ZLnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/client/renderer/IRenderTypeBuffer;Lnet/minecraft/nbt/CompoundNBT;IFFFFLnet/minecraft/entity/EntityType;)V
   L0
    LINENUMBER 35 L0
    ALOAD 1
    INVOKEVIRTUAL com/mojang/blaze3d/matrix/MatrixStack.push ()V
```

To fix this problem, I guess lambdas should be looked up from byte code...

Link to the full **source code** of the mixin: https://github.com/LCLPYT/LCLPMMO/blob/3c62b821686ec30e9e5419e9066ddce8e0e626d7/src/main/java/work/lclpnet/mmo/asm/mixin/client/MixinParrotVariantLayer.java

**Comment by RedNesto** [comment]
See #724

**Comment by Earthcomputer** [comment]
#1221
