### ISSUE TITLE
Forge: There was an error while attempting to retrieve versions.

### ISSUE THREAD

**Issue by DAQEM** [DemonWav/MinecraftDevIntelliJ#827]
![idea64_2021-02-18_21-24-43](https://user-images.githubusercontent.com/66999025/108417862-cbe96780-7230-11eb-995d-d2c144d36189.png)

I've updated the plugin to the newest version but it still gave me this error.

**Comment by Tom-The-Geek** [comment]
This issue should be fixed in the latest nightly of the plugin, you can switch to it in the settings
