### ISSUE TITLE
"There was an error while attempting to retrieve versions"

### ISSUE THREAD

**Issue by DevLarge** [DemonWav/MinecraftDevIntelliJ#828]
![Capture](https://user-images.githubusercontent.com/71059839/108553115-83927e00-72f2-11eb-972f-2c735461cd68.PNG)

Having trouble with retrieving Minecraft versions with the IntelliJ plugin. 

I know of 1 other person who also has this problem, there may be more that I haven't heard of.

**Comment by RedNesto** [comment]
This is already fixed in the nightly channel
