### ISSUE TITLE
Can't make forge mod

### ISSUE THREAD

**Issue by goofyclown** [DemonWav/MinecraftDevIntelliJ#833]
Plugin version: 2020.3-1.5.3-211 (used nightly channel for updates)
Intellij version: one of the latest
OS: Windows 10
Target platform: Forge

When I try to make a forge mod here what happen: 
![image](https://user-images.githubusercontent.com/42712457/109381650-e16b2b00-78db-11eb-95e7-db097453ece0.png)

**Comment by RedNesto** [comment]
The latest nightly build is 213.
If IntelliJ can't find the new version you can try reinstalling the plugin, and make sure only one channel (Nightly) is selected in the plugin repositories list (the gear in the plugins page.)

**Comment by PierreBouffartigue** [comment]
This solution works, but I confirm that the problem is present without this manipulation

**Comment by Earthcomputer** [comment]
"I confirm this problem is present if I don't update", thanks

**Comment by goofyclown** [comment]
well i tryed 
![image](https://user-images.githubusercontent.com/42712457/109386508-57cb5580-78fb-11eb-9f82-0d706bc08682.png)

**Comment by RedNesto** [comment]
I also got the plugin stuck on a specific version, what I usually do is:
1. uninstall the plugin
2. go to the plugin repositories list and remove all entries that contain `8327`
3. install the plugin, it should use a stable version now
4. go to the plugin updates settings, Stable should be selected. Switch to Nightly and check for updates

**Comment by goofyclown** [comment]
i tryed but i can only get version 211 :(

**Comment by RedNesto** [comment]
Try to install the plugin manually then.
Download [the build 213](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/nightly/110887) and dragndrop it into an IDEA window, or use the "Install plugin from disk" action.

If it refuses to install logs would be useful.

**Comment by goofyclown** [comment]
i used intellij eap and seems to work i guess

**Comment by gitmylo** [comment]
> 
> 
> i used intellij eap and seems to work i guess

this also worked for me
