### ISSUE TITLE
[1.16.5]Breakpoint does not let go off my mouse

### ISSUE THREAD

**Issue by tmvkrpxl0** [DemonWav/MinecraftDevIntelliJ#838]
DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.

Please include the following information in all bug reports:

* Minecraft Development for IntelliJ plugin version
* IntelliJ version 
* Operating System (this has come up enough times to be worth noting)
* (optional) Target platform, if relevant
  * E.g., Bukkit, Forge, Mixin, etc

Always include a stack trace if there is one. Otherwise, the more information you can provide in terms of how to reproduce the problem, the more likely it'll be fixed. If there is something specific about your project, a link to the GitHub project can be very helpful.

I'm using Intellij 2020.3-203.5981.155 on Linux mint, After updating forge to official mapping, Hitting breakpoint does not let go off my mouse anymore, It seems that official mojang mapping is not compatible with MinecraftDev
Minecraft version i'm currently using is 1.16.5, Forge is latest version(36.1.2)

**Comment by tmvkrpxl0** [comment]
I have updated both Intellij and MC-Dev and it's still not fixed

**Comment by Earthcomputer** [comment]
If you want it fixed faster you can always PR

**Comment by DenWav** [comment]
This has been fixed at least 4 times by this point. Not sure what's the issue here though, would have to look at it.

**Comment by SizableShrimp** [comment]
The issue lies in official mappings just not being loaded for whatever reason. I tried to look at the internals and see how it was loaded etc. but was hindered by a Jetbrains service being down until recently.

**Comment by T3sT3ro** [comment]
Came here with the same issue. Still present on 2021.2-1.5.15 MC-Dev plugin for 1.17 branch (although IMO MC version is irrelevant). The hope could lie [in the upcoming 2022.xxx version of IDEA](https://youtrack.jetbrains.com/issue/IDEA-279606#focus=Comments-27-5484691.0-0).

@EDIT if this issue resurfaces again in the future I recommend [the `XF86Ungrab` method](https://unix.stackexchange.com/questions/40458/command-for-forcing-a-pointer-ungrab-captured-mouse-release). Just be aware to read through warnings and recognize, that [`XF86ClearGrab` kills the client with active grab](https://cgit.freedesktop.org/xorg/xserver/commit/?id=7d2543a3cb3089241982ce4f8984fd723d5312a1), while `XF86Ungrab` just ungrabs.

**Comment by tmvkrpxl0** [comment]
I have completely forgotten about this issue and the issue is still present somehow

**Comment by Earthcomputer** [comment]
https://github.com/minecraft-dev/MinecraftDev/commit/a4b4bb161f63a6cdef0f72a01224c3e23bd54cf8
