### ISSUE TITLE
MCP/VanillaGradle template

### ISSUE THREAD

**Issue by AverageComet250** [DemonWav/MinecraftDevIntelliJ#839]
Can we have a template for modifying client-side Minecraft without a modloader?

**Comment by Earthcomputer** [comment]
No

**Comment by AverageComet250** [comment]
Okay

**Comment by jamierocks** [comment]
Might be handy to support VanillaGradle though.

**Comment by Earthcomputer** [comment]
Handy for a very small number of people, who probably already know how to create a VanillaGradle project manually, which only takes a little longer. Bear in mind this discussion is only about the project generator, after you have a project, mcdev features should work normally.

**Comment by jamierocks** [comment]
Oh I didn't realise that the plugin already supported VanillaGradle 🥳

**Comment by AverageComet250** [comment]
Is there MCP support as well?

**Comment by Earthcomputer** [comment]
Only MCP *mappings* support.

**Comment by DenWav** [comment]
Coming soon™️ there will be much better distinction when it comes to mappings, and mapping support will be generic and include Yarn and Mojmap etc.
