### ISSUE TITLE
[Fabric] entrypoint inner classes naming issue

### ISSUE THREAD

**Issue by CreepyCre** [DemonWav/MinecraftDevIntelliJ#845]
* Minecraft Development for IntelliJ plugin version: **2020.3-1.5.4**
* IntelliJ version: **IC-203.7148.57**
* Operating System (this has come up enough times to be worth noting): **Windows**
* (optional) Target platform, if relevant: **Fabric**

The plugin seems to evaluate entrypoints in inner static classes wrong, relevant example:
https://github.com/DimensionalDevelopment/DimDoors/blob/1.17/src/test/resources/fabric.mod.json

In this example `org.dimdev.dimdoors.api.DimensionalDoorsApiTest$DimDoorsTestApi` is marked red and it says
`Cannot resolve entry point 'org.dimdev.dimdoors.api.DimensionalDoorsApiTest$DimDoorsTestApi'`.
If you write `org.dimdev.dimdoors.api.DimensionalDoorsApiTest.DimDoorsTestApi` instead the plugin is able to resolve the entrypoint, it will however not work since fabric uses `Class#fromClass`, which requires `$` instead of `.` for inner classes, to load the entrypoints.

Relevant source for the naming of inner classes:
https://jcp.org/aboutJava/communityprocess/maintenance/JLS/innerclasses.pdf

**Comment by Earthcomputer** [comment]
https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/kotlin/platform/fabric/reference/EntryPointReference.kt#L53
This needs to replace `$` with `.`, I think
