### ISSUE TITLE
Support for custom `TextColor` constants and static imported methods

### ISSUE THREAD

**Issue by jpenilla** [DemonWav/MinecraftDevIntelliJ#846]
The new Adventure support is awesome and works great for `NamedTextColor`s and when using the `TextColor.color` methods. However when statically importing these methods the support no longer functions.
Also, custom `TextColor` constants do not get the same gutter highlight as `NamedTextColors` when used.

Here is an image illustrating the difference:
![image](https://user-images.githubusercontent.com/11360596/114117130-dcb27300-989a-11eb-9468-6fab767bd78f.png)
(edit (unrelated): I'm also noticing that the qualified `NamedTextColor.RED` renders different from the same constant statically imported)

**Comment by RedNesto** [comment]
Both static imports issues are already fixed by #811.

I'll look into evaluation of user-defined color constants.

**Comment by RedNesto** [comment]
I believe this issue is completely fixed now.

**Comment by jpenilla** [comment]
> I believe this issue is completely fixed now.

Can confirm! Thanks!
