### ISSUE TITLE
MCP-Reborn

### ISSUE THREAD

**Issue by 12jking** [DemonWav/MinecraftDevIntelliJ#853]
Could you please add MCP-Reborn [()](https://github.com/Hexeption/MCP-Reborn)

**Comment by Earthcomputer** [comment]
No

**Comment by 12jking** [comment]
why?

**Comment by Earthcomputer** [comment]
Because we don't want to encourage jarmodding. Use a mod loader such as Forge, Fabric, Sponge, etc

**Comment by 12jking** [comment]
oh ok
