### ISSUE TITLE
Cleanup and update project creator templates

### ISSUE THREAD

**Issue by RedNesto** [DemonWav/MinecraftDevIntelliJ#929]
I noticed when working on #928 that the current templates are getting a bit dusty:
- we are using Gradle 5 by default, Gradle 7 has been released for almost 2 months by the time of writing this
- many Gradle buildscripts use deprecated or non-optimal stuff
  - the `maven` plugin was removed
  - `processResources` tasks should use `expand` instead of `from(...) {filter... }` and specify `inputs.properties`
  - use the `plugins` block as much as possible (noticed this with the shadow plugin in multi-project setups)
  - upgrade plugins (we still use shadow 4 while on Gradle 5); SpongeGradle might have received updates since then too
  - other things ?
- Forge 1.12.2 projects still use ForgeGradle 2 while FG 4 can be used (thanks to the amazing work of the retrogradle project contributors)
  - it might be even better to drop 1.12, that's something to decide
- the velocity macros can be used a bit more efficiently, for example we can replace `#if (${HAS_AUTHORS})` by just checking `#if (${AUTHORS})` and set its value to `null` in the context.

I noticed all of this while working on the SpongeAPI 8 plugin template and plan to work on this after getting it merged, but if someone wants to tackle this task let me know.

**Comment by Toerktumlare** [comment]
will this be merged, i tried out the plugin today, starting a fabric mod and nothing built and had to spend quite some time trying to problem solve this. I have never worked with gradle before so this took me quite some time to figure out.

**Comment by Chiharu-Hagihara** [comment]
so i will use maven here after.
