### ISSUE TITLE
New project fails to create with Java 16 and Gradle

### ISSUE THREAD

**Issue by jacobsandersen** [DemonWav/MinecraftDevIntelliJ#936]
* Minecraft Development for IntelliJ plugin version: 2021.2-1.5.11
* IntelliJ version: 2021.2 EAP (212.3116.43)
* Operating System: Windows w/ WSL; IntelliJ is on Windows, Java & Gradle are on Linux

I am running Java 16.0.1 (AdoptOpenJDK-16.0.1+9) and I attempted to create a new project with this plugin on IntelliJ 2021.2 EAP. Everything mostly works, but this comes up:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_init remapped class cache for 8lyebhvpycvp55bdjq68eafm6 (/home/simple/.gradle/caches/5.6.1/scripts-remapped/ijtgtmapper1_7qje24re1bfm1hrl1a0070c19/8lyebhvpycvp55bdjq68eafm6/cp_inite7ca86eb00f9d6cbee2b842ef043afcb).
> Could not open cp_init generic class cache for initialization script '\\wsl$\Arch\home\simple\workspace\minecraft\MySecondPlugin\.gradle\ijtgtmapper1.gradle' (/home/simple/.gradle/caches/5.6.1/scripts/8lyebhvpycvp55bdjq68eafm6/cp_init/cp_inite7ca86eb00f9d6cbee2b842ef043afcb).
   > Could not initialize class org.codehaus.groovy.classgen.Verifier

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I can fix it by simply updating gradle:
`gradle wrapper --gradle-version 7.0.2 --distribution-type all`

I believe then that this is related to #929. Let me know if I can provide more information.

**Comment by RedNesto** [comment]
I get an exception about `InvokeHelper` on a fresh spigot project, but they have most certainly the same cause.
