### ISSUE TITLE
Failure to parse AttributeModifiers in nbt file; results in corruption

### ISSUE THREAD

**Issue by TelepathicGrunt** [DemonWav/MinecraftDevIntelliJ#974]
Intellij 2020.3.3, MC Dev Plugin 1.5, Minecraft 1.16.5, Windows

When opening an nbt file that has an extremely small or large value, Minecraft Dev Plugin will try and parse it as a float but then when displayed, it breaks all formatting as it expects a double and not `E-4` tacked on the end due to how the number was parsed as a float. When the file is saved after opening it, it corrupts the nbt file and reduces it down to 1kb, thus losing all the saved work on it.  

Example nbt file that will fail to parse:
[pyramid_flower_forest_pit.zip](https://github.com/minecraft-dev/MinecraftDev/files/6648333/pyramid_flower_forest_pit.zip)

The parse error:
![image](https://user-images.githubusercontent.com/40846040/121893529-0d27ea80-ccec-11eb-8d55-295aa3f39a8b.png)

What the attribute looks like in NBTExplorer:
![image](https://user-images.githubusercontent.com/40846040/121893894-7f003400-ccec-11eb-8e8c-f052031ac7cb.png)

Before and after the file is saved after being opened by Minecraft Dev plugin:
![image](https://user-images.githubusercontent.com/40846040/121893695-482a1e00-ccec-11eb-8afc-d09fd6ed9cfe.png)
![image](https://user-images.githubusercontent.com/40846040/121893620-2b8de600-ccec-11eb-9e6e-7368d0fd9341.png)

**Comment by RedNesto** [comment]
Thanks for all those details and the sample. The fix will be available in the next nightly build (should be `1.5.11-246`) that will be built in a couple of hours. I'd appreciate if you can verify this issue is fixed, thanks!

**Comment by TelepathicGrunt** [comment]
Sorry for delay as I had window update corrupting issues... But yep the new build works and the nbt does not get corrupted. Thank you!
