### ISSUE TITLE
minecraft:alternatives is not recognized as a valid loot entry type

### ISSUE THREAD

**Issue by TheOnlyTails** [DemonWav/MinecraftDevIntelliJ#986]
## General Information

* Minecraft Development for IntelliJ plugin version: 2021.1-1.5.11-245
* IntelliJ IDEA 2021.1.2 (Ultimate Edition)
* Windows 10 - Build 21390

![image](https://user-images.githubusercontent.com/65342367/123236376-6a3e5000-d4e5-11eb-8370-bf46aef70dbf.png)

**Comment by RedNesto** [comment]
I have no idea where this inspection comes from. Do you have a custom JSON schema installed for those files ?

**Comment by TheOnlyTails** [comment]
My bad, I forgot about that. Sorry!
