### ISSUE TITLE
SpongeAPI 8 plugin template broken

### ISSUE THREAD

**Issue by avaruus1** [DemonWav/MinecraftDevIntelliJ#993]
Minecraft Development for IntelliJ plugin version: 2021.1-1.5.11
IntelliJ version: 2021.1.2
Operating System: Arch Linux

---

The Sponge API-8 plugin template appears to be broken. Using it results in a plugin created with the API-7 template, only with spongeapi version 8.0.0-SNAPSHOT instead of the 7.x one.

**Comment by avaruus1** [comment]
Nevermind. I just noticed the latest stable version of this plugin was released almost a month ago and the sponge-8 branch was merged yesterday. Apologies for my stupidity.

**Comment by RedNesto** [comment]
Yeah sorry about that, I'll see if we can make a release soon.
